### ISSUE TITLE
Does not cope well with subfolders

### ISSUE THREAD

**Issue by Karajorma** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#1]
The extension seems to fail if you have any files in subfolders even though Stable Diffusion has no problem with this. For instance all my models are divided into sub-folders named things like characters, styles, etc. The extension ignores these and only gets information for anything in the models/stable-diffusion folder.

**Comment by butaixianran** [comment]
It does not support sub folders for now. I'm not sure it is needed for most cases

**Comment by butaixianran** [comment]
It support subfolder now, you can update and try.

**Comment by butaixianran** [comment]
It's done
