### ISSUE TITLE
【建议】增加aria2下载支持

### ISSUE THREAD

**Issue by fungyua** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#100]
使用aria2测试下载后，速度有明显提升。

![image](https://user-images.githubusercontent.com/48909759/230675754-10d760a8-2e95-4ba8-8a77-252aaeb6da94.png)

![image](https://user-images.githubusercontent.com/48909759/230676466-6945e9ba-ede2-46f0-b457-5c6bf0e922ce.png)

使用requests下载的速度没有达到预期。

**没有测试结果**

**Comment by butaixianran** [comment]
不打算支持。凡是需要用户额外安装的东西，都会带来各种麻烦。尤其是有墙的存在。

本插件将坚守用户无须下载任何额外代码库的原则。不管是civitai helper还是开发中的2.0的model info helper


另外，不使用启动器，直接运行webui-user.bat的话，进度条是可以显示在一行内，无须换行的。

**Comment by tastypear** [comment]
我在docker环境里跑，下载确实很慢。以colab为例，速度只有2M/s，单线程wget却能达到50M/s。

然而这又是唯一能正常运行的插件，正如作者所说，引入额外的库会出现问题，比如Civitai Browser在docker里就不能下载。

如果有变通的方式原生支持多线程就好了。

**Comment by butaixianran** [comment]
想要多线程还是使用专门的下载工具，再放入模型目录比较好。

下载工具的需求是个无底洞，远超本插件的涵盖范围，建议使用专门的工具。

另外，本项目文档开头列出来了另外两个开源的fork，可以尝试下是否有改善。
