### ISSUE TITLE
功能建議

### ISSUE THREAD

**Issue by bluelovers** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#102]
Civitai Helper 分頁

1. 在已經安裝的模組當中尋找重複模組
2. 以模組主訊息來分組，也就是同一個模組底下不同版本的模組都歸類再一起

**Comment by butaixianran** [comment]
1. wait for 2.0
2. won't do it

**Comment by bluelovers** [comment]
希望能支援更改 lora 檔名(一併修改 info 與 預覽圖)

**Comment by bluelovers** [comment]
允許套用提示詞時，只套用正向提示詞
