### ISSUE TITLE
TI with negative

### ISSUE THREAD

**Issue by Apkawa** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#104]
Example https://civitai.com/models/2289/psycho-style, https://civitai.com/models/1998/autumn-style

Currently helper not  download negative file `style-psycho-neg.pt`

**Comment by butaixianran** [comment]
Extension can download it well. There is no different between negative TI and normal TI when downloading.

**Comment by Apkawa** [comment]
But look https://civitai.com/models/2289/psycho-style
Civitai talk about negative embed, this additional variant for TI
![image](https://user-images.githubusercontent.com/16043/230785793-a5693aee-403e-4ff2-b37b-5f7a0667bd7e.png)
Author talk about requirements
![image](https://user-images.githubusercontent.com/16043/230785830-b3f8c5fe-e0b4-4b79-9a0e-99f5b93fbda6.png)

I think in this case need download two file, `style-psycho.pt` and `style-psycho-neg.pt`

**Comment by butaixianran** [comment]
Downloading multiple files can not be supported. Civitai API only has 1 download url in it.

**Comment by Apkawa** [comment]
I checked api
https://civitai.com/api/v1/models/2289
I think need check `modelVersions[0].files[1].type == 'Negative'`
![2023-04-09-202547_831x708_scrot](https://user-images.githubusercontent.com/16043/230787276-ead3992f-ea38-4da3-9909-fe19f9316d1e.png)

**Comment by butaixianran** [comment]
OK, this is not written in the API document. I'll see what I can do.

**Comment by butaixianran** [comment]
Done, update your extension. You need to re-launch  sd webui after updating, not just reload UI.

**Comment by Apkawa** [comment]
Thank you very much!
I checked, it works as I wanted
