### ISSUE TITLE
HTTPSConnectionPool 有人遇到吗?

### ISSUE THREAD

**Issue by h3clikejava** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#108]
点击Scan的时候报错:  
  raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='imagecache.civitai.com', port=443): Max retries exceeded with url: /xG1nkqKTMzGDvpLrqFT7WA/9dfd6f56-2538-4e6c-950f-afab73969a00/width=640/74136.jpeg (Caused by SSLError(CertificateError("hostname 'imagecache.civitai.com' doesn't match either of '*.bulletin.com', '*.alpha.bulletin.com', '*.beta.bulletin.com', '*.cinyour.bulletin.com', '*.prod.bulletin.com', '*.trunkstable.bulletin.com', 'bulletin.com'")))

**Comment by Un1ess** [comment]
遇到了，请问楼主解决了吗

**Comment by h3clikejava** [comment]
解决了，需要全局翻墙
