### ISSUE TITLE
Preview images not showing

### ISSUE THREAD

**Issue by Schwifty246** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#111]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
None of the preview images are showing. Despite reinstalling everything i could think of and making changes based on the claim wall i havent been able to fix it. Ive opened every png downloaded and have deleted and redownloaded all of them.

## Screenshot for UI issue
![image](https://user-images.githubusercontent.com/111214636/231575812-38061012-da23-4958-bdbc-f2162e859bd5.png)

## Console log's msg or screenshot for function issue
"There is no image in gallery to save as a preview. "

**Comment by butaixianran** [comment]
When there is no preview image, there will be a default image displayed on those model cards, which is a build-in feature of SD webui, no matter you have this extenion or not. 
![Snipaste_2023-04-13_07-05-48](https://user-images.githubusercontent.com/5558722/231605089-d93801ae-9fe8-4a45-ae46-6d6c2d620b99.jpg)

In your screenshot, you don't even have that default preview image.

So, there is something wrong about your SD webui. Even your webui itself is not working. 

Have you modified model folder's name?

**Comment by Schwifty246** [comment]
Firstly thank you for responding so quickly. No I just did a fresh install
today without chanting anything.

**Comment by butaixianran** [comment]
Still, your sd webui is not working. You see, this extension, does not show preview images for you. this extension just put images there, then SD webui will load them. 

So, display preview images, is a build-in feature of SD webui. And in your sd webui, it's not working.

So, your issue is not related to this extension at all. You should ask why your extra network does not display any preview image in a webui's community.

**Comment by Schwifty246** [comment]
Alright I’ll see what I can do. Thanks for the information

**Comment by GawainProdigy** [comment]
I have A1111 on c: and checkpoints on d:  Might this cause the issue? I too have this, deleting extension, rebooting, ad naseum doesn't work.

**Comment by butaixianran** [comment]
Again, this is not an issue of this extension. This extension just put image there. It is your sd webui who should display them.
Ask it at sd webui's official issue list.

**Comment by GawainProdigy** [comment]
Nice. It's working nicely. Sry to bother u; and, thx 4 the prompt reply.
