### ISSUE TITLE
Feature Request - Pull Triggers & Description Info into a <modelname>.txt

### ISSUE THREAD

**Issue by DreamOfGit** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#113]
Feature Request - Pull Trigger Words & Description Info into a <modelname>.txt

AKA, When you fetch the preview image can we also fetch any Trigger Words / Descriptions as well?
Sometimes a Civitai model I download gets deleted and I forget all the specifics around how to best use it. I find myself writing these text files everytime now to capture relevant prompting info.

**Comment by butaixianran** [comment]
wait for 2.0

**Comment by midcoastal** [comment]
PR inbound
