### ISSUE TITLE
Feature Request: Please add support for LyCORIS

### ISSUE THREAD

**Issue by kerror** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#115]
Hello,

Not sure how long until version 2, but would love to see this feature in this version 1 if possible. Could you add support for https://github.com/KohakuBlueleaf/LyCORIS extension which adds the LyCORIS tab to the webui? Currently, your tool doesn't scan this directory.

Thanks!

**Comment by butaixianran** [comment]
we only support sd webui's build-in features, won't support any extension. You can ask sd webui's team to support LyCORIS.

**Comment by Kepler-16b** [comment]
I've got better idea. Why don't we add simple function to rename LoRA / Checkpoints based on their info? For example, if a checkpoint is based on SD2.1-768 then rename it automatically to something like v2-checkpoint_name. And for LyCORIS, just do the same, LoHA / LoCON-original_name. This way possible confusion can easily be prevented.
Also save you from using additional LyCORIS extension (don't see the point of using it anyways).

**Comment by kerror** [comment]
> we only support sd webui's build-in features, won't support any extension. You can ask sd webui's team to support LyCORIS.

All I am asking is for your tool to scan another directory in the webui folder structure... You already scan the embeddings folder, hypernetworks, lora, and stable-diffusion folders. Why not add the additional LyCORIS folder?

The extension I referenced adds a LyCORIS directory under the models directory. 

I'm not sure I understand how the sd webui's team could help here? Could you explain? It is your tool that adds the pictures and the .info files...

**Comment by kerror** [comment]
> I made this change on my fork, you can use it. https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/tree/Add-LyCORIS-parsing #107

Thank you, I'll check it out and test it.

**Comment by FutonGama** [comment]
I recommend to add this function officially cause many users are already using Lycoris instead of normal Loras.
https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/tree/Add-LyCORIS-parsing #107
Huge Thank you!
