### ISSUE TITLE
Download faster with aria2

### ISSUE THREAD

**Issue by Efreak** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#117]
Currently I download my SD models and Loras either with the batchlinks extension or outside of a1111 entirely. Can you implement aria2 (or [other method](https://stackoverflow.com/q/58571343/4856479)) for downloading models with multiple connections? It would be nice to get the information without having to so a scan after each download (colab *really* doesn't like this, and occasionally drive disconnects while scanning, necessitating remounting drive and restarting A1111)

**Comment by butaixianran** [comment]
this extension won't support any third part downloading tool. 

you can try tocreate your own fork for that or wait for other developer's fork.

**Comment by Efreak** [comment]
Disappointing, but understandable.

Also, I've noticed that very occasionally, the UI seemingly freezes, but I'm 99% sure this is gradio, possibly the websocket connection being lost. You might consider adding a note that if there's no civitai helper activity in the console and you can't click any buttons, that reloading the page should help. Not sure about chrome, but in Firefox, right click and duplicate tab will keep all form inputs, (including those that aren't saved in params.txt, like prompt cutoff extension); after this you can close the original tab
