### ISSUE TITLE
Previews are *way* too big for many models

### ISSUE THREAD

**Issue by Efreak** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#118]
Some thumbnails have ridiculous sizes. My (admittedly fairly large) collection of Loras and TIs has a combined total of >350mb just for thumbnails. I ran an imagemagick script to deal with this, and stored the results on my own server with a redirector extension to modify requests, but it doesn't help with newly installed models. The biggest example I have is [hamunaptra style](https://civitai.com/models/4157/hamunaptra-style), [at 18mb](https://i.imgur.com/rd3NrqL.png) for an animated png file it's far larger than the TI file itself.

This causes issues with both bandwidth usage and limit on the total number of simultaneous connections (imposed by either cloudflare, the browser, colab, or python, not sure which). Once I open the networks interface, it doesn't want to let me do much of anything until all the previews finish loading; usually I either enable my redirector extension mentioned above and do without previews of recent items, or I copy my prompt settings and reload the tab so I can actually use them.

It would be nice to use server-side cropping to only send the browser the exact pixels that will be displayed. Alternatively, a way to have the browser request previews directly from civitai's imagecache instead of A1111 (easier, but I haven't tested to see if civitai's imagecache subdomain goes down every time their main servers do)    

-----

*I realize that you're working on a 2.0 version of this extension. I'm not asking for anything urgently with this (or my other request), just asking that you consider this* (and hopefully have some kind of solution, but if not I'll keep using my redirector)

**Comment by butaixianran** [comment]
there is an option on extension's tab page to download full size of preview image. Uncheck it to download small size of preview images.

**Comment by Efreak** [comment]
I did do this for a while, but even then the number of requests has gotten too big and still causes issues. Instead, I've started redirecting requests to another server entirely, which does quite a lot to fix it. Now if only my generations would go faster...
