### ISSUE TITLE
Lycoris scan support

### ISSUE THREAD

**Issue by timpf83** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#119]
With the growing support of lyCORIS it would be great if you could support scanning those too and linking to civitai as it is the case with models, LORA etc.
LyCORIS are a semi-new attempt to improve on LoRAs in multiple ways, including the ability to learn more layers. With the rise early models it seems like it is here to stay.

**Comment by butaixianran** [comment]
this extension won't support any other extensions. it will only support sd webui's build-in feature.

you can ask sd webui support that first.

**Comment by goldmojo** [comment]
You can try my fork [https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/tree/Add-LyCORIS-parsing](https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/tree/Add-LyCORIS-parsing)
I will try to keep it up to date until it is integrated to the webui officially.

**Comment by jyuan15** [comment]
You can move the lycoris model to the Lora folder for scanning, and after obtaining the image and info of the model, cut them into the LyCORIS directory.

**Comment by Lute-4** [comment]
See:
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/107

**Comment by dhwz** [comment]
@goldmojo could you please make your Add-LyCORIS-parsing to your default branch on your repository so the webui extension update doesn't update back to your main branch, thx

**Comment by goldmojo** [comment]
> @goldmojo could you please make your Add-LyCORIS-parsing to your default branch on your repository so the webui extension update doesn't update back to your main branch, thx

It's done.

**Comment by Dawgmastah** [comment]
> this extension won't support any other extensions. it will only support sd webui's build-in feature.
> 
> you can ask sd webui support that first.

Lycoris support officially added today to [1.5.0 version] of automatic111

Will extension be updated?

**Comment by dhwz** [comment]
Update of the extension is no longer required as it's integrated into Lora

**Comment by butaixianran** [comment]
This is done in another repo
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
