### ISSUE TITLE
Model Version dropdown field is not refreshed when downloading several models from url in a row

### ISSUE THREAD

**Issue by uselessgithub** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#123]
## Describe Issue
When using "Download Model", input a Civitai URL and click "1. Get Model Info by Civitai Url" button. The model info is correctly populated, including "Model Version" dropdown (for example version "1.2345").
Now do it again with another url and click "1. Get Model Info by Civitai Url" button. The Model name is correctly refreshed with the new model, but the Model version is stuck on the previous version "1.2345".

First download OK
![OK](https://user-images.githubusercontent.com/53917777/233835731-899d80fa-6723-421d-9578-290a14994250.png)

Second model download incorrect Model Version
![NOK](https://user-images.githubusercontent.com/53917777/233835767-38c4b2cb-04fd-472d-865b-ae3abe724eb0.png)

**Comment by butaixianran** [comment]
hi, the list is actually changed, but it won't select a new value for you automatically.

so you just need to click that dropdown list and pick a new value.

**Comment by Elec0** [comment]
> hi, the list is actually changed, but it won't select a new value for you automatically.
> 
> so you just need to click that dropdown list and pick a new value.

For me neither Subfolder or Version auto-populate on first update either.

<details>
<summary>Terminal output</summary>

```
Civitai Helper: Getting model info by: https://civitai.com/models/15365/hanfu
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai
Civitai Helper: Get subfolder for: C:\Users\elec0\Documents\GitHub\stable-diffusion-webui\models\Lora
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:hanfu 汉服
Civitai Helper: model_type:lora
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['v3.0_54777', 'v3.1-tang_63077', 'v3.1-song_63081', 'v2.8_21656', 'v3.0-song_39043', 'v3.0-ming_30796', 'v2.0_18795', 'v2.9_27946', 'v2.1(Focus Clothes)_19475', 'v1.0_18106']
```

</details>

But why would it not select a new value for you automatically?
The versions are almost certainly not going to be the same, so what's the point of keeping the old version?

## Example
### Lora 1
**URL:** https://civitai.com/models/15365/hanfu
**Versions:** `['v3.0_54777', 'v3.1-tang_63077', 'v3.1-song_63081', 'v2.8_21656', 'v3.0-song_39043', 'v3.0-ming_30796', 'v2.0_18795', 'v2.9_27946', 'v2.1(Focus Clothes)_19475', 'v1.0_18106']`
### Lora 2
**URL:** https://civitai.com/models/8484/yae-miko-or-realistic-genshin-lora
**Versions:** `['YaeMiko-Mixed_11523', 'YaeMiko-Full_10003', 'YaeMiko-Standard_10002']`

And the version stays as 
![image](https://user-images.githubusercontent.com/5119098/236974871-b70d872b-02cf-486e-b7d9-0c309a3df027.png)

Which will never be correct.

It should automatically pick the most recent version. If you really want to keep the old version, you should check if the old version is even an option in the incoming versions.

**Comment by butaixianran** [comment]
The model version list is refreshed, but due to gradio's problem, it won't select a new value for you automatically. You need to select an option from version list.
