### ISSUE TITLE
It does not scan models under the root folder when the --ckpt-dir command option is specified.

### ISSUE THREAD

**Issue by H20-DHMO** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#126]
Thank you for creating this wonderful extension!

I have a small SSD space, so I place the models I use often in the root and move the models I use only occasionally to the HDD.
If I specify ``--ckpt-dir`` in the startup options, the Stable Diffusion web UI will load both models.
Currently, the scan by civitai helper scans models in the specified path, but not models under the root folder.
Is it possible to fix it so that it scans both models as well as the Stable Diffusion web UI?

**Comment by butaixianran** [comment]
Multiple model folder is not supported. And won't be supported in this version.

I'll try to find a way to handle that in version 2.0
