### ISSUE TITLE
没有预览图文件。其他功能一切顺利。

### ISSUE THREAD

**Issue by 1270156695** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#129]
Hi，非常感谢你创建的插件帮助我们提高效率。
我浏览过常见问题，也看完了已解决的issues，没有找到解决方法
我推测原因可能是：我的模型中创建了[大模型] 和 [Lora]两个文件夹

## Describe Issue
问题：只是没有对应的图片文件；
其他情况： 扫描正常；刷新正常；4个图标功能正常；模型Lora对应的info文件正常；代理正常。

## Screenshot for UI issue
![14751682473289_ pic](https://user-images.githubusercontent.com/74035643/234444555-af2cc7d8-8c92-4893-bb92-34a250a6b595.jpg)
![14741682473258_ pic](https://user-images.githubusercontent.com/74035643/234444590-b00d9d51-0694-4715-93a9-83e3a8838e75.jpg)
![14761682473430_ pic](https://user-images.githubusercontent.com/74035643/234444600-d849ff1c-0b7a-471e-8b7f-02cc6ff71ac9.jpg)

**Comment by butaixianran** [comment]
你的模型目录下没有下载预览图，自然就不会显示。

如果你的模型不在civitai上，就无法下载预览图。只会建立一个空的没有内容的info文件。


你可以用文本编辑器打开info文件看看是不是空的

**Comment by 1270156695** [comment]
感谢回复！
很幸运，info里是有内容的，完整内容如下：
![14821682490254_ pic](https://user-images.githubusercontent.com/74035643/234487738-be9ecc4b-c939-47d0-bd9f-7dfc8d919e37.jpg)

**Comment by 1270156695** [comment]
好消息，问题找到了：
我做了三次测试，每次测试前 删除所有PNG和info文件。
对比测试后发现，勾选NSFW时会没有图片，不勾选时一切顺利。

问题已解决。感谢你为我们无私付出！！！👍
