### ISSUE TITLE
Indent civitai.info json files

### ISSUE THREAD

**Issue by Zyin055** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#13]
Can you format the civitai.info json files so they are indented?

Should be easy to do with `data = json.dumps(content, indent=4)`

I'd like it to be human readable so that I can add my own trigger words if the author doesn't include them.

**Comment by butaixianran** [comment]
ok, I'll make it into an option.

**Comment by MrKuenning** [comment]
I agree, but I think maybe taking it a step further and include a metadata editor on the Helper Tab.

See my request here: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/18

**Comment by dsully** [comment]
Please also have the file extension be `.json` instead of `.info` so that editors such as vim/neovim can properly highlight.

**Comment by butaixianran** [comment]
No, ext will be `.info` to make sure it is for this extension, not a json file with anyother file structure.

You should know that, edit it manually is never a purpose of this extension. Consider it as a hacking way. And you can config your text edit tool to treat it as .json.

**Comment by dsully** [comment]
I understand that one shouldn't edit it, but purposefully having a extension that is generic is not useful in my opinion.

**Comment by butaixianran** [comment]
This is done.
