### ISSUE TITLE
Download Model is not done

### ISSUE THREAD

**Issue by horoabb** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#130]
I use AUTOMATIC1111 webui

Download Model-webui is done ,but backend cmd just download 40% or XX% not finish。

**Comment by butaixianran** [comment]
its your network issue, you can download it again.

**Comment by horoabb** [comment]
Are you sure? 
sometimes happen

**Comment by butaixianran** [comment]
You don't need to delete the unfinished file, It can download from break point, so you don't need to download from beginning.

It is mentioned in the document.

**Comment by horoabb** [comment]
hmm,next time i try it.

before, webui say this file is exist, so i go delete not finish files

**Comment by butaixianran** [comment]
unfinished downloading file is named as `model_name.downloading`. Which is not used by sd webui, so there is no way sd webui says there is a unfinished downloading file.

**Comment by Golgovskiy** [comment]
> You don't need to delete the unfinished file, It can download from break point, so you don't need to download from beginning.
> 
> It is mentioned in the document.

No, it downloads a new one. Old one is still here. It really needs some error handling.

**Comment by create-msugi** [comment]
I fixed this bug.
Please check the pull request #233

**Comment by butaixianran** [comment]
check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
