### ISSUE TITLE
FR(s): Local Star Rating, local description caching (and pop up), local notes/prompts/tags/config.

### ISSUE THREAD

**Issue by midcoastal** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#131]
A few feature requests, if a comment comes in to spit them, I'll go ahead and do that.

Local Star Rating: it would be great if we could set star ratings for checkpoints/loras/hypernets/etc. Some are good, some suck, but some of us are hoarders. ;-)

Local Description Caching with pop-up: I may actually be blind, or dumb, but it would be great to have a model's information cached locally, and displayed as a pop up as opposed to opening Civitai. 

Multiple Preview Images/Examples: it the addition to the local description pop up, it would be great if we could attach multiple preview images/prompts as well. This would help me understand the capabilities of my collection better.

Local Notes: also in addition to the description, it would be great to be able to add my own notes, that wont update woth the remote description. Maybe redundant and just don't pull new descriptions if there already is one.

Local Default Config: it would be great to be able to set things like the default weight for when included. As well as tags. Either at the global level, or, in addition to allowing multiple preview images, per preview images (so we could collect examples of what different activations do).

Model Hiding: I have a LOT of models. It would be helpful to be able to tag them (not a prompt tag, but a category tag), and hide models with a tag. Maybe this is out of scope of this plugin, maybe this could be done at the WebUI level by hiding subdirectories or something, but wheras I like to organize some of my models by author, that wouldn't work. It would be awesome to be able to hide deprecated models, while still having them available.

With all of the above, we could lock editing according to the enable-unsafe-extensions, or lock settings flags.

With regards to hiding; it would be good to be able to have models show up for a particular user.

I guess for both, looking for a specific flag in the session/cookies would do the trick, as I am looking to implement a User plug-in at some point (out of scope for this topic).

**Comment by butaixianran** [comment]
2.0 feature

**Comment by midcoastal** [comment]
Oh!  That's cool to hear!

Like, all the ideas?  Or a specific one?  Glad to hear there IS a 2.0 coming.  Any idea times on that?  Not asking to rush, just wondering if there is any idea.
