### ISSUE TITLE
 Feature Request - Download Model - Model Version section autoupdate

### ISSUE THREAD

**Issue by BoyNG** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#132]
## Describe Issue

I "Download Model" section, After clicking "Get model info", in the field - "Model Version" remains filled from the previous model.
It should be filled with the version of the new model, if it is only one, or the field should be cleared if there are several versions.

Also LORA model with tag - LyCORIS better download in LyCORIS dir!

**Comment by butaixianran** [comment]
Due to gradio's bad design, it won't be done
