### ISSUE TITLE
有些lora名字太长会盖住卡片按钮，盖住的部分不能点

### ISSUE THREAD

**Issue by pimin12** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#136]
希望能优化一下

**Comment by butaixianran** [comment]
小图模式，请去sd webui官方项目提建议让他们把图片尺寸改大。

**Comment by LoveLand168** [comment]
> 

能否将按钮的层级放到最上层，sdui的默认主题太难用了，chicken的界面更人性化一些，会成为主流的

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
