### ISSUE TITLE
Large thumbnail images

### ISSUE THREAD

**Issue by Kaneda56** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#137]
Since the last webui update my thumbnail images of Civitai helper are very big
![Capturecivitai](https://user-images.githubusercontent.com/12573241/236417027-b0716761-9234-444f-83a5-16cba561cb20.PNG)
python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89)  •  checkpoint: [e6415c4892]

**Comment by butaixianran** [comment]
I won't waste time on this question. You need to learn how to use sd webui. There is nothing to do with this extension.
