### ISSUE TITLE
Feature Request: Icon to show new model versions are available

### ISSUE THREAD

**Issue by Aelobin** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#14]
Hey, great extension!

Would it be possible to add a button to the Civitai Helper page to "Scan for model updates"? It would check each model page to see if there is a newer version than the current model hash, and if so it shows a notification icon on that model in the Extra Networks list.

This would make it so much easier to check which of your models have new versions available to download.

Thanks

**Comment by butaixianran** [comment]
It is already in the todo list, but not with a high priority.

**Comment by butaixianran** [comment]
Get a way to check model's new versions, update your version.

Not the way you asked, but a way works better as a limited extension.

**Comment by Aelobin** [comment]
That's amazing, thanks so much!

The only issue I've found is that some of my VAE files are ".vae.ckpt" or ".vae.pt" and the extension thinks they are checkpoint models

**Comment by butaixianran** [comment]
why your vae is in a model's folder? vae has its own folder, which won't be scanned

**Comment by Aelobin** [comment]
Unless I'm mistaken, when you have a vae in the same folder as a model (with the same name) then A1111 will use that vae instead of the one you've set as default, which means you don't need to keep changing the settings when you load some models.

**Comment by butaixianran** [comment]
OK, you know, in SD webui, you can put the vae drop down list from setting page to the top toolbar, like the model drop down list.
![Snipaste_2023-03-11_11-51-14](https://user-images.githubusercontent.com/5558722/224463426-e75e9018-84d6-47a3-9dcb-df2360fa0989.jpg)

Just put "sd_vae" to this setting textbox in your setting page:
![Snipaste_2023-03-11_11-50-17](https://user-images.githubusercontent.com/5558722/224463456-bd4b68dd-9df3-4205-98a2-8c34c2d16bae.jpg)


So, when you pick a model, you can pick a vae for it at the same toolbar, without going to setting page.

With this way, you don't need to lock a model to a vae, you can swtich vae very easliy for the same model in different cases.

**Comment by butaixianran** [comment]
Add a quick fix for this, update new version. No version number changed though.

**Comment by Aelobin** [comment]
Oh nice, I didn't know this :D Thanks for the tip!

Previously I was using symlinks to the vae folder so I didn't need to remember which vae I need for each model (when the uploader recommends one in the civitai description) but I guess I can just try each of them with that menu to see what works :)

**Comment by butaixianran** [comment]
Remove your vae's model info file. Update to latest version. vae will be ignored when scanning.
