### ISSUE TITLE
Download improvements

### ISSUE THREAD

**Issue by cooperdk** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#140]
What the script needs to do when updating a model:

 1) register the download with a dummy file, fx <model name>.civitai - in this file refer to the ID of the file
2) REMOVE the old version and it's info and preview files (THIS IS NOT DONE AUTOMATICALLY NOW - these are big files and there's no reason to do this manually)
3) download the new model and info/previews (this is done now)
4) remove the download check

What the script needs to do when checking for updates (or entering the CivitAI helper tab):

1) Check for any dummy files, if existing .civitai files are present
2) Download these after the user is prompted to do so

**Comment by halr9000** [comment]
Also the way update checks happen is super slow. I can think of some ways to improve that. 

1. Run a local process to check the hashes of all installed models (or trust the hash in the .info). 
2. Batch these up in a single API call to the website.
3. Have that call return the info of each that match, with some optimizations like pagination, only return outdated, etc.
4. Present the findings to the user with a bunch of checkboxes in a table. Select all/none would be nice, and a "download all" button. 
5. see ^ above

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
