### ISSUE TITLE
Feature suggestion: Download Queue

### ISSUE THREAD

**Issue by Isaiahfeldt** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#143]
Who has time to wait around for a 3GB model to download before copying pasting over the next url only to wait again for next 4GB model to finish downloading, and so on and so forth 

It would be nice if there was a queue that I could just dump some urls in and civitai helper could download them in sequence, with any necessary rate limiting of course

**Comment by butaixianran** [comment]
Won't do it, you can use professional downloading tools for queue

**Comment by Isaiahfeldt** [comment]
It’s alright, turned out that the new official Civitiai extension has this feature. Thanks for your time
