### ISSUE TITLE
reading custom lora pathes and saving everything in respective source pathes too

### ISSUE THREAD

**Issue by JaysonPhoenix** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#145]
## Have you read document?
+
## Have you checked console log window's msg?
+
## Describe Issue
isnt this tool suppposed to not only read custom checkpoint folders and subfolders but also cutstom lora folders? because it doesnt for me and that would actually be more important than for the checkpoints because of all the triggerwords and thumbnails and linking to civitai for readmes and so on. 
also when working with custom folders it should save thumbnail and model info and even the updates in the location where the original lora/checkpoint/whatever is found instead of in the automatic1111 folders. this tool should prevent me from copy and paste stuff back and forth as much as possible, 
so while automatic1111 doesnt support custom hypernetwork and embedding folders (as far as i know) it does support custom lora folders via the additional network settings which this tool should support aswell then (guess to fetch the lora path from there shouldnt be a big deal if it doesnt already and its only bugging on my side) and put everything downloaded/saved where it finds the sources so it doesnt get messy and the user doesnt have to manually move stuff around anymore.

in my case i have a db folder with checkpoint sub folder and each checkpoint has its subfolder in there, same for loras (and for hypernetworks and embeddings too, but since automatic doesnt support custom pathes for thos i still have to copy those em to the program folders). which is good to keep everything tidy and clean and have other ai tools access that same database instead of wasting harddrive space by cloning for each program. the helper tool should then be able to access such dbs and save in such dbs and not mess everything up by not saving in the same db, hope thats understandable ^^

**Comment by butaixianran** [comment]
sd webui has command arguement which can set custom model folder.

**Comment by butaixianran** [comment]
If you don't know a command argument you can find it on sd web ui's wiki page or search it with google. 

Lora's argument command is there.

**Comment by JaysonPhoenix** [comment]
awsome, thank you! that completely solved both issues. right arguments are --lora-dir --embeddings-dir --hypernetwork-dir found on https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings in the wiki. 
to my defense google didnt find that page when i used several custom lora path keywords and always only came up with forum entries and vids talking about loras in general or at best about the additional networks lora path settings, and im pretty sure i looked up that wiki before at some point and didnt find the whole command line arguments section ^^ but this time when you said its in the wiki i went there and found it in an instant, 
so thank you again and maybe civitai helpers main page should mention manually setting up those pathes during installation or something for dumb guys like me ^^
