### ISSUE TITLE
[功能建议]通过文件夹前缀来屏蔽插件的检索

### ISSUE THREAD

**Issue by Policturn** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#147]
希望能增加一个通过为模型文件夹添加某一前缀来让使用在c站搜索对应模型的时候略过这个文件夹
主要用途是在自己合成的模型上,每次检索后会给自己合成的模型添加一个civitai文件但那个文件本质上又没有用途,如果能通过手动设置让文件夹被忽略掉就好了

**Comment by butaixianran** [comment]
等2.0
