### ISSUE TITLE
[建议]关于read me文档中代理的使用说明最好强化一下

### ISSUE THREAD

**Issue by FCJ1987** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#150]
安装之前看了文档，关于代理那里扫了一眼，想着自己挂了代理的就确实没有太仔细看。使用时发现扫描报错，控制台显示timeout，所以是C站连不上去。返回去再看了几遍文档还是没看出端倪。后来是在其他人的报错帖子里看到楼主的回复https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/133#issuecomment-1528822197
才知道网页能翻墙不代表SD调用的Python能翻墙，必须在C站助手工具栏的代理信息里填入端口信息才行。外行玩家对代理认识比较肤浅，不知道必须在软件内输端口信息，还以为只要有梯子能翻墙上网就行了。
另外再问下civitai helper2-model info的开发计划怎么样，什么时候能正式发布呢，好期待啊。

**Comment by butaixianran** [comment]
文档里面是有提到要填写代理的，还有格式说明。

2.0已经有文档专门提到进展了。
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/about_version2.md
