### ISSUE TITLE
助手不支持C站LYCORIS模型更新吗

### ISSUE THREAD

**Issue by chen135347542093** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#151]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/104272971/d3c55a7f-f77b-4a5c-b84f-3417510f459a)
也不能扫描模型下载预览图

**Comment by chen135347542093** [comment]
> 不支持

以后会支持吗

**Comment by butaixianran** [comment]
there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
