### ISSUE TITLE
[功能建议] 2.0中能否增加预览图的数量

### ISSUE THREAD

**Issue by FCJ1987** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#152]
目前预览图只能加载一张，看2.0版的model info增加了很多自定义的描述信息，不知道能不能给模型增加一个查看多张预览图的功能，点击之后除了默认的预览图之外，还能以这个模型生成的图片作为更多的预览详情，格式就按模型同名文件名的XXXpreview01.PNG、XXXpreview02.PNG...这样子

**Comment by butaixianran** [comment]
It will be in another project and another repo, won't talk it here.
