### ISSUE TITLE
Notice: this extension has been added to the extension index

### ISSUE THREAD

**Issue by w-e-w** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#153]
hello @butaixianran I'm one of the maintainers of the [sd webui extension index](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
I wish to inform you that I have added your extension to the extension index with the following description

if you do not wish your extension to be added to the index or think that the description is inappropriate
please make a pull request to amend this
```json
"name": "Stable Diffusion Webui Civitai Helper",
"url": "https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git",
"description": "Download or populate models with metadata and preview image from civitai.com",
"added": "2023-05-16",
"tags": ["tab", "UI related", "online"]
```
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/57

**Comment by butaixianran** [comment]
thanks for your information. it's ok to me

**Comment by w-e-w** [comment]
I forgot to mention, if you add self-advertisement in the future, please add the tag `ad`
