### ISSUE TITLE
Feature suggestion: Rename models

### ISSUE THREAD

**Issue by LLKoder** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#155]
I suggest to do feature rename model with download model. If model to keep with original name sooner or later it make any mess.

**Comment by LLKoder** [comment]
What I mean is to add a section in extension with a field or fields where users can specify how the model will be called. The field will be able to contain from the original name by default.

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
