### ISSUE TITLE
Bug: The model scan

### ISSUE THREAD

**Issue by LLKoder** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#156]
If I download [this](https://civitai.com/models/26344/tahlia-hall) model with Civitai-Helper - all ok.
But if I download by myself and then scan with Civitai-Helper it shows me problems. I see wrong preview, tags and etc.

**Comment by butaixianran** [comment]
some models of civitai are saved with a wrong hash code in civitai's database.

it's a bug of civitai, not this extension.

civitai has a discord pose which you can report this kind of models:

https://discord.com/channels/1037799583784370196/1096271712959615100/1096271712959615100

**Comment by LLKoder** [comment]
Thanks for info...
