### ISSUE TITLE
this plug-in cannot be applied to the chicken theme.QAQ

### ISSUE THREAD

**Issue by LoveLand168** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#157]
Thanks for your hard work, this plug-in cannot be applied to the chicken theme, hope you can update this suggestion in the v2 version, hope to support the preview of all models.!Four buttons missing
![微信截图_20230516144741](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/133742829/64f86ca3-73a2-49ce-b39a-7abdcb4d1c10)

**Comment by butaixianran** [comment]
won't support it

**Comment by LoveLand168** [comment]
好吧
