### ISSUE TITLE
icon buttons not appearing for LyCORIS models

### ISSUE THREAD

**Issue by Connum** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#158]
## Have you read document?
yes 

## Have you checked console log window's msg?
yes

## Describe Issue
With support of additonal model types installed, e.g. LyCORIS (https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git), the icon overlays do not work for those tabs, even after clicking the blue refresh button. After clicking the button, the console logs `found active tab: lycoris`, but the icons do not appear. All tabs should be working, or there should be a way to add additional paths/model types.

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/13076806/830e491d-76bc-411d-919b-3cb14e168af7)
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/13076806/cddf612e-c29a-48e9-b20f-1e87e6a7b6f9)

**Comment by shtrih** [comment]
It's not about any other 3rd party extension at all. It's about model format on civit and folders on ssd. Your extension works with files and folders and civit models. What uses those folder or files is not matter for your extension. Your extension is not affect otherr extensions since it just creates info files. And lycoris extension is not affect your extension since it just reads list of models. So what's the reason to refuse in `lycoris` branch merge? I really don't understand your position. 
@butaixianran

**Comment by Connum** [comment]
See #107, #119, #179, #190, but sure, keep insisting on not implementing this simple thing that shouldn't break anything for anyone not using the LyCoris extension...

For anyone wanting to fix this temporarily and not wanting to abandon this extension in favour of a fork:

1. in _extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py_

Look for `model_type_dict = {` and add ` "LyCORIS": "lora",` to it after `"LoCon": "lora",`
to enable scanning of preview images and data for the LyCORIS folder.

2. in _extensions\Stable-Diffusion-Webui-Civitai-Helper\javascript\civitai_helper.js_

Look for `switch (active_extra_tab) {` and add another case
```python
case "lycoris":
  active_extra_tab_type = "lycoris";
  break;
```

Look for `switch (js_model_type) {` and add another case
```python
case "lycoris":
  model_type = "lycoris";
  break;
```

That's it, that's all the fuzz.

**Comment by butaixianran** [comment]
this is supported in another fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
