### ISSUE TITLE
在某一lora模型上civitai-helper失效

### ISSUE THREAD

**Issue by evergreenqingyu** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#159]
## Have you read document?
是的
## Have you checked console log window's msg?
是的
## Describe Issue
在使用某一lora模型时，civitai助手失效，虽然显示了全部的按键，但除了替换封面无论点什么都是调用lora，添加lora到prompt，尝试过用别的模型info文件强制替换，尝试过删除模型再使用civitai助手内置lora下载，都无法解决问题，控制台也一切正常。目前只发现这一个lora有这样的问题。
这是lora的地址，https://civitai.com/models/60728/girls-frontline-ltlx7000   但我不清楚这是否是我个人的问题，非常感谢。
## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/82428916/e0afe798-57bd-41ae-a53d-7b2089cb165e)
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/82428916/003907e0-1e2f-42f1-a9c6-6cbb0e94f598)
## Console log's msg or screenshot for function issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/82428916/c8b6d00d-ab13-41e9-bf79-8c52ec422e00)

**Comment by butaixianran** [comment]
hi, 这是因为这个模型名称里面有个单引号。引号是程序中用来定义字符串的字符。如果模型名称中包含了引号，那么模型名称中，引号后面的内容，就不会被认为是模型名称而导致程序出错。

这个引号不但导致本扩展失效，并且导致sd webui一些内置功能，也无法用于这个模型。

解决办法也很简单，把Girls后面的单引号从模型相关的几个文件名上去掉，就正常了。

包括：模型文件，.civitai.info文件，预览图文件。

改名后一切恢复正常。

由于本扩展需要依赖sd webui内置的extra network，于是这个问题无法通过修改本扩展得到解决，只能修改模型名称解决。

**Comment by evergreenqingyu** [comment]
非常感谢大佬百忙之中回答我的问题，谢谢大佬！
