### ISSUE TITLE
open model page from current browers instead of browser on remove server.

### ISSUE THREAD

**Issue by kasimok** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#16]
I'm remote accessing webui, the plugin works but the pages opens on the host machine's browser instead of the current browser. Thinking it will be better to open at current browser.

**Comment by butaixianran** [comment]
I'll see what I can do, due do the limitation of gradio, this may not be done.

**Comment by MrKuenning** [comment]
I also access mine remotely, I think a simple solution could be to have the button copy the URL into the clipboard.
