### ISSUE TITLE
[Bug] Extension download more than one model file the same version

### ISSUE THREAD

**Issue by LLKoder** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#160]
Then I download this [model](https://civitai.com/models/2220/babes) the extention download 4 files of this version (~15gb) instead 1 file. Why? It's bug.

I think author of #142 meant the same situation.

I know Interface of CivitAI very specific and many users type `version of model` in tag (v1, v2, v3 VAE and etc) and each version have `type of vesion`. Also in the type of version put files in (fp16, fp32, SafeTensor, PickleTensor and etc). IMHO there is logic in it.

There is no way to correctly download the model files in the extension for now.

```
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:Babes
Civitai Helper: model_type:ckp
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['Babes 2.0_61372', 'Babes 1.1_21216', 'Babes 1.1 no vae_2411', 'Babes 1.1 clip fixed_10709', 'Babes 1.1 experiment 9_20609', 'Babes 1.1 experiment 8_8828', 'Babes 1.1 experiment 7_8254']
Civitai Helper: Searching local model by version id
Civitai Helper: folder: ...stable-diffusion-webui\models\Stable-diffusion\
Civitai Helper: version_id: 61372
Civitai Helper: This model version is already existed
Civitai Helper: Searching local model by version id
Civitai Helper: folder: ...stable-diffusion-webui\models\Stable-diffusion\
Civitai Helper: version_id: 61372
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/61372?type=Model&format=PickleTensor&size=pruned&fp=fp16
Civitai Helper: File size: 2132865129
Civitai Helper: Target file path: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.ckpt
Civitai Helper: Downloading to temp file: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.downloading
Civitai Helper: Downloaded size: 0
[--------------------------------------------------] 100%
Civitai Helper: File Downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.ckpt
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/61372
Civitai Helper: File size: 2132625468
Civitai Helper: Target file path: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.safetensors
Civitai Helper: Downloading to temp file: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.downloading
Civitai Helper: Downloaded size: 0
[--------------------------------------------------] 100%
Civitai Helper: File Downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.safetensors
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/61372?type=Model&format=PickleTensor&size=full&fp=fp16
Civitai Helper: File size: 4244331592
Civitai Helper: Target file path: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.ckpt
Civitai Helper: Target file already exist.
Civitai Helper: Downloading to temp file: ...stable-diffusion-webui\models\Stable-diffusion\babes_20_2.downloading
Civitai Helper: Downloaded size: 0
[--------------------------------------------------] 100%
Civitai Helper: File Downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20_2.ckpt
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/61372?type=Model&format=SafeTensor&size=full&fp=fp16
Civitai Helper: File size: 4244098750
Civitai Helper: Target file path: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.safetensors
Civitai Helper: Target file already exist.
Civitai Helper: Downloading to temp file: ...stable-diffusion-webui\models\Stable-diffusion\babes_20_2.downloading
Civitai Helper: Downloaded size: 0
[--------------------------------------------------] 100%
Civitai Helper: File Downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20_2.safetensors
Civitai Helper: Request version info from civitai
Civitai Helper: Write model info to file: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.civitai.info
Civitai Helper: Checking preview image for model: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.safetensors
Civitai Helper: This image is NSFW
Civitai Helper: Downloading file from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/16a0f4ac-2b5d-469d-8265-8d85324cbb2b/width=1328/807240.jpeg
Civitai Helper: File downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.preview.png
Civitai Helper: Done. Model downloaded to: ...stable-diffusion-webui\models\Stable-diffusion\babes_20.safetensors

```

**Comment by LLKoder** [comment]
![2023-05-18_16-06](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/50442676/6e3fdd89-fdbf-4989-adc6-ca7907229f76)

**Comment by butaixianran** [comment]
It's not a bug, it's a feature which is request from other users. 

In your case, model creator should not upload multiple models into 1 version's file list. That's a very bad behavior. 

If you still want to this extension only download just 1 file, you can download this extension's version 1.6.1.1 from civitai:
https://civitai.com/models/16768/civitai-helper-sd-webui-civitai-extension

**Comment by butaixianran** [comment]
Added a new checkbox "Download All files" for downloading model section. Uncheck means only download 1 file.

Check latest version 1.6.4 for this new feature.

**Comment by LLKoder** [comment]
> It's not a bug, it's a feature which is requested by other users.
> In your case, model creator should not upload multiple models into 1 version's file list. That's a very bad behavior. You can ask that model's creator upload them as different versions to civitai.

Can you say to CivitAI they realize bad feature? :)
Can I send a message to every authors who have upload more than 1 files and say "That's a very bad behavior.". :) I'm interesting how many messages I will have to send? And more important how many time I will waste to send messages? It's like more strange side... Don't you think so? :)

> If you still want this extension only download just 1 file, you can download this extension's version 1.6.1.1 from civitai: https://civitai.com/models/16768/civitai-helper-sd-webui-civitai-extension

It doesn't suit me, I want to use the latest version of every app I have, just like all other users.

> Added a new checkbox "Download All files" for downloading model section. Uncheck means only download 1 file.
> Check latest version 1.6.4 for this new feature.

Thanks. :) But one question what will file download if I have more than one? Last? First? Random?
IMHO, it would be nice to have choice from each files or "Download All files" in future versions.
For example, this feature not very good realized in this [extension](https://github.com/Vetchems/sd-civitai-browser), at least users have choice between SafeTensor or PickleTensor model.

**Comment by butaixianran** [comment]
well, you can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
