### ISSUE TITLE
clicked on the "refresh civitai helper" without any response, and I couldn't see the four buttons either

### ISSUE THREAD

**Issue by baifagg** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#161]
## Have you read document?
yes
## Have you checked console log window's msg?
Console has no information
## Describe Issue
clicked on the "refresh civitai helper" without any response, and I couldn't see the four buttons either
## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/51266591/9c85503b-9964-4560-9a20-760bb251e960)
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/51266591/4f1ec873-2550-4624-81ab-dc14dda4709d)
## Console log's msg or screenshot for function issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/51266591/65390d8b-6193-4da5-a6e6-450c374a3836)

**Comment by butaixianran** [comment]
不支持kitchen

**Comment by baifagg** [comment]
> 不支持kitchen
> 
> kitchen is not supported

好的 谢谢了

**Comment by goldmojo** [comment]
Last version of kitchen fixes this issue

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
