### ISSUE TITLE
"subfolder string is None"

### ISSUE THREAD

**Issue by VitaliyAT** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#162]
Try download model but got this message after step 3 button push

**Comment by butaixianran** [comment]
Pick a subfolder from the subfolder list before clicking download button

**Comment by speaknowpotato** [comment]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/59820713/8d6a63c2-8137-4c4a-a195-61a9f9933c6c)
Still not working @butaixianran

**Comment by d3fc0n2008** [comment]
When I click the Sub folder button there is nothing.  There are no sub folders that appear and nothing to choose from.  Its completely blank.  I have a Lora model I want to try to download directly from Civitai but when I click on the model and then choose Download I get the following:  "Civitai Helper: subfolder string is None"
I get that it can't be blank -- I don't have an option to choose a sub folder --clicking on the sub folder button does not give me anything.  Its blank.  How do I fix this?

**Comment by feldsher-mv** [comment]
When you click the Sub folder button there is not empty, there is slash ( / ) . Choose it.

**Comment by butaixianran** [comment]
It is decided by gradio. I can do nothing about this. 

But, you can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
