### ISSUE TITLE
The four buttons have disappeared

### ISSUE THREAD

**Issue by hirtelen** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#163]
The four buttons have disappeared from Civitai Helper. No matter what I do, they don't come out of any of the models. Not from any browser.

**Comment by butaixianran** [comment]
()[https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/img/refresh_ch.jpg]

**Comment by albamuth** [comment]
I seeing the 4 buttons for LORA's that did not load an image due to being NSFW or missing image

**Comment by BaseMe2** [comment]
The button don't appear in img2img, text2img works fine.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
