### ISSUE TITLE
Not working because of --data-dir ?

### ISSUE THREAD

**Issue by jangrewe** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#164]
## Have you read document?
yes

## Have you checked console log window's msg?
yes

## Describe Issue
I have the a model from Civitai that is not recognized when scanning. A separate embedding is recognized and metadata etc. is added.

I'm using `--data-dir ./data`, so the model is in `data/models/Stable-diffusion` and the embedding is in `data/embeddings`.

Even when providing the URL for the model, your extension says `failed to get model file path`.

When downloading the model through your extension, it gets downloaded to `models/Stable-diffusion`, so i'm suspecting that your extension does not honor the `--data-dir` argument?

**Comment by butaixianran** [comment]
data-dir is not supported

**Comment by jangrewe** [comment]
Could you please add support for this? It makes separating the software from the data so much easier, and i guess all you need to do is check the currently running configuration if there is a different data-dir being used, and then look inside that path... it's basically "just adding a path prefix", as the data-dir has to be inside the stable-diffusion-webui directory.

**Comment by butaixianran** [comment]
data-dir is a bad command argument no one should use, I have explained this in many issues. It is full of trouble and won't be supported

**Comment by jangrewe** [comment]
I looked at existing issues, but i don't find you explain why this is bad anywhere in those? I personally think this is a very useful argument, as it allows me to mount all models, extensions, etc. into a Docker container, without having to mount every directory individually and without loosing the models that are already baked into the container.

**Comment by robbiep** [comment]
Due to not support custom dirs, as is the extension is not useable in my company's internal docker configuration, which is something we'd like.

**Comment by butaixianran** [comment]
won't support --data-dir

You can ask this in a new repo
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
