### ISSUE TITLE
Connect to Civitai API service failed. Wait a while and try again, check console log for detail

### ISSUE THREAD

**Issue by rancherito** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#166]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
Lora error download info

## Console log's msg or screenshot for function issue
Civitai Helper: Creating model info for: lux_v1.safetensors
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: 3cbadfc2010a8e8dcc7335593f8c669becd6c564d36dc447930de4c04b296f63
Civitai Helper: length: 75615886
Civitai Helper: Request model info from civitai
Civitai Helper: Get error code: 403
...

**Comment by butaixianran** [comment]
error code 403 means your internet connection can not connect to civitai's API service.
