### ISSUE TITLE
Scanning done but loss preview image

### ISSUE THREAD

**Issue by xbahenrytam** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#167]
sometime the scanning is over, but there are still no preview images, I have to add it by myself.
Can the "Get Model Info from Civitai by URL
Use this when scanning cannot find a local model on civitai" in Civitai Helper page only shows that ones don't have preview images?

**Comment by butaixianran** [comment]
if a model is on civitai, scanning should be able to get the preview image.

If not, make sure you have NOT checked "skip NSFW images" option for scanning.

A picture you think is safe for work, is not what civitai thought.

For a model which is not on civitai, extension will just create an empty model info file. 

In this case, you can use "Get model info by url" function to get the model info and preview.

Check "only show models have no info file" will get a model list only with empty info file.

**Comment by xbahenrytam** [comment]
I'm sure "skip NSFW images" is NOT checked, sometimes it really cannot scan images. But it's seldom occurred.
And I check those models have no info file, they do have preview images, but cannot open the URLs, I guess it's because some of the original posts on civitai have been deleted. 

Thanks for your reply.

**Comment by 1613283929** [comment]
是的，我也遇到了同样的问题，并且在试图解决这些问题的时候遇到了一些像我一样的人，他们目前都还未解决

**Comment by butaixianran** [comment]
If there is no info file, then this model is not on civitai. Also, even a model is not on civitai, after scanning, it will create an empty info file. So it won't scan that model again. If there is no info file at all, that means there is something wrong when scanning. You may need to scan again and check the console log window to find out what's really going on there.
