### ISSUE TITLE
"Open this model's ciivitai url" function

### ISSUE THREAD

**Issue by xbahenrytam** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#168]
If I change the folder name where the models are inside, the function is fail.
For example:
The original folder name is "costume", when I change it to "Costume&Appearance", the following error message occur.
But when I change back to "costume", the function works again. So, if I want to change the folder name or move to another folder, how should I do?

Civitai Helper: Load model info of /Costume&amp;Appearance/BaltimoreraceV1.safetensors in lora
Civitai Helper: Can not find model info file: D:\AI\stable-diffusion-
webui\models\Lora\Costume&amp;Appearance/BaltimoreraceV1.civitai.info
Civitai Helper: Failed to get model info for lora /Costume&amp;Appearance/BaltimoreraceV1.safetensors
Civitai Helper: Start open_model_url
Civitai Helper: Start parse js msg
Civitai Helper: End parse js msg

**Comment by butaixianran** [comment]
have you refreshed your model list with extra network's "Refresh" button?

have you tried not use a character like "&"?

**Comment by xbahenrytam** [comment]
Find the problem, a special character may cause this issue. Thx

**Comment by butaixianran** [comment]
This extension is based on sd webui's extra network, so there are a lot of limitation in many ways. So it can not be done.
