### ISSUE TITLE
Feature Request: Pull model description into Info file (or external text file)

### ISSUE THREAD

**Issue by oncoremarco** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#169]
Hello. I have found that many models include special information in their descriptions, such as instructions or guides for usage, that are not pulled by the program. While this information is displayed on the web page, should a model be removed from Civitai, these instructions will be lost. Therefore, I'd like to propose that this information be pulled by the extension into the .info file upon creation.

As an example of the issue:
https://civitai.com/models/68863/angewomon-digimon-realisticanime

The above model includes in the description a suggestion that certain tags be applied to improve the accuracy of the model. Without going to the web page, there is no way to uncover this information, and should the model be pulled from the webpage, there will be no way to retrieve it, rendering the model largely unusable. 

In the past I've manually created a .txt file containing this information in the Model's folder, but if the extension could do that itself, it would be indispensable.

**Comment by butaixianran** [comment]
wait for 2.0
