### ISSUE TITLE
Icons Cover up thumb view.

### ISSUE THREAD

**Issue by MrKuenning** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#17]
I have about 500 LoRAs, when I view them in thumb view the icons seem to always be on and almost completely cover the image.
Is there any way to make them only appear when you mouse over an image?  Or a button to toggle the icons on and off.

I also think maybe the thumbnail view could just have two icons, Replace image, and Insert Keywords.  There really isn't a need to have the URL icon on the thumb view.

Extension Enabled
![2023-03-07 13_03_37-Stable Diffusion](https://user-images.githubusercontent.com/16549268/223563903-12ded8de-d266-44c0-9d29-403acdd77037.jpg)
Disabled
![2023-03-07 13_05_15-Stable Diffusion](https://user-images.githubusercontent.com/16549268/223564143-f2c613b6-6c46-4b86-b81d-d8a791ea3d33.jpg)

**Comment by butaixianran** [comment]
hi, this extension can not work with thumbnail mode. The image is too small to work with 4 buttons.

I may find a way to remove them all when using thumbnail mode.

**Comment by MrKuenning** [comment]
Yeah, I keep the thumbnail/card drop-down on the top of the page, as I have to toggle between them depending on which computer I am accessing it from.


![2023-03-07 13_44_50-Stable Diffusion](https://user-images.githubusercontent.com/16549268/223571144-ccef1a13-28e6-4f10-8d81-3218bdef933d.jpg)

I would still like to have a button on thumb mode to insert the LoRA with the optimal weight and keywords from the info file.

I don't need to see the URL and current image prompt buttons.

But if we could specify the most optimal weight value and prompt keywords in the civitai.info file, it would be useful to have a single button in thumb mode to insert that into the prompt.

**Comment by scrumpyman** [comment]
I don't why you can't make it work, just have the icons slightly smaller and have all of them appear on hover at the top.

**Comment by butaixianran** [comment]
Additional buttons are removed when using thumbnail mode. Consider it's done.

If you really need this so badly, you should go to SD webui's project, ask them to make the thumbnail bigger.

**Comment by butaixianran** [comment]
This will be handled in 2.0, close it for now.

**Comment by butaixianran** [comment]
It is more important than I thought, need to handle this in 1.x, so reopen this issue.

**Comment by butaixianran** [comment]
![Snipaste_2023-03-11_19-03-26](https://user-images.githubusercontent.com/5558722/224480663-81ee5c4e-471c-49df-9e1c-f401ab42a5cc.jpg)

Finished in my local repo. Since SD webui has a bad design on this thumbnail's hover css, this is the best an extension can achieve. Better css requests to modify SD Webui's build in css file, which can not be done in this extension.

**Comment by GZ1A** [comment]
> ![Snipaste_2023-03-11_19-03-26](https://user-images.githubusercontent.com/5558722/224480663-81ee5c4e-471c-49df-9e1c-f401ab42a5cc.jpg)
> 
> Finished in my local repo. Since SD webui has a bad design on this thumbnail's hover css, this is the best an extension can achieve. Better css requests to modify SD Webui's build in css file, which can not be done in this extension.

I am extremely grateful for this update as I have 200+ Lora and had to use thumbnail mode. It has made a significant difference. Thank you.

**Comment by butaixianran** [comment]
Done, check update., Re-launch SD after updating, just Reload UI won't work.
