### ISSUE TITLE
为什么模型上四个按钮有的是一行，有的是两行？

### ISSUE THREAD

**Issue by greatjusticelight** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#170]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/134216265/26ef45b0-8ebb-4ffb-9c62-4b4c1e3c7d53)
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/134216265/5cc64ee5-2aa3-49d1-822c-249081f4e7ed)
有些名字长的模型已经挡住按钮了（主要是强迫症忍不了）
求解

**Comment by butaixianran** [comment]
因为有的模型，右上角有个sd webui内置的按钮，鼠标移动上去就会显示。为了按钮不互相覆盖，这种情况就会换行。

**Comment by greatjusticelight** [comment]
你说的那个按钮是第二张图的那个圆圈叹号吗？这种情况有解决办法吗？

**Comment by greatjusticelight** [comment]
你说的那个按钮是第二张图的那个圆圈叹号吗？这种情况有解决办法吗？

**Comment by butaixianran** [comment]
没办法解决，那是sd web ui官方的稀烂设计，这边只能配合
