### ISSUE TITLE
关于更新模型时提示“远程主机强迫关闭了一个现有的连接”等等因为网络波动导致失败得优化建议

### ISSUE THREAD

**Issue by NaughtDZ** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#175]
首先，我想很多人手头得lora都是几十几百的。但是每次更新只要失败，再点更新又得从头开始。就此，我建议每次更新，把已扫描的模型文件名写入一个log文件，在比如12小时这样的冷却期内，这个文件不会再次扫描。
其次，经常是扫到一大半就因为波动一下下就直接提示失败，未免太过激进。应当提供一个选项入口，比如远程主机强迫关闭了一个现有的连接，这种情况，可以主动等待60秒后在多次发起连接尝试。而不是抛出一个错误，就逼着用户从头点击更新，从头扫描。

**Comment by Array-Cats** [comment]
本人认为作者会在目前版本内加入类似功能的概率并不大，所以建议对模组用小文件夹进行分类管理，然后更新的时候一次只更新一个小文件夹内的模型（其余的移动到别处）

**Comment by butaixianran** [comment]
1.x不打算处理这种问题了，找个稳定的代理吧。会好很多
