### ISSUE TITLE
All models downloaded with extension can't be loaded

### ISSUE THREAD

**Issue by Golgovskiy** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#176]
Using in-interface downloading from url, models are downloaded, but webui can't load them.

```
Traceback (most recent call last):
  File "D:\Repositories\Python\stable-diffusion-webui\modules\shared.py", line 516, in set
    self.data_labels[key].onchange()
  File "D:\Repositories\Python\stable-diffusion-webui\modules\call_queue.py", line 15, in f
    res = func(*args, **kwargs)
  File "D:\Repositories\Python\stable-diffusion-webui\webui.py", line 199, in <lambda>
    shared.opts.onchange("sd_model_checkpoint", wrap_queued_call(lambda: modules.sd_models.reload_model_weights()), call=False)
  File "D:\Repositories\Python\stable-diffusion-webui\modules\sd_models.py", line 533, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "D:\Repositories\Python\stable-diffusion-webui\modules\sd_models.py", line 273, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "D:\Repositories\Python\stable-diffusion-webui\modules\sd_models.py", line 252, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "D:\Repositories\Python\stable-diffusion-webui\venv\lib\site-packages\safetensors\torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```
I saw other people having this problem, but they blame safetensors. However, i have identified that only models loaded from the extension recently fail to load for me.
I have confirmed the wrong hash number on all of them.

**Comment by ancker010** [comment]
Confirm. Same issue and same cause.
Download with extension, error above.
Download from website, works fine.

**Comment by drimeF0** [comment]
same problem

**Comment by Golgovskiy** [comment]
Issue had disappeared for me, although i can't see any commits about it. Weird.

**Comment by woaiseeit** [comment]
Please reopen. This issue still exists. It happens when the download fails and the resulting file is incomplete.

Notice the file size expected for the download: `2132625894`
```
Civitai Helper: Getting model info by: https://civitai.com/models/4201/realistic-vision-v51
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai
Civitai Helper: Get subfolder for: /home/woaiseeit/Projects/stable-diffusion-webui/models/Stable-diffusion
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:Realistic Vision V5.1
Civitai Helper: model_type:ckp
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['V5.1 (VAE)_130072', 'V5.1-inpainting (VAE)_130090', 'V5.0 (VAE)_125411', 'V5.0-inpainting (VAE)_125437', 'V4.0 (VAE)_114367', 'V4.0-inpainting (VAE)_114600', 'V3.0 (VAE)_105674', 'V3.0-inpainting (VAE)_105723', 'V3.0 (noVAE)_106399', 'V3.0-inpainting (noVAE)_106412', 'V2.0 (noVAE)_29460', 'V2.0-inpainting (noVAE)_29461', 'V1.3_6987', 'V1.3-inpainting_7935', 'V1.2_5196']
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/130072
Civitai Helper: File size: 2132625894
Civitai Helper: Target file path: /home/woaiseeit/Projects/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.safetensors
Civitai Helper: Downloading to temp file: /home/woaiseeit/Projects/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV51_v51VAE.downloading
```

The manual download is exactly like that:
```
$ wget https://civitai.com/api/download/models/130072
Length: 2132625894 (2.0G) [application/octet-stream]
```

But the file downloaded by the helper is smaller:
```
$ ls -l realisticVisionV51_v51VAE.safetensors
-rw-r--r-- 1 woaiseeit woaiseeit 1413152768 Aug 23 22:45 realisticVisionV51_v51VAE.safetensors
```

**Comment by woaiseeit** [comment]
It would be cool if the extension could be check for incomplete files when it scans them for updates. %)

**Comment by Trahloc** [comment]
Getting this problem with loras as well.
loading network /home/trahloc/s/ai/stable-diffusion-webui/models/Lora/Detail Tweaker XL/add-detail-xl.safetensors: SafetensorError
Traceback (most recent call last):
  File "/home/trahloc/s/ai/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 238, in load_networks
    net = load_network(name, network_on_disk)
  File "/home/trahloc/s/ai/stable-diffusion-webui/extensions-builtin/Lora/networks.py", line 142, in load_network
    sd = sd_models.read_state_dict(network_on_disk.filename)
  File "/home/trahloc/s/ai/stable-diffusion-webui/modules/sd_models.py", line 291, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "/home/trahloc/mambaforge-pypy3/envs/sd/lib/python3.10/site-packages/safetensors/torch.py", line 259, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

**Comment by butaixianran** [comment]
hi, the issue is, downloadeding is failed by connection issue. but extension thought it is finished.  Now it show an error for this.

check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by woaiseeit** [comment]
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/commit/32555824bb3103bcef1ce626ce7a0a46bd616e17

The fix is not really a fix, will you please reopen the issue?

The `requests` module allows automatic retries when the download is interrupted, see the example in the official documentation, it's super easy:
https://requests.readthedocs.io/en/latest/user/advanced/?highlight=retry#example-automatic-retries

**Comment by deJQK** [comment]
> https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

This problem occurs for me when I submit many jobs, each wants to save safetensor into the same filepath, and thus a conflict.

**Comment by 516340952** [comment]
模型下载放在那个文件夹下啊？？？？
