### ISSUE TITLE
How to get the civitai names for the models automatically

### ISSUE THREAD

**Issue by Devicetron** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#177]
in the "show/hide extra networks" tab it uses the filename for the checkpoints and loras, is there a way to get the names on the titles in their civitai urls automatically using the extension?

**Comment by butaixianran** [comment]
extra network is sd web ui's build-in feature, it only use file name.

**Comment by Devicetron** [comment]
wow thanks, I did not think of that, is there an alternative we can use to batch rename then and still be synced by your extension? you are doing magic for the community by the way... thank you!

**Comment by gurukast** [comment]
With the Civita Hlper grabbing the Model name  for the .info file, and the fact that you can change "replace preview" with the 4 icons, isn't there a way to similarly "replace / intercept" the file name and replace it with the Model name?

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
