### ISSUE TITLE
更新模型时显示Error，导致ui无法刷新

### ISSUE THREAD

**Issue by TimeEternal** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#178]
cmd命令行中没有任何的报错，检查成功
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/18033326/49aa539f-71b0-4aee-8b6a-3aad2cc0c210)
但是在web ui界面显示error导致后续的ui不会刷新，没有任何提示 具体原因未知
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/18033326/53856467-16dc-4efd-ad94-66028018d991)

**Comment by tsukibana** [comment]
报告一个同样类似的问题，如果因为网络原因导致下载模型中断的话，程序会卡在处理中的读秒无法退出网络异常，再次点击UI下载的按钮无效，必须要重启SD才能重新下载。

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
