### ISSUE TITLE
Helper labels LyCORIS  models as Loras

### ISSUE THREAD

**Issue by Jeffpiatt2k4** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#179]
## Describe Issue
the helper shows LyCORIS models as normal Loha models.  it also downloads them to the Loha folder .  i know some lyco plugins just operate them in the normal folder but my extension requires they be in a separate LyCORIS folder and gives them a separate tab.
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

## Screenshot for UI issue
![Screenshot 2023-05-27 155459](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/132238594/e1324a77-9f67-4f8c-b9da-788c9527e5b6)

## Console log's msg or screenshot for function issue
![Screenshot 2023-05-27 155459](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/132238594/e1324a77-9f67-4f8c-b9da-788c9527e5b6)
![Screenshot 2023-05-27 155431](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/132238594/33c4fb84-9e64-44f1-ba0e-fa59a2b7f52e)

**Comment by rlach** [comment]
This could be expanded to "support LyCORIS". For example when you want to download preview images + data for your models you can choose lora, loha, ti and checkpoint, but no lyco.

**Comment by Jeffpiatt2k4** [comment]
Currently even the official CiVal link app doesn't get preview images for Lyco's stored in there own folder. I don't know how it used to work but the current add on has them as a separate network.

**Comment by butaixianran** [comment]
there is a fork for this
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
