### ISSUE TITLE
Feature Request: Custom weight and keywords / Metadata Editor Tab

### ISSUE THREAD

**Issue by MrKuenning** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#18]
I have about 500 LoRAs and I found remembering the right keyword and weights for each one to be impossible.

### My current process
So I started a spreadsheet with:
`Title | Filename | Catagory | URL | Best Weight | Best Keyword Combo | List of avilable keywords.`

I have it then combine the Title and Weight and create a CSV Title and then combine the Filename and weight and best keywords and make a CSV Entry.  This gives me a list to import into the styles CSV .

Example

`Mazda Miata | Mazda Miata | Object | https://civitai.com/models/16258/mazda-miata | 0.6 | MazdaMiata, 1car`

Results in a style entry titled:
`LoRA - Mazda Miata - 0.6	`

With the value being:
`<lora:Mazda Miata:0.6>,  MazdaMiata, 1car`

### Requested Idea
The idea of this extension is to mitigate a lot of that by automating most of it.  However, I would still like to have some creative control over the weight and which keywords it recommends.  Some LoRAs only seem to work with a specific order of words or may require extra keywords.

Ideally, I would love to be able to specify the weight and prompt that goes along with each LoRA and have a button on the thumbnail to enter all of that into the prompt box. 

I would love to see a metadata editor on the Civitai Helper tab, that would list out all of the models' info files and allow users to specify the best LoRA weight and keyword combo.

- I could go to the Civitai Helper Tab

- Select the Mazda Miata LoRA

- Change the recommended weight to: `0.6`

- Enter the recommended keywords to be: `MazdaMiata, 1car`

- Then when I am entering a prompt I can select a button that will add `<lora:Mazda Miata:0.6>,  MazdaMiata, 1car` to the prompt.

If you didn't want to do it on the tab, you could just put an edit button on the Card to edit the metadata.

I feel like this extension can be a super powerful addition to the WebUI and maybe should not be tied exclusively to Civitai.  I feel like we need a metadata file next to each object regardless of the origin, and maybe importing that metadata from civitai could just be one feature of it.

There is a pull request on the A1111 repo to add an auxiliary file next to the model for titles or tagging, but it never seemed to go anywhere.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7953#issuecomment-1440806919
Maybe some collaboration could play in there.

**Comment by butaixianran** [comment]
What you want here, is setting your own best practise to models. That's not a civitai thing anymore, just you happen to view civitai model's description as reference.

This should be a feature in another extension, not in this one. It won't be handled in this extension. Also, you should search on google, there maybe some extensions already did a similar thing as you asked.

For example, this script:
https://github.com/jdolinschi/tagger

Did pretty much the same thing you are doing but with radio buttons can be selected on UI.

**Comment by MrKuenning** [comment]
That extension seems to be for making custom tags and custom prompts.  What I am describing is more like customizing the most optimal way of using a LoRA and being able to select that when the LoRA is used.

I agree it's a larger concept than what this extension is.

But I almost feel like there should be a metadata extension for models and then a Civitai Scraper plugin that can update the extension.  

So many of the LoRAs don't work out of the box with a weight of 1 and the default Trigger Words.

This extension is great and gets you 70% of the way there.  
But it would be amazing if we are able to bridge that last 30% and click edit on a model and specify a default weight of ` 0.6` and a default trigger/prompt of `armor, valkyrie, winged helmet, cape,`

I wold love to have editible fields like:

TItle
Description
Weight
Trigger Words
URL
Example Prompt

that all get stored in the .info file next to the model.

With buttons on the preview image to insert the example prompt or go to the URL.
And maybe the default behavior of clicking the image itself will insert the Lora with the custom weight and trigger words.


I respect your choice about what you want to include in your extension.  I was just excited and proposing ideas.

**Comment by butaixianran** [comment]
Like I mentioned, if they are optimized, they are not civitai things, they are your own things. You just happen use civitai as a reference. 

Then this should not be done with this addon.

**Comment by jokker87** [comment]
I'll implement most of what is requested here in a own extension the next days. stay tuned.

**Comment by MrKuenning** [comment]
Sounds awesome, here is another similar project and more of my ideas.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8366

**Comment by butaixianran** [comment]
This will be handled in 2.0 and with a different extension name. close it since 1.x won't handle it.
