### ISSUE TITLE
webui1.3.0更新后如果设置中附加网络选择thumbs就无法显示按钮。

### ISSUE THREAD

**Issue by marksong233** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#180]
webui1.3.0更新后如果设置中附加网络选择thumbs就无法显示按钮。
只有那些有缩略图的lora无法显示按钮，那些没有缩略图的就可以显示，怀疑是被图片覆盖了按钮。
另外如果选择cards就可以正常显示。
webui版本：20ae71f
![微信图片编辑_20230529031022](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/61261347/c9bf4f4f-81e4-4a07-812b-ee7dd1b3ba6d)

**Comment by ColorfanXP** [comment]
I had the same issue since the update to automatic1111 came out yesterday. The Civitai Helper icons wont appear on the loras/etc that have a thumbnail image, but will on those that dont.

**Comment by mikheys** [comment]
I confirm. I have the same problem.

**Comment by Deckard9999** [comment]
me too. glad to know is not me...

**Comment by marksong233** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#10639](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10639) 因为这个修改，图片被添加了 `position: absolute`，导致了层级覆盖
> 
> 可以在项目根目录的 `style.css` 中添加如下代码，重新启动后，即可解决问题
> 
> ```
> .extra-network-thumbs .actions .additional {
>     position: relative;
> }
> ```

可用

**Comment by Deckard9999** [comment]
> 

it works. thank you very very much. I really apreciate your work.

**Comment by UriahKong** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#10639](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10639) 因为这个修改，图片被添加了 `position: absolute`，导致了层级覆盖
> 
> 可以在项目根目录的 `style.css` 中添加如下代码，重新启动后，即可解决问题
> 
> ```
> .extra-network-thumbs .actions .additional {
>     position: relative;
> }
> ```

哥们你真吊
this code works so well ,everbody check this out and try to apply it ,but I believe this error will be no longer fixed by official civitai,cheers 
问题上一大堆这个bug就你这个解决办法能行啊

**Comment by liulsg** [comment]
复制上述代码还是不能出现四个按钮。只能回退稳定版了。

**Comment by liulsg** [comment]
> > [AUTOMATIC1111/stable-diffusion-webui#10639](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10639) 因为这个修改，图片被添加了 `position: absolute`，导致了层级覆盖
> > 可以在项目根目录的 `style.css` 中添加如下代码，重新启动后，即可解决问题
> > ```
> > .extra-network-thumbs .actions .additional {
> >     position: relative;
> > }
> > ```
> 
> 哥们你真吊 this code works so well ,everbody check this out and try to apply it ,but I believe this error will be no longer fixed by official civitai,cheers 问题上一大堆这个bug就你这个解决办法能行啊
> 
> 
> > [AUTOMATIC1111/stable-diffusion-webui#10639](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10639) 因为这个修改，图片被添加了 `position: absolute`，导致了层级覆盖
> > 可以在项目根目录的 `style.css` 中添加如下代码，重新启动后，即可解决问题
> > ```
> > .extra-network-thumbs .actions .additional {
> >     position：relative;
> > }
> > ```
> 
> 哥们你真吊 这段代码工作得很好，everbody检查并尝试应用它，但我相信这个错误将不再被官方civitai修复，干杯 问题上一大堆这个bug就你这个解决办法能行啊

应该会修复的，不然后面ui升级到最新版的人，还不知道有多少出现这个问题呢。

**Comment by YujoeChiu** [comment]
太牛逼了哥们，给你大拇哥！

**Comment by wmlqk** [comment]
I added the following code in the style.css file in the root directory of the project. After restarting, why hasn't this problem been solved? I feel so sad.
.extra-network-thumbs .actions .additional {
    position: relative;
}

**Comment by lookas231** [comment]
> I added the following code in the style.css file in the root directory of the project. After restarting, why hasn't this problem been solved? I feel so sad. .extra-network-thumbs .actions .additional { position: relative; }

I identified a conflict with the Latent Couple extension. Turning off that extension along with the above solution solved the problem.

**Comment by aomaoyyw** [comment]
thx, the code worked.
你最好直接粘贴在css文档内容的最后，而不要去改它里面原有的内容，即便里面有类似的代码。
You'd better paste it directly at the end of the css document instead of changing the original content in it, even if there is similar code in it.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
