### ISSUE TITLE
Buttons (and refresh) not working in img2img

### ISSUE THREAD

**Issue by Spaceisprettybig** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#182]
When I refresh Civitai Helper in automatic 1111, everything works as normal in txt2img, yet the buttons don't appear in img2img.

I see no error message, and hitting the refresh button creates no new message in the cmd.

Automatic 11111: 1.3

**Comment by RealTekHousE** [comment]
Same here, same version of A1111 too. Only a few of the thumbnails have icons on them. The rest have nothing. Is this because of using the latest version of A1111?

**Comment by UriahKong** [comment]
saaaaame here !!!
before this error happened I replied the new-update 
not only the image2image ,tex2image the refresh button(blue one) is not working ether 
I'm crying bro ,plz help meeeeeeee

**Comment by ColorfanXP** [comment]
Are you guys not reading the other thread? Theres information on how to fix it for the time being. 

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/180

**Comment by RealTekHousE** [comment]
> 

Skipped that thread since I could not understand the topic. 

But this fix worked for me. TX

**Comment by Spaceisprettybig** [comment]
> > 
> 
> Skipped that thread since I could not understand the topic.
> 
> But this fix worked for me. TX

Sorry to be a newb but where exactly do I paste that code?

**Comment by ColorfanXP** [comment]
> > > 
> > 
> > 
> > Skipped that thread since I could not understand the topic.
> > But this fix worked for me. TX
> 
> Sorry to be a newb but where exactly do I paste that code?

in the root folder, style.css, edit with notepad

**Comment by Spaceisprettybig** [comment]
> > > > 
> > > 
> > > 
> > > Skipped that thread since I could not understand the topic.
> > > But this fix worked for me. TX
> > 
> > 
> > Sorry to be a newb but where exactly do I paste that code?
> 
> in the root folder, style.css, edit with notepad

Crud, didn't work. :L I wonder what else might be at play.

**Comment by Spaceisprettybig** [comment]
> > > > 
> > > 
> > > 
> > > Skipped that thread since I could not understand the topic.
> > > But this fix worked for me. TX
> > 
> > 
> > Sorry to be a newb but where exactly do I paste that code?
> 
> in the root folder, style.css, edit with notepad

To be extra sure, you mean the style.css file in the primary folder for automatic1111, containing the webui-user.bat file, correct?

Additionally, I'm not replacing anything, only add the text to the bottom? I just want to make sure.

**Comment by ColorfanXP** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Skipped that thread since I could not understand the topic.
> > > > But this fix worked for me. TX
> > > 
> > > 
> > > Sorry to be a newb but where exactly do I paste that code?
> > 
> > 
> > in the root folder, style.css, edit with notepad
> 
> To be extra sure, you mean the style.css file in the primary folder for automatic1111, containing the webui-user.bat file, correct?
> 
> Additionally, I'm not replacing anything, only add the text to the bottom? I just want to make sure.

Yes, you got it. You cant really hurt anything, its just a web page style sheet. You can make a copy of the file first as a backup if youre worried.

**Comment by Spaceisprettybig** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > Skipped that thread since I could not understand the topic.
> > > > > But this fix worked for me. TX
> > > > 
> > > > 
> > > > Sorry to be a newb but where exactly do I paste that code?
> > > 
> > > 
> > > in the root folder, style.css, edit with notepad
> > 
> > 
> > To be extra sure, you mean the style.css file in the primary folder for automatic1111, containing the webui-user.bat file, correct?
> > Additionally, I'm not replacing anything, only add the text to the bottom? I just want to make sure.
> 
> Yes, you got it. You cant really hurt anything, its just a web page style sheet. You can make a copy of the file first as a backup if youre worried.

Darn, still not working. I'm guessing there's a conflict with another extension.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
