### ISSUE TITLE
This extension cannot read subdirectory or cannot see subdirectory inside symbolic link?

### ISSUE THREAD

**Issue by songib** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#185]
got this error when trying to scan the model folder
`PermissionError: [Errno 13] Permission denied`

for now what I did is just doing [this](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/134#issuecomment-1575639020)

**Comment by butaixianran** [comment]
I can only do what python's API offered. If it won't work then there is nothing I can do here. 

But, you can still ask this in a new fork:
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
