### ISSUE TITLE
过滤.git文件夹

### ISSUE THREAD

**Issue by AlawnCN** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#187]
## Have you read document?
Yes
## Describe Issue
几个模型文件夹都是从huggingface仓库clone下来的，为了可以同步模型，希望可以支持过滤.git文件夹、.gitignore、.gitattributes文件

## Screenshot for UI issue
<img width="1103" alt="image" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/49110973/637cdcc1-f4e7-4479-858f-ebbfe9248bb4">

**Comment by butaixianran** [comment]
why there is git folder in your model folder?
