### ISSUE TITLE
Does not display model info

### ISSUE THREAD

**Issue by pflky** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#188]
I think this issue started in a recent update. The info files are there, but it does not display model trigger words in the cards list for new models downloaded. It also doesn't display the other features like being able to click to add the trigger words to prompt.

**Comment by NikouZhou** [comment]
me too...

**Comment by SteveM50** [comment]
me too

**Comment by NikouZhou** [comment]
try this:

in the root dirt file: <style.css> add code:

.extra-network-thumbs .actions .additional {
    position: relative;
}

**Comment by Ambition24678** [comment]
> try this:
> 
> in the root dirt file: <style.css> add code:
> 
> .extra-network-thumbs .actions .additional { position: relative; }

It works. Thanks!

**Comment by poorshu** [comment]
> 试试这个：
> 
> 在root dirt文件中：<style.css>添加代码：
> 
> .extra-network-thumbs .actions .additional { position：relative; }

非常NICE，大佬，谢谢您的帮助，给您点赞了

**Comment by goldmojo** [comment]
Great, thanks !

**Comment by goldmojo** [comment]
PS : If the owner could fix it, it would be great too ;-)

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
