### ISSUE TITLE
Preview filenames formatting.

### ISSUE THREAD

**Issue by MrKuenning** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#19]
The default filename formats in A1111 Web Ui gives 

Embeddings:  `Filename.preview.png`
Hypernetwords:  `Filename.png`
CKPT:  `Filename.png`
LoRAs:  `Filename.png`

This is the format that the WebUi will create when you have it save the current image to be the thumbnail.

The Civitai Helper uses the first format for ALL 4 types. This caused it to create hundreds of redundant thumbnail images, as most of my models already had a thumbnail image but they did not include the .preview. in the name.

**Comment by butaixianran** [comment]
No action needed
