### ISSUE TITLE
Plugin shouldn't assume all downloads completed successfully

### ISSUE THREAD

**Issue by ketsuban** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#191]
Civitai Helper has the ability to resume a half-finished download if a `.downloading` file is present. However, it does not detect the case where the download is interrupted partway through, which happens a lot with Civitai; it assumes all completed downloads were successful, and proceeds to rename the `.downloading` file containing an incomplete copy of the downloaded file.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
