### ISSUE TITLE
.jpeg preview images not working

### ISSUE THREAD

**Issue by copypastesgptcode** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#192]
I see from the 'how to use section' that the preview image examples you have are for .png

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper#preview-image

Almost every image I save from the Civitai site is as .jpeg and when I scan I lose these images as my previews. Any solution to this?

**Comment by Vulatera** [comment]
Just try to rename your .jpg to .png. This should work.

**Comment by copypastesgptcode** [comment]
Yeah that works but it's strange that it requires png when all of the images download as jpegs on civitai. This means this program is converting them to png after it downloads when it could leave it as jpeg.

**Comment by butaixianran** [comment]
Which image is used as preview is a build in function of sd webui, not by this extension. Ask them to support jpg
