### ISSUE TITLE
Conflict with Latent Couple extension(Two shot)

### ISSUE THREAD

**Issue by lookas231** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#194]
I had a problem with the refresh button not working in i2i. 

I tried the solution of modifying the style.css, but it didn't work for me, so I checked for conflicts with other extensions and found that when I turned off the Latent Couple extension, the refresh and the four buttons worked fine.

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
