### ISSUE TITLE
Can't figure out what the "tool":{} setting is suppose to be

### ISSUE THREAD

**Issue by jebarpg** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#195]
## Have you read document?
Yes

## Have you checked console log window's msg?
yes

## Describe Issue
I'm looking inside setting.json and I can't figure out what to put inside the "tool": {} section.

## Screenshot for UI issue
no screen shot, but here is my setting.json file:

```json
{
    "model": {
        "max_size_preview": true,
        "skip_nsfw_preview": false
    },
    "general": {
        "open_url_with_js": true,
        "always_display": true,
        "show_btn_on_thumb": true
    },
    "tool": {}
}
```

## Console log's msg or screenshot for function issue
this doesn't apply to my issue

**Comment by butaixianran** [comment]
there was a function in that section then removed.
