### ISSUE TITLE
Preview image format

### ISSUE THREAD

**Issue by ImportMemoryLeak** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#199]
1. On the site civitai previews are stored in jpg
but civitai-helper renames jpg in png(without converting), third-party programs(irfanView) notify that the preview has an error in the name of the image format (.jpg file has the name .png, but format still jpg)
2. When scanning models, if you already had previews.JPG, the scanner will download new previews and save them
sample:

Before run scan
Cats -
  - Bobby.pt
  - Bobby.preview.JPG

After scan
Cats -
  - Bobby.pt
  - Bobby.preview.JPG
  - Bobby.preview.PNG

I think it would be nice to add a choice of format name to the scanner menu, jpg or png, this will solve these problems

**Comment by butaixianran** [comment]
you can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
