### ISSUE TITLE
Models not detected + Refresh Civitai helper button duplicates icons

### ISSUE THREAD

**Issue by Nacurutu** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#2]
Hi, thanks for the extension.

I have my models on a different drive, also, to save disk space I prune all my models, and also, I change the files to .safetensors

The HASH change when I prune the model and change the file type, may I ask, it is possible to detect models with the filename? I always leave the filenames the same.

None of the models are getting the previews and info.

Also, every time you click on Refresh civitai Helper, the icons duplicate.

**Comment by geomorf128** [comment]
Civitai Helper: Can not find model info file: C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\madvision_v2.civitai.info
Civitai Helper: Failed to get model info for ckp madvision_v2
Civitai Helper: Start open_model_url
Civitai Helper: Start parse js msg
Civitai Helper: End parse js msg
Civitai Helper: Can not find model info file: C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\beautyMix_v20.civitai.info
Civitai Helper: Failed to get model info for ckp beautyMix_v20
Civitai Helper: Start open_model_url
Civitai Helper: Start parse js msg
Civitai Helper: End parse js msg
Civitai Helper: Can not find model info file: C:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\beautyMixV1_v10.civitai.info
Civitai Helper: Failed to get model info for ckp beautyMixV1_v10
and etc. all model

**Comment by butaixianran** [comment]
Hi, there are only 2 ways to get a model version from civitai: by hash or by id.

I'll add some buttons to force a model link to civitai with id. Not today though.

**Comment by hempires47** [comment]
+1 for the search by ID button as I also pruned my files changing their hashes lol

no rush though, this is so helpful! thanks

**Comment by Nacurutu** [comment]
> Hi, there are only 2 ways to get a model version from civitai: by hash or by id.
> 
> I'll add some buttons to force a model link to civitai with id. Not today though.

Thanks a lot for that, waiting for this update... 

No rush, take your time...

**Comment by butaixianran** [comment]
This is done, update your version

**Comment by Nacurutu** [comment]
Hi, thank you for the update, may I ask, is there a way to compare the file name of the model with the one in Civitai?

For example, if my model is Model1.safetensor to look for Model1 in the civitai database?

**Comment by Nacurutu** [comment]
As i dnt know anything about coding, I asked bing if he can help to achieve that. Bing's response:

---------------------------------------------------------------
Sure, I can help you with that. [To compare file names in JavaScript, you can use the path module to parse out just the base name (without extension or path) and then compare them using the === operator](https://stackoverflow.com/questions/44379891/compare-files-names-regardless-of-extension-in-node)[1](https://stackoverflow.com/questions/44379891/compare-files-names-regardless-of-extension-in-node). For example:

``` js
const path = require('path');
function compareFileNames(f1, f2) {
  let name1 = path.parse(f1).name;
  let name2 = path.parse(f2).name;
  return name1 === name2;
}
```
[To look for the name of a file in the Civitai database, you can use the GET /models endpoint of the Civitai API](https://stackoverflow.com/questions/44379891/compare-files-names-regardless-of-extension-in-node)[2](https://stackoverflow.com/questions/44379891/compare-files-names-regardless-of-extension-in-node). This will return a list of models with their names and other properties. For example:

```js
const axios = require('axios');
async function getModels() {
  try {
    let response = await axios.get('https://api.civitai.com/models');
    return response.data;
  } catch (error) {
    console.error(error);
  }
}
```

To combine these two functions, you can loop through the list of models and call the compareFileNames function for each model name and your local file name. For example:

```js
const fs = require('fs');
async function findMatchingModel(localFileName) {
  let models = await getModels();
  for (let model of models) {
    if (compareFileNames(model.name, localFileName)) {
      return model;
    }
  }
  return null;
}
```


This function will return the matching model object if found, or null otherwise.

---------------------------------------------------------------

I don't know if this can help to look for the file's name and compare them with the ones we have in the disk. 

To improve the Auto Scan option.

**Comment by butaixianran** [comment]
when you search a model on Civitai, you are searching the model name, which is the title of the model page, not the file name.

so, use your file name as a search keyword won't get the right result. Also user could change file name to anything they want.

**Comment by Nacurutu** [comment]
Ok, in that case, im doing it manually... made a search on civitai's webpage, look for the model page, copy the URL, and paste it in the URL field...

If I do it that way, the model Is found, but just typing the model's name, nothing happens, get this error.

![image](https://user-images.githubusercontent.com/18109442/224179299-ad6be402-73eb-459e-92ea-f1f6d9396a23.png)


Also, de AutoScan still doesn't detect the models if they have a different hash.

**Comment by butaixianran** [comment]
it alread told you on UI, fill a url or model id, not a name

**Comment by Nacurutu** [comment]
> it already told you on UI, fill a url or model id, not a name

The model ID? where do I find that? 


Also, Im running the Autoscan.. it is not detecting the models

For example, AllInOnePixelmodel_v1 is in this link: 
https://civitai.com/models/34/all-in-one-pixel-model

but the Auto Scan is not detecting it:
(I prunned this model and changed it to safetensor)

![image](https://user-images.githubusercontent.com/18109442/224182808-34ac6fc2-3679-4036-8db9-4b23faa25131.png)

Sorry if I'm not getting what u r trying to explain me.

**Comment by butaixianran** [comment]
if you can use a model's url, just use it. the number in the url is the id.

document is already told you scan model is finding model by hash, file name doesn't matter.

**Comment by Nacurutu** [comment]
Ok, got it.. thanks...

**Comment by butaixianran** [comment]
I'll close this issue for now, since it is finished. If you don't think it is finished you can reply and reopen this issue.
