### ISSUE TITLE
Current Preview Image Prompt Issues

### ISSUE THREAD

**Issue by MrKuenning** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#20]
The option to insert the current preview image prompt often inserts the wrong prompt or no prompt at all.

I believe this is because it is grabbing the prompt from Civitai and storing it in the info file.
This fails when the image on civitas didn't display a prompt or when the user presses the button to insert a new preview image.

The reality is 99% of the time even when the metadata doesn't display on civitai.com, you can still download the image and drop it into PNG info and still display the prompt.

Example: https://civitai.com/models/16669

I recommend that the images get processed by the PNG info and that data gets stored in the info file.
Likewise, when the image is replaced with a new thumbnail the metadata should be updated to reflect this.

**Comment by butaixianran** [comment]
won't do that, you can ask that to civitai official. 

This is a civitai extension, not a everything extension. If you ask something not offered by civitai, then it should be in another extension.

What you are asking here, is basically you think civitai's information is not good enough, and you want to build your own. In that case, you need to find another extension for that.

**Comment by MrKuenning** [comment]
That makes sense in regard to not pulling extra info for the images on civitai.com.  

But your extension has a button to "replace preview image with one currently selected in the gallery", however when you do that and click the button "Use prompt from preview image" it does not use the prompt from the preview image it uses the prompt from the previous preview image.

**Comment by butaixianran** [comment]
"replace preview" button is not offered by this addon, it is a build-in feature of SD webui. It always be there even you remove this addon.

**Comment by butaixianran** [comment]
Maybe as a handy function in 2.0, not sure. But won't be done in 1.x, so close it for now.
