### ISSUE TITLE
not work with Cozy-Nest

### ISSUE THREAD

**Issue by bluelovers** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#200]
https://github.com/Nevysha/Cozy-Nest

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/167966/d60af2e2-5a4a-49c6-b59d-7bb97546160e)

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
