### ISSUE TITLE
不同于上次的c站链接超时的问题,，又要麻烦作者帮我看一下了，谢谢

### ISSUE THREAD

**Issue by MysteryManTK** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#202]
## Have you read document?
看过了
## Have you checked console log window's msg?
看了，没看懂，感觉可能还是和代理或者网络有关，但不确定
## Describe Issue
这次是在新的电脑上重新装的插件，刚开始是报了，equests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/ac68270450051ac4da9577c622cd45774d19d2c1adf2bda339515daee141e5bc (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000234A0F351E0>, 'Connection to civitai.com timed out. (connect timeout=None)'))，但是我通过代理解决了，且有正常使用几天，但这几天又出了，远程主机强迫关闭的一个提示，然后我又重新折腾了一下，这次是新的没有看到过的一些提示

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/132129804/34f45061-8811-44d1-96e8-2bf5bec0e204)

## Console log's msg or screenshot for function issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/132129804/371a8224-ec08-40c7-ad99-bbe9d25baea4)

**Comment by MysteryManTK** [comment]
备注：今天再出错了几次之后，又突然成功了一次。。。

**Comment by MysteryManTK** [comment]
备注：今天再出错了几次之后，又突然成功了一次，但同时也有一个现象，就是失败的时候虽然不能扫描，但可以用四个图标的功能，但是成功扫描了之后，反而四个图标的功能会消失

**Comment by MysteryManTK** [comment]
它现在又好了，不知道是什么原因导致的，上1秒还不行，下1秒有可以了，还是帮我看看吧，我主要还是想知道代码里的报错是什么导致的

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by butaixianran** [comment]
报错内容的意思是超过最大重试次数，连不上

**Comment by jiangkeli1962743006** [comment]
一摸一样的问题

**Comment by jiangkeli1962743006** [comment]
解决方案是啥啊

**Comment by udiss** [comment]
> 它现在又好了，不知道是什么原因导致的，上1秒还不行，下1秒有可以了，还是帮我看看吧，我主要还是想知道代码里的报错是什么导致的

试试这个教程？ https://www.bilibili.com/video/BV1nE421L7JF

**Comment by udiss** [comment]
> 解决方案是啥啊

试试这个教程？https://www.bilibili.com/video/BV1nE421L7JF
