### ISSUE TITLE
Extra netwrk buttons uttons not appearing on start

### ISSUE THREAD

**Issue by MysteryGuest42** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#203]
On starting Web UI, the buttons for loras are not visible under extra networks. I can bring them in by going to Civitai helper settings and checking "Always Display buttons" and refreshing the extra networks page but the settings do not stick between sessions. 

When i boot up web ui again the setting is reverted and requires to his display buttons again and refresh the networks page. 

Not the end of the world but ive checked settings.json and the flag for buttons is true and doesnt change so not sure what to try next.

**Comment by UnSand** [comment]
You can add the following code to style.css in the project root directory, and after restarting, the problem can be resolved.
.extra-network-thumbs .actions .additional {
    position: relative;
}
Answer from Eurkidu

**Comment by MysteryGuest42** [comment]
> 

Thanks UnSand!

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
