### ISSUE TITLE
[Feature request] Manually add trigger word for lora not from Civitai

### ISSUE THREAD

**Issue by Gh20221205** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#204]
## Describe Issue
This extension has been working great for me with lora downloaded from Civitai as it supposed to be, but I also have some lora files that is not downloaded from elsewhere. In this case, I'm unable to use the bulb button to add trigger word to the prompt windows. Therefore, I request a feature to manually add trigger word to a lora downloaded elsewhere so that I can call these trigger word later.

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
