### ISSUE TITLE
[Feature request] add a donwload button for all on the "Check models’ new version"

### ISSUE THREAD

**Issue by jeanpierre8** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#205]
## Describe Issue
A Feature request is to add a donwload button for all on the "Check models’ new version", for example, I have a lot of loras to update, and I don't want to click in each lora to donwload on civitai helper, we need to add a download button to donwload all the update version in one click.

**Comment by butaixianran** [comment]
You can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
