### ISSUE TITLE
没有预览图的可以显示模型按钮，有预览图的不显示模型按钮

### ISSUE THREAD

**Issue by DaMengLee** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#207]
您好，麻烦问一下，没有预览图的可以显示模型按钮，有预览图的不显示模型按钮 是什么问题，该如何解决？
[https://z4a.net/images/2023/07/03/QQ20230703152348.jpg](url)

**Comment by UnSand** [comment]
您可以在civitai helper的项目根目录中将以下代码添加到style.css中，重新启动后可以解决问题。
.extra-network-thumbs .actions .extra {
position： relative ;
}

回答来自 Eurkidu

**Comment by butaixianran** [comment]
You can ask this in a fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
