### ISSUE TITLE
[Update models] "Download into SD" JS error (ch_dl_model_new_version is not defined)

### ISSUE THREAD

**Issue by dkhold** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#209]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
After checking for model updates, clicking on "Download into SD" doesn't work, there is a JS error.

## Screenshot for UI issue
![Control-V](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/134951619/0ae0b84b-a5b1-4b4e-accb-6d9eac8b9e88)

## Console log's msg or screenshot for function issue
 ```
?__theme=dark:1 Uncaught ReferenceError: ch_dl_model_new_version is not defined
    at HTMLAnchorElement.onclick (?__theme=dark:1:1)
```

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
