### ISSUE TITLE
Feature Request: Add a button to show/hide NSFW previews

### ISSUE THREAD

**Issue by ObiOneStenobi** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#21]
Add a button next to the "Refresh Civitai Helper" to show/hide NSFW preview pictures.

**Comment by butaixianran** [comment]
Won't do it. Which image to be used as preview is decided by SD webui's build-in extra network function, not by this extension.. So, it is not a civitai feature. 

This is a civitai extension, not an everything extension. You need to ask SD webui's team to add this into "Extra Network" tabs.

**Comment by ObiOneStenobi** [comment]
Mmh so one possible solution but not the best one is to replace everytime the previews like the first time and set a blank image to flagged nsfw civitai models?

**Comment by butaixianran** [comment]
As you described, it's a possible solution, but it's not a civitai feature.

**Comment by butaixianran** [comment]
This maybe can be handled in 2.0 and with a different extension name. close it since 1.x won't handle it.
