### ISSUE TITLE
点击图片填入tag框的文件名有错误？

### ISSUE THREAD

**Issue by lastsd777** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#210]
点击图片快速填入tag框的文件名和实际的文件名不一样，以前似乎没这个问题，不知道是哪次更新出现的情况。
因为有部分civitai上的lora，比如角色之类的文件名容易重名，需要在本地修改成不同的文件名，但是civitaihelper会默认使用civitai上的lora原文件名，如果在本地lora文件修改了文件名，那就每次只能手动填写tag。希望能改成优先使用本地文件名。

**Comment by AsteriskQAQ** [comment]
在webui的
设置-拓展模型
将扩展模型添加到提示词时，通过以下格式提及lora 
改成
●文件名

**Comment by butaixianran** [comment]
点击图片填入的名称，是sdwebui自己的功能，不是本扩展提供的。请问那边。本扩展提供的是把图片中保存的内容填入提示词输入框。
