### ISSUE TITLE
feature request: don't rename downloads when updating a model

### ISSUE THREAD

**Issue by Raivshard** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#212]
So, a lot of models have really misinformative names. I always rename them locally to be more coherent and understandable. I would like the filenames I pick to be considered more important than the filename supplied by civitAI. Is this doable?

**Comment by butaixianran** [comment]
You can ask this in a fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
