### ISSUE TITLE
尝试连接到 https://civitai.com/api/v1/model-versions/by-hash/ 时超时

### ISSUE THREAD

**Issue by MingTAT** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#213]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
尝试连接到Civitai 网络超时

## Screenshot for UI issue
<img width="955" alt="10501a267c76ae5b857997f01cb5b60" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/7205597/71221fff-8618-49ad-b084-60910acd895a">

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
