### ISSUE TITLE
Feature: Need hash check feature.

### ISSUE THREAD

**Issue by tranzmatt** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#214]
I've found that sometimes a model, especially a large checkpoint, won't download correctly until I try to use it.  A check of the sha256sum or b3sum will show the hash mismatch, forcing me to redownload it, so it would be very handy to have an option to have the Helper "verify" a download as well as a window to check models much like how it looks for updates.

**Comment by butaixianran** [comment]
hi, there are some models in civitai.com are saved with wrong hash. It's an issue of civitai and they have a place to report this kind of models. You can find that report url at the bottom of this extension's document.
