### ISSUE TITLE
[Feature request] Fetch Activation Text from CivitAI

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#217]
From the upcoming 1.50 update of Automatic1111 (https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.5.0-RC), a very useful functionality to edit the metadata of LoRAs has been added. It would be amazing to be able to get all this data from CivitAI for existing LoRAs.

`extended Lora metadata editor: set activation text, default weight, view tags, training info`

**Comment by butaixianran** [comment]
check a fork for this
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
