### ISSUE TITLE
request to add "model's alternative name" feature

### ISSUE THREAD

**Issue by liewcc** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#22]
First of all, thanks for your affrod and in fact this is the most useful extension for any webui users. I do not understand why CivitAI take so long for such importent extension to be integrated into WebUI, but your afford is appreciated. 

Hereby I suggest to add in a feature call "model's alternative name".

As most of CivitAI model has lengthy file name and it is sometime hard to read from the "extra cards" section. An alternative file name will also helpful for quick picking or in some occations that when the model's orignal file name might not originated from english. e.g. guofeng_v3 which user can choose to display it's alternative file name as "国风" in the extra card section.

**Comment by butaixianran** [comment]
You can just modify model file's name as you wish. Just modify those model info files and preview image files' name too. 

Model id from civitai is saved in those model info files, so model name doesn't matter at all, you can just rename them.

**Comment by bluelovers** [comment]
比起改檔名
我覺得能支援額外顯示 在 civitai 上面的名稱
以及自己追加的名稱的話 會更友善一點

**Comment by liewcc** [comment]
> You can just modify model file's name as you wish. Just modify those model info files and preview image files' name too.
> 
> Model id from civitai is saved in those model info files, so model name doesn't matter at all, you can just rename them.

pratically speaking, we usually will retain the original file name as it is in order to keep track of which version it is. I understand all model can be ranamed as we want, but it will become very confuse when there are ten of handred of new models taht have been generated by all SD users.

**Comment by liewcc** [comment]
> 比起改檔名 我覺得能支援額外顯示 在 civitai 上面的名稱 以及自己追加的名稱的話 會更友善一點

是的，因为模型混搭的门槛很低，最近的未来我们会看到排山倒海的混合模型出现在市面上，而保持原档案名可让我们很轻易的检查是否所下载的是重复的版本或新版本，而增加一个副档案名也能在webui中有限的model card图标空间中，更容易找到我们需要的模型。

可是这还是要回到原作者的意愿，无论如何都要感激他们的无私贡献。

**Comment by butaixianran** [comment]
希望修改extra network的内置功能，请提交给SD web ui 官方。

**Comment by bluelovers** [comment]
> 希望修改extra network的内置功能，请提交给SD web ui 官方。

題外話 Q_Q 話說 身為一個英文溝通白癡 提個希望 排序不分大小寫 都被官方說看不懂啥意思XD

**Comment by butaixianran** [comment]
This can be handled in 2.0 and with a different extension name. close it since 1.x won't handle it.
