### ISSUE TITLE
Civitai Helper has been experiencing a lot of download interruptions lately.

### ISSUE THREAD

**Issue by player99963** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#220]
Recently, when using Civitai Helper to download ckpt models, the download is often interrupted, but the webui interface shows that the download is complete.
And as a matter of course, these downloaded models don't work properly.

Civitai Helper: Getting model info by: https://civitai.com/models/115637/corneos-7th-heaven-mix-fp16cleaned
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai
Civitai Helper: Get subfolder for: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion
Civitai Helper: Get following info for downloading:
Civitai Helper: model_name:Corneo's 7th Heaven Mix (fp16/cleaned)
Civitai Helper: model_type:ckp
Civitai Helper: subfolders:['\\0', '\\1', '\\loli', '/']
Civitai Helper: version_strs:['2.0_125129', '2.0 (no vae)_125134']
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/125129
Civitai Helper: File size: 2132626066
Civitai Helper: Target file path: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.safetensors
Civitai Helper: Downloading to temp file: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.downloading
Civitai Helper: Downloaded size: 0
[-------------                                     ] 27%
Civitai Helper: File Downloaded to: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.safetensors
Civitai Helper: Request version info from civitai
Civitai Helper: Write model info to file: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.civitai.info
Civitai Helper: Checking preview image for model: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.safetensors
Civitai Helper: This image is NSFW
Civitai Helper: Downloading file from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/31daacb0-6eee-4fc7-81d8-ed163d292673/width=1024/1708190.jpeg
Civitai Helper: File downloaded to: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.preview.png
Civitai Helper: Done. Model downloaded to: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\1\corneos7thHeavenMix_20.safetensors

**Comment by create-msugi** [comment]
I fixed this bug.
To @butaixianran : Please check the pull request #233
