### ISSUE TITLE
 4 icon buttons

### ISSUE THREAD

**Issue by n714** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#221]
after update at autoimic11111 v1.5,   4 icon buttons on the card is not show anymore.

**Comment by xyzDist** [comment]
+1 please help

**Comment by 3R1LE** [comment]
+1

**Comment by nowtp** [comment]
Issue is a carry across from the dev build. Seems to be a work around to make it work.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/216

**Comment by nowtp** [comment]
Issue is a carry across from the dev build. Seems to be a work around to make it work.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/216

**Comment by nowtp** [comment]
Issue is a carry across from the dev build. Seems to be a work around to make it work.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/216

**Comment by rayan135** [comment]
same +1

**Comment by vlx** [comment]
+1

**Comment by Wovik253** [comment]
+1

**Comment by SelumFuu** [comment]
+1

**Comment by JashDE** [comment]
+1

**Comment by yattad** [comment]
+1

**Comment by lesspem** [comment]
111

**Comment by jmattatall** [comment]
same here had to revert back to 1.4.1

**Comment by Oem42** [comment]
+1

**Comment by ikeda731** [comment]
i have same issu with after update at autoimic11111 v1.5.1

**Comment by ikeda731** [comment]
Ihave same issue after update at autoimic11111 v1.5.1

**Comment by chaosaiart** [comment]
Same here 
-> Automatic1111 - webui - SD version 1.5.1

**Comment by gigend** [comment]
same +1

**Comment by gigend** [comment]
> same here had to revert back to 1.4.1

how to revert back?

**Comment by jmattatall** [comment]
> same here had to revert back to 1.4.1
I am back on 1.5.1
I was able to get it working by copying the [civitai_helper.js](https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/blob/main/javascript/civitai_helper.js) file into the folder. Just make a copy of the original first then replace it with this one.

**Comment by chaosaiart** [comment]
> > same here had to revert back to 1.4.1
> > I am back on 1.5.1
> > I was able to get it working by copying the [civitai_helper.js](https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/blob/main/javascript/civitai_helper.js) file into the folder. Just make a copy of the original first then replace it with this one.

The reason is quite simple why it doesn't work. 
With the Stable Diffusion Update, a importen area for CivitaiHelper was removed from the Asset-Display-Card, which is why CivitaiHelper is no longer functioning. 

Your JS (JavaScript) adds the area back with the following line of code

```
   if (ul_node==null) {
                      ul_node = document.createElement("ul");   
                      additional_node.appendChild(ul_node);
                  }
                  // replace preview text button
                  replace_preview_btn = card.querySelector(".actions .additional a");

                  if (replace_preview_btn==null) {
                      replace_preview_btn = document.createElement("a");   
                      additional_node.appendChild(replace_preview_btn);
                  }
```

**Comment by HaiderRe** [comment]
+1

**Comment by n714** [comment]
> if (ul_node==null) {
>                       ul_node = document.createElement("ul");   
>                       additional_node.appendChild(ul_node);
>                   }
>   
>                     replace_preview_btn = card.querySelector(".actions .additional a");
>                     
>                   if (replace_preview_btn==null) {
>                       replace_preview_btn = document.createElement("a");   
>                       additional_node.appendChild(replace_preview_btn);
>                   }

after replace the code, 4 button still not show up

**Comment by stanleyshek** [comment]
tried all the possible fixs above but doesn't work.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
