### ISSUE TITLE
Tag Autocomplete: Could not locate model-keyword extension, LORA/LYCO trigger word completion will be unavailable.

### ISSUE THREAD

**Issue by swumagic** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#222]
Tag Autocomplete: Could not locate model-keyword extension, LORA/LYCO trigger word completion will be unavailable.

**Comment by swumagic** [comment]
A1111更新为1.5后，且embeddings 模型看不见了

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
