### ISSUE TITLE
[Feature Request] When checking for model updates, add option to ignore or skip a specific version of a model/lora/etc in future checks

### ISSUE THREAD

**Issue by jpwingfi** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#223]
## Describe Issue
When I check for model updates it will notify me of the most recent version of models. This is mostly fine, but there are a least a couple of instances where it can be an issue: 

- There are some models like the Pokemon LoRA and ChilloutMix that have multiple alts of the same version (eg. fp16 and fp32 for ChilloutMix); I already have the fp16 alt on my PC but CH treats the fp32 alt as a new version since it's the latest, and notifies me of this 'update'.

- Some other models may get new version releases that are not necessarily better/preferred than the older version I have on my PC.

In those cases I'd like to be able to tell CH to ignore those specific versions when checking for updates in the future. 

Thanks for reading.

**Comment by butaixianran** [comment]
you can ask this in a new fork
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
