### ISSUE TITLE
Please switch back to the previous version, please God

### ISSUE THREAD

**Issue by zgmeaw** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#224]
Please switch back, this version is too difficult to use now. Lora's trigger words have to be searched and filled in by herself, and you cannot click on the link to jump to the corresponding Civitai page as before. The four small icons before are still sufficient. Please.

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/83573779/84cb0556-d2ce-482e-9f46-b5aabe33afe0)

**Comment by kuso-ge** [comment]
you are mistaken, that is a new feature update from Auto1111's repo.
This extension just outdated and broke from the updated.

**Comment by GroupTester2** [comment]
https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper.git
Download this some awesome dude made a fix put it in the extensions tab within Auto1111 next to the old Civitai-Helper
i personally put a 1 in front so i could identify when the main file gets updated. i have 2 of each but works fine better than nothing.
![Screenshot 2023-08-01 142546](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/124081399/87254748-86c3-4c71-a77c-42447bf0fedb)

**Comment by Razgrits** [comment]
> https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper.git Download this some awesome dude made a fix put it in the extensions tab within Auto1111 next to the old Civitai-Helper i personally put a 1 in front so i could identify when the main file gets updated. i have 2 of each but works fine better than nothing. ![Screenshot 2023-08-01 142546](https://user-images.githubusercontent.com/124081399/257528092-87254748-86c3-4c71-a77c-42447bf0fedb.png)

After switching my LyCORIS tab broke again(can't see the buttons), is there a fix for that? Tried to implement the fix I previously had but it doesn't seem to work, any idea how to redo it?

**Comment by GroupTester2** [comment]
> > https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper.git Download this some awesome dude made a fix put it in the extensions tab within Auto1111 next to the old Civitai-Helper i personally put a 1 in front so i could identify when the main file gets updated. i have 2 of each but works fine better than nothing. ![Screenshot 2023-08-01 142546](https://user-images.githubusercontent.com/124081399/257528092-87254748-86c3-4c71-a77c-42447bf0fedb.png)
> 
> After switching my LyCORIS tab broke again(can't see the buttons), is there a fix for that? Tried to implement the fix I previously had but it doesn't seem to work, any idea how to redo it?

Every time it disappears for me too I just press the refresh button a few times an it works fine, not the large gray one but the small one with arrows in a circular motion

**Comment by songib** [comment]
I thought it was just me who couldn't refresh the button and had nothing change. 
this main update from them breaks a lot of things, and their change is questionable aswell.
the style refresh button and paste button are under one more click is so stupid aswell.

**Comment by butaixianran** [comment]
check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
