### ISSUE TITLE
Hidden/removed networks after scanning

### ISSUE THREAD

**Issue by ahernandezmiro** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#225]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
After installing the extension and running the local scan, the local models/embeddings/networks that haven't been modified by the tool are missing from the UI selector. The files are stil there but not appearing in the UI.

## Screenshot for UI issue
![Sin título](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5021600/ec1428e8-12ae-405f-a60e-8348e666f62e)

**Comment by butaixianran** [comment]
You need to click refresh button
