### ISSUE TITLE
feature request / QOL improvement

### ISSUE THREAD

**Issue by whitevamp** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#226]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
when in the Check models’ new version section and it gets done and then shows you that there is newer versions available, it would be great if it told you what version you had instead of just telling you what the current ver. is. this way you can look at it and it would say " current ver. "6" --> latest ver. "8" "
also it would be great if it would tell you the file size, this way if your on a slow internet connection / and or a metered connection you could go and look at it right from this page and not have to open up each link to civita. 

## Screenshot for UI issue
no

## Console log's msg or screenshot for function issue
no

**Comment by butaixianran** [comment]
You can ask in a fork for this
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
