### ISSUE TITLE
大佬，助手又用不了

### ISSUE THREAD

**Issue by wangnimaaa** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#227]
在sd1.5.1版本里四个按钮不显示出来，按了刷新也没用，控制台也没有报错。希望大佬修一下，挺好用的插件！

**Comment by kuso-ge** [comment]
This extension hasn't been updated since May.

You can try this fix for now, although it's not perfect: https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/commit/0a62d3af0abd2e159675a62002f3b6ebefce9f5c

**Comment by wangnimaaa** [comment]
> This extension hasn't been updated since May.
> 
> You can try this fix for now, although it's not perfect: [axilesoft@0a62d3a](https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/commit/0a62d3af0abd2e159675a62002f3b6ebefce9f5c)

This won't work either

**Comment by cdmusic2019** [comment]
> This extension hasn't been updated since May.
> 
> You can try this fix for now, although it's not perfect: [axilesoft@0a62d3a](https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/commit/0a62d3af0abd2e159675a62002f3b6ebefce9f5c)
Thanks, fixed it the way you did.

**Comment by kuso-ge** [comment]
@wangnimaaa Try this fix from Goldmojo's fork by zixaphir https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/pull/3/files

**Comment by jonk999** [comment]
> @wangnimaaa Try this fix from Goldmojo's fork by zixaphir https://github.com/goldmojo/Stable-Diffusion-Webui-Civitai-Helper/pull/3/files

While this no longer gives me an error in the log window and the extensions page now loads okay, it doesn't seem to give the icons in the image for each Lora, etc. Even after pressing the refresh button

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
