### ISSUE TITLE
1.51版本错误问题

### ISSUE THREAD

**Issue by lesspem** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#228]
4个按钮不显示，输入c站地址下载模型一直出现 错误

**Comment by wangnimaaa** [comment]
同问

**Comment by ivever2** [comment]
按钮不出现

**Comment by dxdgg** [comment]
I used civitai helper everyday and it help me a lot but it cant work in SD 1.5.1.  it need fix pls before civitai helper version2 realeased. Could u help us? i hope so. thank u!

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
