### ISSUE TITLE
sd更新到1.5.1,关闭了所有中文及多语言插件,预览正常,能看到刷新按钮,但点击无反应

### ISSUE THREAD

**Issue by augusdin** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#229]
## Have you read document?
yes

## Have you checked console log window's msg?
yes

## Describe Issue
sd更新到1.5.1,关闭了所有中文及多语言插件,scan功能能够正常连接连接到civitail并正常下载和显示预览,可以看到Refresh右侧的刷新按钮,但点击按钮没有任何反应,控制台也没有任何输出,点击似乎没有被触发

## Screenshot for UI issue
<img width="2231" alt="2023-08-02_22 26 17" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/129820382/929e5b5d-326f-4c75-94b8-522e601147fb">

## Console log's msg or screenshot for function issue

Launching Web UI with arguments: --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: /Users/xxx/stable-diffusion-webui/extensions/Stable-Diffusion-Webui-Civitai-Helper/setting.json
Civitai Helper: No setting file, use default
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
2023-08-02 22:05:15,908 - ControlNet - INFO - ControlNet v1.1.234
ControlNet preprocessor location: /Users/xxx/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2023-08-02 22:05:15,953 - ControlNet - INFO - ControlNet v1.1.234
sd-webui-prompt-all-in-one background API service started successfully.
Loading weights [0873291ac5] from /Users/xxx/stable-diffusion-webui/models/Stable-diffusion/AbyssOrangeMix2_nsfw.safetensors
Creating model from config: /Users/xxx/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: /Users/xxx/stable-diffusion-webui/models/VAE/orangemix.vae.pt
Applying attention optimization: InvokeAI... done.
Running on local URL:  http://127.0.0.1:7860

**Comment by feynmandj** [comment]
在浏览器的控制台里，发现了以下报错:
Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
    at HTMLButtonElement.update_card_for_civitai (civitai_helper.js?1690982261.5005965:569:45)

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
