### ISSUE TITLE
扫描错误的问题，有跟我一样的么？

### ISSUE THREAD

**Issue by eplay6** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#231]
之前填了代理地址，用了几天，后来不知道是插件安装还是啥原因，几天之后就报错了，哪位大佬知道解决办法啊

requests.exceptions.ProxyError: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/ebb647fe7b8400972ccd922604e5be43957a65d862f0d59f865664a2340afa47 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))

**Comment by wangnimaaa** [comment]
一样

**Comment by ryxiang** [comment]
Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py   修改里边15-18行的com为space,可以切换到镜像站，可以解除魔法

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
