### ISSUE TITLE
"Skip NSFW Preview Images" not working correctly - always loads first image.

### ISSUE THREAD

**Issue by davbardi** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#234]
Line 345 in civitai.py isn't checking the NSFW correctly - should be something like ": if img_dict["nsfw"]!= "None":"

**Comment by sdy623** [comment]
So do I. I want try to make a fix patch

**Comment by sdy623** [comment]
I check the code and the downloaded model info. The json key nsfw is string rather than the bool. That probable the problem is.

```
"url": "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/5dd7174e-a3ae-4929-83ee-8d80266e11b3/width=450/2406511.jpeg",
"nsfw": "None",
```
```
if "nsfw" in img_dict.keys():
    if img_dict["nsfw"]:
        util.printD("This image is N8d80266e11b3/width=450/2406511.jpeg",
"nsfw": "None",
```
```
if "nsfw" in img_dict.keys():
    if img_dict["nsfw"]:
        util.printD("This image is NSFW")
        if skip_nsfw_preview:
            util.printD("Skip NSFW image")
            continue
```SFW")
        if skip_nsfw_preview:
            util.printD("Skip NSFW image")
            continue
```
And we can review this code `if img_dict["nsfw"]` means that if the json have a ["nsfw"] key, the following code will be executed, now that the program will get the ["nsfw"] as a string "None", so the program will be executed with this bug.

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
