### ISSUE TITLE
Support lycoris ?

### ISSUE THREAD

**Issue by taoistwar** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#236]

**Comment by tranzmatt** [comment]
I agree.  Lycos are supposed to be kept in a separate folder from Loras, but because this extension mixes the two, it makes things messy.

**Comment by butaixianran** [comment]
won't do it, check another fork for this
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
