### ISSUE TITLE
[Bug] Not showing buttons - Automatic1111 ver 1.6.0 RC

### ISSUE THREAD

**Issue by suonnon** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#238]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
After upgrading Automatic1111 to version 1.6.0, the CivitAiHelper buttons not showing on checkpoint/hypernetworks/loras/textual inversions cards.
I pressed the refresh blue button, but still not working.
I'm using Automatic1111 1.6.0 RC, CivitAiHelper latest version, default dark theme

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/133345496/4bd7e7f5-efc8-444d-88e1-eba4ec7cc838)

**Comment by jkyndir** [comment]
i ran into the same issue. plz help

**Comment by ponginesu** [comment]
Please refer here.
https://github.com/axilesoft/Stable-Diffusion-Webui-Civitai-Helper/commit/0a62d3af0abd2e159675a62002f3b6ebefce9f5c
Also, although I haven't tried it much, it seems that the creation of unnecessary buttons can be suppressed by changing part of the above code as follows.
```
if (replace_preview_btn==null) {
    replace_preview_btn = document.createElement("a");   
    additional_node.prepend(replace_preview_btn); // <-
}
```

**Comment by waltercool** [comment]
This fix works great to me.

Is this project being updated by maintainer?

**Comment by stanleyshek** [comment]
with UI version 
version: [v1.5.2], this fix doesn't work.

**Comment by xyzDist** [comment]
I did all change on civitai_helper.js, still no luck...

a1111 version 1.6

**Comment by BKbrentz** [comment]
According to the readme.md, perhaps you use the bilingual-localization, a1111 version under 1.6.1 may cause this conflick.disable it,it works.
<img width="761" alt="企业微信截图_16944901729123" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/69199428/f5c63e16-097f-43f5-ae82-961eb4454dcf">

**Comment by butaixianran** [comment]
Done, check new version.
Also there is a fork keeps catching up with latest sd webui.
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by MrSwamps** [comment]
Sorry, I'm not a programmer, how do I implement this fix?
