### ISSUE TITLE
Get activation keywords from CivitAI for LoRAs etc.

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#239]
## Have you read document?
Which document?

Feature request: Get activation keywords from CivitAI for LoRAs etc.
Since Automatic 1111 v1.5, we got a new model "Edit Metadata"-button on models.
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/60541708/441a7fc2-b480-4d28-bf0c-bb3154005352)

This is nifty, and it has space for activation text to be added whenever you click on the network. As well as a default weight. Would it be possible to fetch this data from CivitAI wherever applicable?

It is saved in a json-format:
`{"description": "", "sd version": "SD1", "activation text": "GelatoStyle", "preferred weight": 0.8, "notes": ""}`

It would be amazing if this extension could fetch such data when scanning for CivitAI info. Probably as an option. 
If no json-file exists, it should create one and fill it with as much data as possible.
If json-files exist but it's empty, it should download the data.
If a json-file already exists and has content, it shouldn't download anything. 
Each model should be able to opt out as well, so it prevents future scraping, if you would rather have your own than what's on Civit.

**Comment by TheMightyPheonix** [comment]
I've been wanting this as well.  In my case, the URL of the page that has the download link would also be handy to have added in the notes section, in addition to the description there, as well as all trigger words.

**Comment by MNeMoNiCuZ** [comment]
Yes, a link to the model should be easy enough to add, and super useful, as models are often not named what the model files called etc.

**Comment by butaixianran** [comment]
A bad design for workflow data. still, better than nothing. 

won't support this.
