### ISSUE TITLE
[Feature Request] Move the tab to settings section.

### ISSUE THREAD

**Issue by KonokoAz** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#24]
Hi!, ty so much for make this extensions c:, but I would like to ask for something.

Could be possible move from a tab in the main UI, to a tab in settings section? I already have a lot of tabs :<

This functionality maybe is going to be used around once a week.

Ty so much.

**Comment by butaixianran** [comment]
They are not just settings, there function buttons in this tab and will add more. 

You should ask SD webui's team to find a solution for this "too many tabs" issue. Even you don't use this extension, you still gonna have too many tabs from other extensions. So, you need ask SD webui's team to offer a solution for tabs.

**Comment by KonokoAz** [comment]
Oh it's ok, it was just a suggestion. I'll be looking forward to the new features you mention, thanks a lot for replying c:
