### ISSUE TITLE
Downloading models with Chinese file names will turn into garbled characters

### ISSUE THREAD

**Issue by barst** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#242]
Downloading models with Chinese file names will turn into garbled characters,and show it on UI,it is hard to use,
Like this 
https://civitai.com/models/117926/zen

## Console log's msg or screenshot for function issue

Civitai Helper: model_name:青禅_ZEN
Civitai Helper: model_type:lora
Civitai Helper: subfolders:['/']
Civitai Helper: version_strs:['v1.0_127867']
Civitai Helper: Start downloading from: https://civitai.com/api/download/models/127867
Civitai Helper: File size: 75612244
Civitai Helper: Target file path: E://AILIB/Lora\éç¦_Zen.safetensors
Civitai Helper: Downloading to temp file: E://AILIB/Lora\éç¦_Zen.downloading
Civitai Helper: Downloaded size: 0
[--------------------------------------------------] 100%
Civitai Helper: File Downloaded to: E://AILIB/Lora\éç¦_Zen.safetensors
Civitai Helper: Request version info from civitai
Civitai Helper: Write model info to file: E://AILIB/Lora\éç¦_Zen.civitai.info
Civitai Helper: Checking preview image for model: E://AILIB/Lora\éç¦_Zen.safetensors
Civitai Helper: This image is NSFW
Civitai Helper: Downloading file from: https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a6a5918e-e010-4ae8-b2e6-2cc2ef503ff4/width=1024/1771097.jpeg
Civitai Helper: File downloaded to: E://AILIB/Lora\éç¦_Zen.preview.png
Civitai Helper: Done. Model downloaded to: E://AILIB/Lora\éç¦_Zen.safetensors

If i download from web,the file name is ok, 青禅_Zen.safetensors
(By the way, my system language is ZH_TW, this file name is ZH_CN , maybe save it by utf-16)

**Comment by butaixianran** [comment]
Done, check new version
