### ISSUE TITLE
Delete old version when updating

### ISSUE THREAD

**Issue by MrSwamps** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#244]
Please include an option to delete the old version of a LORA or Checkpoint when updating. I've found out that this isn't done, some of these files are 5-6 GB in size and having multiple version is a big issue. 

Thanks

**Comment by MrSwamps** [comment]
From Civitai Helper tab, select "Check New Version from Civitai"

once updated are found, select update and clicl "Download into SD"

This then downloads the new version of the LORA or Checkpoint.

The issue is that the old version is not removes, so for example, if I download an update to v4 of a checkpoint, v3 is not deleted from the SD folder. this means I now have v3 AND v4, taking up double the space. If there are 3-4 updates this can be 24+GB of wasted space. 

I have to manually find these duplicates and remove them. Would be good to have them auto removes, or a checkbox to allow deletion of old version.

**Comment by butaixianran** [comment]
Added a remove button in new version on card

**Comment by MrSwamps** [comment]
Where is this added? I'v update plugin but can't see this new option.
