### ISSUE TITLE
请问我升级到sd1.6以后，安装了最新的civitai helper，但是没有显示略缩图的按钮了，tab里有，而且能正常scan

### ISSUE THREAD

**Issue by ntfox0001** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#245]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/19569340/b102d238-081e-498c-a6a7-6b683efd1f00)
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/19569340/b0b53a39-6d7e-41e7-bfa2-9d7ad1564885)

**Comment by skupcll** [comment]
sd1.6的lora选项卡集成在下面了,没有单独的按钮

**Comment by butaixianran** [comment]
Done, check new version
