### ISSUE TITLE
My civitai helper does not have a bottom button. 

### ISSUE THREAD

**Issue by LeeBun** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#246]
My civitai helper does not have a bottom button. 
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/90349130/8d2faadf-1947-4a1f-81ce-2f987df518a2)

When I click the blue refresh button, the F12 console prompts
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/90349130/bd573a3b-8d0e-412b-9e36-f2924ef0aca9)

**Comment by Eversor** [comment]
having the same issue

**Comment by ToniMagi** [comment]
Same here!

**Comment by butaixianran** [comment]
Done, check new version
