### ISSUE TITLE
Model folder for Stable-diffusion does not use modified path to models

### ISSUE THREAD

**Issue by PietFourie** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#247]
I use a modified path for my models in order to share the models with other frontends

The path is specified on the web-user.sh file as a command line arg: --data-dir /mnt/3A92DFE192DFA025/StableDiffusion/data
Everything works fine.
When I download a LORA with Civitai-helper the path is correctly assembled:
/mnt/3A92DFE192DFA025/StableDiffusion/data/models/Lora/
and it downloads fine.
However, when I try to download a Checkpoint, the Civitai-helper does not assemble the path correctly and wants to use
/mnt/3A92DFE192DFA025/StableDiffusion/stable-diffusion-webui/models/Stable-diffusion/
When I create the /models/Stable-diffusion directories (I removed them, previously) in the original stable-diffusion-webui folder,  Civitai-helper downloads the checkpoint....... no problem.
It seems as if the checkpoint download routine does not use the custom path and therefor does not assemble the path for checkpoints correctly.
I did not check embedding or other folders.
BTW, I run Ubuntu 20.04 ......

**Comment by PietFourie** [comment]
Oops ..... I forgot to mention... Scanning the folders is fine. It is just the downloading of checkpoints that has a problem

**Comment by butaixianran** [comment]
"--data-dir" is not supported and won't supported.
