### ISSUE TITLE
打開 Civitai 頁面應該由目前瀏覽器開啟 而非由 API 去開啟瀏覽器

### ISSUE THREAD

**Issue by bluelovers** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#25]
打開 Civitai 頁面應該由目前瀏覽器開啟 而非由 API 去開啟瀏覽器

**Comment by butaixianran** [comment]
受到gradio的限制，js端無法收到來自python端的任何信息，所以你想要的這個比較難實現。會想辦法的，無法保證一定能處理。

gradio是SD webui使用的UI庫，非常非常糟糕的一個庫，導致很多本來很簡單、很基礎的功能，變得幾乎不可能。所以，耐心等待吧。

**Comment by bluelovers** [comment]
竟然Q_Q 因為我 SD 是裝在別台電腦上
所以導致點了打開頁面都是開在另外一台電腦上XD

**Comment by butaixianran** [comment]
已完成，更新版本
