### ISSUE TITLE
Issue - WebUI not restarting when press ReloadUI

### ISSUE THREAD

**Issue by suonnon** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#252]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
Whenever I pressed the Reload UI from anywhere that has that button, the webui is just stucking at "Reloading...". I'm using A1111 latest official release version and CivitAiHelper latest version.

This issue was happen only with CivitAiHelper extension enabled. When I disable the extension, the webui restarting/reloading works fine.

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/133345496/bc78c85a-d41a-4efc-aa18-cdb67abdb4f5)

## Console log's msg or screenshot for function issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/133345496/cbf2da8f-6b86-464a-a643-399025e7d4b1)

**Comment by butaixianran** [comment]
I don't have this issue at all. Everything is fine. This extension won't affect reloading at all. 

Your python log also does not have any msg when reloading UI. That means it stops before loading any extension. 

I guess you have enabled xformers, in that case, SD webui's reloading gonna be much much slower. 

Also, you are using Chinese name for models. You should rename them into English to see if it helps.
