### ISSUE TITLE
AttributeError when launching from SD.NEXT master

### ISSUE THREAD

**Issue by LankyPoet** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#253]
SD.Next is up to date:
21:38:10-035253 INFO     Version: app=sd.next updated=2023-10-14 hash=98bf24d7
                         url=https://github.com/vladmandic/automatic.git/tree/master

I receive this error on startup every time after adding the Stable-Diffusion-Webui-Civitai-Helper extension:

`21:38:39-040403 ERROR    Module load: extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
│ C:\sdnext\modules\script_loading.py:18 in load_module                                                                             │
│                                                                                                                                   │
│   17 │   │   with contextlib.redirect_stdout(io.StringIO()) as stdout:                                                            │
│ ❱ 18 │   │   │   module_spec.loader.exec_module(module)                                                                           │
│   19 │   │   setup_logging() # reset since scripts can hijaack logging                                                            │
│ in exec_module:883                                                                                                                │
│ in _call_with_frames_removed:241                                                                                                  │
│                                                                                                                                   │
│ C:\sdnext\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\civitai_helper.py:31 in <module>                               │
│                                                                                                                                   │
│    30 │   "open_url_button": False,                                                                                               │
│ ❱  31 │   "add_trigger_words_button": util.newer_version(util.webui_version(), '1.5.0', allow_                                    │
│    32 │   "add_preview_prompt_button": False,                                                                                     │
│                                                                                                                                   │
│ C:\sdnext\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\util.py:433 in webui_version                            │
│                                                                                                                                   │
│   432 │   version = None                                                                                                          │
│ ❱ 433 │   tag = launch.git_tag()                                                                                                  │
│   434 │   match = re.match(r"v([\d.]+)", tag)                                                                                     │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'launch' has no attribute 'git_tag'`

**Comment by butaixianran** [comment]
sd.next is not supported. but, you can ask this in a fork repo of this project:
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
