### ISSUE TITLE
Aesthetic Gradients support?

### ISSUE THREAD

**Issue by sou-long** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#254]
Hi, I think it would be nice if this (already amazing:1.3) extension supported "Aesthetic Gradients". It's another type of a Civitai resource, like textual inversion / embedding, used via a webui plugin. Upd: Especially interesting to see accompanying thumbnails in a folder with `.pt`s, because it's hard to tell how they look after manual downloading.

Webui plugin:
https://github.com/AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients

How-to from Civitai:
https://github.com/civitai/civitai/wiki/How-to-use-models#aesthetic-gradients

Civitai "repo":
https://civitai.com/search/models?modelType=AestheticGradient

Local path:
`aesthetic_embeddings` (the same folder where e.g. `embeddings` and `extensions` live)

**Comment by butaixianran** [comment]
this extension won't support any other plugins. but, you can ask this in a fork repo of this project:
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
