### ISSUE TITLE
阿里云服务器无法下载civitai的模型

### ISSUE THREAD

**Issue by jqsl2012** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#255]
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/6802595/33b6be22-2c47-46bd-9ec3-6b6533a11f47)

这种情况应该怎么处理呢

**Comment by butaixianran** [comment]
网络问题，请在设置界面中填入代理。
