### ISSUE TITLE
原版UI下 civitai helper 四个按钮会覆盖SD原来的两个按钮

### ISSUE THREAD

**Issue by Array-Cats** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#258]
## Have you read document?
是的
## Have you checked console log window's msg?
是的
## Describe Issue
原版UI下 civitai helper 四个按钮会覆盖SD原来的两个按钮

## Screenshot for UI issue
这个是点击刷新civitai helper按钮前的按钮排版
![Snipaste_2023-11-11_08-25-37](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/33084797/094f3ade-a96e-4ff0-a151-ae091de37b5b)

这个是点击刷新civitai helper按钮后的按钮排版
![Snipaste_2023-11-11_08-25-57](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/33084797/6e060fbd-0bb6-437d-b5f3-021aa39ce55b)

## Console log's msg or screenshot for function issue
没有报错

**Comment by butaixianran** [comment]
卡片尺寸太小了，另外两个按钮在同一行后面。

这个不能转弯换行的样式是webui自带的，扩展这边难以调整。

喜欢用小尺寸卡片的话，用文档推荐的那个fork项目试试看。

**Comment by Array-Cats** [comment]
> 卡片尺寸太小了，另外两个按钮在同一行后面。
> 
> 这个不能转弯换行的样式是webui自带的，扩展这边难以调整。
> 
> 喜欢用小尺寸卡片的话，用本项目文档开头推荐的那个fork项目试试看。
> 
> https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

试用了一下，目前遇到最严重的问题就是没法从c站拉取模型的info文件和图片文件。
当然UI的问题其实并不是很重要，因为lobe theme可以“解决”这个问题。

我最希望的还是能够适配LyCORIS文件夹

**Comment by butaixianran** [comment]
那个版本应该是适配了LyCORIS的。从c站获取模型信息和图片都没有问题。如果你觉得有问题，请清晰描述你的问题现象，python界面显示的什么出错信息。

**Comment by Array-Cats** [comment]
> 那个版本应该是适配了LyCORIS的。从c站获取模型信息和图片都没有问题。如果你觉得有问题，请清晰描述你的问题现象，python界面显示的什么出错信息。

放在LyCORIS文件夹下面的模型没有办法使用灯泡按钮（其他的功能因为并不是很重要所以没有去做测试，但估计也是寄的），点了灯泡按钮后prompt栏并不会添加tag（已确认同一模型在LoRA文件夹内是可以添加tag）。

[zixaphir](https://github.com/zixaphir)fork的版本是可以对存放在LyCORIS文件夹内的模型使用helper插件的按钮功能。

控制台并没有报错，不过浏览器开发者界面没有去看过。

以个人双脚还在门外的水品比较了一下你和ta两人的scripts/ch_lib
/model.py文件差异估计是你这边没有让插件去识别LyCORIS文件夹

**Comment by butaixianran** [comment]
sd webui已经原生支持LyCORIS，没有必要再去用插件。

如果你要用插件的话，前面已经提到了，请使用那个fork的版本
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by Array-Cats** [comment]
> sd webui已经原生支持LyCORIS，没有必要再去用LyCORIS相关插件。
> 
> 如果你要用LyCORIS插件的话，前面已经提到了，请使用那个fork的版本 https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

其实1.5开始整合LyCORIS插件功能后LyCORIS文件夹内模型依旧是可以被SD webui识别的（只是在UI里面并不会单独显示LyCORIS页面，所有LyCORIS内模型会归到LoRA页面中）。

当然目前fork版我认为最大的问题就是下载模型info信息似乎与你的有比较大的区别。

如果你并不打算针对这个进行更新的话~~~~~~~我也就先凑合的用了
