### ISSUE TITLE
Civitai Helper: failed to get model file path

### ISSUE THREAD

**Issue by kider** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#259]
sd版本 v1.6
日志：
Civitai Helper: failed to get model file path
Civitai Helper: subfolder string is None

**Comment by butaixianran** [comment]
在进行什么操作时出现这个错误？你的civitai helper 版本号多少？

**Comment by Nox-M** [comment]
![图片](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/73013773/78fb648a-e734-4c61-a7ef-4d02f642b8b7)

![图片](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/73013773/76d71317-a92e-41cf-99c4-c499c79468ad)

![图片](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/73013773/82aa0e18-8da7-4055-a046-e1de9970b0e0)
你好，我也是出现了这个错误，但我不确定webui是否使用了data目标路径有关的命令行参数，有什么途径可以确定吗？我现在是使用秋葉的启动器。不使用helper进行手动安装是可行的。

**Comment by butaixianran** [comment]
如何查看启动参数还请去秋叶启动器那边询问。

**Comment by butaixianran** [comment]
没有得到进一步反馈信息，并且和第三方启动器有关，因此关闭
