### ISSUE TITLE
Contributing: Configurable prompt and weight per model/lora

### ISSUE THREAD

**Issue by jokker87** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#26]
Hi butaixianran

Many thanks for your effort. I'm a developer myself and really like the extension you created. In our community (https://discord.com/invite/dFB7zuXyFY), we have some additional ideas to integrate into this extension.

Are you cool with it, if i implement those features and send a pull requests to you?

Best regards
jokker

Edit: guess it would be pretty much what was mentioned in #18

**Comment by butaixianran** [comment]
You are welcome to add new civitai feature. But, if it is not a civitai feature, it should not be added into this extension. 

If you are trying to modify those model information from civitai, then you are creating your own model information.

So, the right way to do this is: create another extension, which can load this extension's model info file as input.

**Comment by jokker87** [comment]
We defenetly want to alter the info to our likings. so i guess i will take you're work as a baseline and create another extension, if that's cool with you?

**Comment by butaixianran** [comment]
You are free to take any part of it, also, you can just load the model info file in your extension, since this extension has already downloaded it.

**Comment by jokker87** [comment]
thank you very much for your feedback.
