### ISSUE TITLE
能否做一个www.liblib.art,版本

### ISSUE THREAD

**Issue by xueqing0622** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#261]
https://github.com/sethgggg/Stable-Diffusion-Webui-LiblibAI-Helper
这作者不更新了,  你能否做一个www.liblib.art,版本, 最好是一次能扫描两个网站

**Comment by butaixianran** [comment]
没有这种计划

**Comment by xueqing0622** [comment]
好的  谢谢
已知:civitai模型的hash_value的地址:
https://civitai.com/api/v1/model-versions/by-hash/{hash_value}

请问https://www.liblib.art或者吐司https://tusiart.com/模型的hash_value的地址:是什么呢

**Comment by butaixianran** [comment]
这个请询问该网站运营人员
