### ISSUE TITLE
希望能Civitai Helper Proxy能自动对应到Windows中的代理端口

### ISSUE THREAD

**Issue by annedaphne** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#264]
![QQ截图20231219155942](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/129287927/e59b0ed9-62a7-4dd5-b1e3-53e998e76cfb)
![QQ截图20231219155925](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/129287927/2860bb24-d001-4e72-9388-cd1a56fdd8bd)
就是希望有个选项可以自动将这两个数值一致。。因为使用的魔法上网工具总是会修改它，每次用C站助手都需要手动输，感觉。。很麻烦→ _ →

**Comment by butaixianran** [comment]
请自行在你的代理工具中，设置固定的端口，而不是每次随机端口。
