### ISSUE TITLE
feature request: compatibility with JPG previews vs PNG

### ISSUE THREAD

**Issue by ride5k** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#265]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
when output of SD is set to JPG, preview image does not supersede civati downloaded PNG
manual workaround is possible if PNG is deleted but will be replaced during next sync
## Screenshot for UI issue
N/A, preview does not change

**Comment by butaixianran** [comment]
Which image is used as preview, is a build-in feature of SD webui, this extension just download images and put it there.

You should ask your question in SD webui's issue list.
