### ISSUE TITLE
(Feature Request) Solve the problem with animated previews when scanning models from Civitai

### ISSUE THREAD

**Issue by ostap667inbox** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#267]
Often the preview for a model is in animation format. In this case, Civitai Helper performs an incorrect action: it saves the animation file with the PNG extension. In general, there is no point in saving animations as previews, they can't be displayed in Automatic1111 anyway.

My suggestion, if there is a way to do this: before saving a preview image for a model, do a check to see if it is a video file.
If it is a video file, try to take another image as a preview.

Here is an example of such models. This user has a lot of LoRa with slider function and he makes first preview images animated:
[https://civitai.com/user/ntc/models](https://civitai.com/user/ntc/models)

**Comment by butaixianran** [comment]
Well, I was waiting for SD webui to support display video as preview. Seems they still won't do that.

I'll see what I can do.

**Comment by butaixianran** [comment]
Ok, its done. Update your extension and restart the whole sd webui, not just the "Restart UI".

**Comment by ostap667inbox** [comment]
Thanks! Now the model list looks great and no need to search for problematic previews and replace each one manually.
