### ISSUE TITLE
对于非CIVITAI下载的lora，能否曾加一个录入自定义tag功能

### ISSUE THREAD

**Issue by xymlx** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#27]
因为从Civitai以外地方下载的lora也很多，希望能增加一个存储录入自定义tag的功能

**Comment by sakurairsora** [comment]
同，因为很多关键词其实是在简介里面的，而没有写在关键词里，所以如果能增加自定义录入就好了
再加上还有些是非基础tag，可能会出现“虽然没有写在简介里，但你要这个衣服是这个词，要那个衣服是那个词”的情况，所以感觉可以加入style的功能，要换指定配饰衣服能够一起输入。

**Comment by butaixianran** [comment]
这是个civitai扩展，不是个万用扩展。

你们需要的修改功能，应该是放到一个新的扩展中，然后这个扩展，能读取本扩展的model info文件，作为修改的起点。

而不是把所有修改功能都往这个扩展里面堆。

我们先把civitai扩展应该有的功能完善，然后再去考虑这个全新的自定义模型信息的扩展该怎么设计。

**Comment by sakurairsora** [comment]
是这样，但是c站本身也是确实不少人的触发词不写东西或者就写一个词，把内容全都堆在简介里。只能读取触发词不记录简介，导致可以触发的东西有限，更多的要去模型的主页自己查看说明跟复制，也确实是现在这个插件使用上的尴尬之处

**Comment by butaixianran** [comment]
自定义的修改功能将在2.0添加，并且会用不同的插件名称。因此这里关闭，因为1.x不会去做。
