### ISSUE TITLE
Button don't show up

### ISSUE THREAD

**Issue by mohitsrivastavazzz** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#270]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
The buttons don't show up after installing

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/71134823/c49b9614-9f21-4133-87b6-02eaf2e9e8e2)

## Console log's msg or screenshot for function issue
venv "F:\E\ai\stable-diffusion-webui-forge\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f0.0.7-latest-42-g9c31b0dd
Commit hash: 9c31b0ddcba42afcbda310b46750decd33b6ea2e
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Launching Web UI with arguments: --always-gpu --xformers --ckpt-dir F:\E\ai\stable-diffusion-webui\models\Stable-diffusion --lora-dir F:\E\ai\stable-diffusion-webui\models\Lora
Total VRAM 6144 MB, total RAM 16222 MB
WARNING:xformers:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
xformers version: 0.0.17
Set vram state to: HIGH_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : native
VAE dtype: torch.float32
Using xformers cross attention
==============================================================================
You are running torch 2.0.1+cu118.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.17.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
ControlNet preprocessor location: F:\E\ai\stable-diffusion-webui-forge\models\ControlNetPreprocessor
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
[-] ADetailer initialized. version: 23.7.7, num models: 13
2024-02-07 23:35:37,242 - roop - INFO - roop v0.0.2
2024-02-07 23:35:37,243 - roop - INFO - roop v0.0.2
2024-02-07 23:35:37,249 - roop - INFO - roop v0.0.2
2024-02-07 23:35:37,254 - roop - INFO - roop v0.0.2
Loading weights [bb06ca39b8] from F:\E\ai\stable-diffusion-webui\models\Stable-diffusion\ToyBox2.safetensors
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\modules\gradio_extensons.py:25: GradioDeprecationWarning: `optional` parameter is deprecated, and it has no effect
  res = original_IOComponent_init(self, *args, **kwargs)
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop2\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:38: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  img = gr.inputs.Image(type="pil")
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:55: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  upscaler_name = gr.inputs.Dropdown(
F:\E\ai\stable-diffusion-webui-forge\extensions\sd-webui-roop3\scripts\faceswap.py:74: GradioDeprecationWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  model = gr.inputs.Dropdown(
2024-02-07 23:35:37,757 - ControlNet - INFO - ControlNet UI callback registered.
[Civitai Helper] Settings:
[Civitai Helper] max_size_preview: True
[Civitai Helper] skip_nsfw_preview: False
[Civitai Helper] open_url_with_js: True
add tab
[([button, button, button, button, button], button, gallery), ([button, button, button, button, button], button, gallery)]
F:\E\ai\stable-diffusion-webui-forge\modules\gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 71.7s (prepare environment: 50.9s, import torch: 6.2s, import gradio: 1.3s, setup paths: 1.1s, initialize shared: 0.4s, other imports: 1.3s, list SD models: 0.4s, load scripts: 8.1s, create ui: 1.5s, gradio launch: 0.5s).
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
loaded straight to GPU
To load target model BaseModel
Begin to load 1 model
Loading VAE weights specified in settings: F:\E\ai\stable-diffusion-webui-forge\models\VAE\kl-f8-anime2.ckpt
To load target model SD1ClipModel
Begin to load 1 model
Moving model(s) has taken 0.17 seconds
Model loaded in 9.6s (load weights from disk: 0.9s, forge load real models: 7.4s, load VAE: 0.6s, calculate empty prompt: 0.6s).

**Comment by mohitsrivastavazzz** [comment]
using this fork btw : https://github.com/lllyasviel/stable-diffusion-webui-forge

**Comment by butaixianran** [comment]
forge is not supported. You can try another fork of this project to see if they supported that
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

**Comment by aleph23** [comment]
> forge is not supported. You can try another fork of this project to see if they supported that https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper

I've been using this fork (zixaphir's).  No buttons for me either.  I'm on webui v1.7.0-dev.

**Comment by butaixianran** [comment]
> > forge is not supported. You can try another fork of this project to see if they supported that https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
> 
> I've been using this fork (zixaphir's). No buttons for me either. I'm on webui v1.7.0-dev.

Does it work for you for webui version v1.7.0  (not dev) ?

Have you re-started your web ui after installing?

Are you using webui's default theme? (No other theme applied)

If all question's answers are "Yes", You better create another issue and offer screenshot of your webui.

**Comment by aleph23** [comment]
I haven't used non dev in a while, but I've since switched to forge and found a fork with fully functional buttons, here:
https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/106#issuecomment-1950217258

I'm linking the thread rather than repo so you can see the two other 'working' confirmations.

**Comment by butaixianran** [comment]
since you are using forge now then it's a forge issue.

**Comment by aleph23** [comment]
As I said, with this fork, it is not an issue at all.  Either on 1.7.0-dev or on forge.

**Comment by butaixianran** [comment]
I've checked blue-pen5805's fork's code. Seems it replaced webui's build-in model cards refresh function. 

That is a way to make it work on most versions of sd webui. But webui is still under active development, this way may have other issues in the future.

I'll see if this extension really has to do the same thing after ver1.8 is released.

**Comment by ArmyOfPun1776** [comment]
I don't know if it's gonna help anyone here using Forge but:

The most recent Auto1111 update made my buttons disappear as well.
- Refresh: No Joy
- Delete and Reinstall: No Joy
- Adding the API key: JOY!

After inserting the API Key, Reloading the UI, and Refreshing the Extra Networks; My buttons are back. 

Hope this helps someone.

**Comment by butaixianran** [comment]
You are misleading users. How button shows is a client side thing written with javascript. There is nothing to do with python part. So no matter what you do with API key, there is no difference.

With latest version of this extension, there is no another green refresh button anymore. The refresh function is merged into official's refresh button. 

But, when model cards need to be reloaded from local disk, this addon won't wait for that. Because SD webui has no API to wait for that. 

So this addon will not find any model cards to add additional buttons. 

In that case, you can just click the refresh button again, after your model card list refreshed. 

Maybe I should bring back the green refresh button of this addon. I'll see what I can do.

**Comment by aleph23** [comment]
First, people were looking for a temporary fix to fill in while waiting for upstream,  The fork fulfilled this need.

Second, I did not mention language or API.  I simply said that it worked.  I was in no way attempting to convert anyone to becoming a dedicated user of some other fork, nor was I making false statements with regard to that fork.

@butaixianran , I appreciate and thank you for your work.
