### ISSUE TITLE
[1.8.0.RC] Extra Networks buttons do not appear on latest AUTOMATIC1111 release candidate.

### ISSUE THREAD

**Issue by koblue** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#271]
## Have you read document?

Yes

## Have you checked console log window's msg?

Not applicable

## Describe Issue

On Automatic1111 1.8.0 Release Candidate the buttons that appear on hover for trigger words, civitai page and preview image prompt do not appear. 

There have been changes to the layout of the Extra Networks section in the latest version which may be the cause.

**Comment by butaixianran** [comment]
Hi, I will update this extension after it merges into the main branch. 

But you can try other forks of this project, they may already work for candidate version.

https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
or
https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper

**Comment by koblue** [comment]
Thanks.

I was using the zixaphir fork, had the issue, uninstalled and went with this version since it was more recently update and no change. 

I wasnt aware of the blue-pen5805 fork, so installed that and it now works as expected.

**Comment by Zyin055** [comment]
The A1111 v1.8.0-RC has been merged into the main branch as v1.8.0 now. Eagerly awaiting an update for this handy extension :)

**Comment by butaixianran** [comment]
Done, check new version for SD webui v1.8

Change log:
v1.10.0
* Support SD webui v1.8.x
* With SD webui v1.8.x, this extension's refresh function is added to Official Extra Network's refresh button. There is no need another green fresh button anymore.
