### ISSUE TITLE
Linux系统下路径大小写问题导致四个图标点击无效

### ISSUE THREAD

**Issue by ygrdsj** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#272]
## Describe Issue
CentOS 7
stable diffusion WebUI v1.8.0
Stable-Diffusion-Webui-Civitai-Helper 1.10.0

已经完成信息扫描，并且相应的目录中已经存在正常的.info文件
点击四个图标后无反应，查看日志发现路径中名称大小写存在问题
如下面日志显示真实的路径是/opt/stable-diffusion-webui/models/**Lora**/
而日志中显示的是/opt/stable-diffusion-webui/models/**lora**/
其中 lora 的L的大小写不对，导致无法读取info文件

## Console log's msg or screenshot for function issue

Civitai Helper: Scanning path: /opt/stable-diffusion-webui/models/Lora
Civitai Helper: Done. Scanned 46 models, checked 46 images
Civitai Helper: Start use_preview_image_prompt
Civitai Helper: Start parse js msg
Civitai Helper: Msg: {"action":"use_preview_prompt","model_type":"lora","model_path":"/opt/stable-diffusion-webui/models/lora/add_detail.safetensors","prompt":"","neg_prompt":""}
Civitai Helper: End parse js msg
Civitai Helper: Add Trigger Words for /opt/stable-diffusion-webui/models/lora/add_detail.safetensors
Civitai Helper: Load model info of /opt/stable-diffusion-webui/models/lora/add_detail.safetensors
Civitai Helper: Can not find model info file: /opt/stable-diffusion-webui/models/lora/add_detail.civitai.info
Civitai Helper: Failed to get model info for lora

**Comment by butaixianran** [comment]
Done, check latest version 1.10.1

已更新，下载新版 v1.10.1
