### ISSUE TITLE
希望模型下载里添加一个一键下载所有版本的选项

### ISSUE THREAD

**Issue by tangerdream** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#274]
如图，有些模型里的版本太多了，而且都是单独的模型。。。一个一个下载太不方便了，所以求一个一键下载所有版本功能~
![QQ截图20240310141051](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/72326927/6b42bb50-8737-4dc6-936a-cb03857f97ed)

**Comment by butaixianran** [comment]
不打算添加。但是你有如下选择：

* 通过浏览器下载，再在本插件界面扫描模型。

* 也可以去文档顶部提供的另外两个fork的项目，去查看是否有类似功能。

* sdwebui还有其他专门用来下载civitai模型的插件。请前往那些插件看是否有这样的功能。
