### ISSUE TITLE
关于右键菜单

### ISSUE THREAD

**Issue by tsurumi-rumi** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#275]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
更新WEBUI1.8和插件1.10后LORA界面的右键菜单不再出现，请问该功能是否已经移除？

**Comment by butaixianran** [comment]
这个扩展本来就没有右键菜单。请确认你之前用的是什么扩展。
