### ISSUE TITLE
Feature Request: PNG-Info for Civitai-Images

### ISSUE THREAD

**Issue by nosdregamon** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#276]
Civitai changed it's on-site generator to ditch some meta-data, namely model hashes.

Instead of something along the lines of "Model hash: 529c72f6c3, Model: mfcgPDXL_v10.pony" you get "{"type":"checkpoint","modelVersionId":290640}," which is unusable with A1111 and unreadable for me.

Could you add a "translator" that gives the user an idea, what model or loras were used? 

I know there's an API for that, ( say https://civitai.com/api/v1/model-versions/298238 ) but I got no clue about how gradio works or how to integrate it into a fork of your extension.

Ideally the translator could also check, if the Lora is already downloaded, or give the option to DL it (or a link to the models/loras' page).
--------
If would probably be overkill, but perhaps you could even add a variation of the normal "apply styles" button, that works like the original but with translated civitai-images?

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/1910987/6202d4e6-62f8-4036-af9e-1e92475b0038)

**Comment by butaixianran** [comment]
sd webui has a png info tab, which you can put any image into it to get generation info.

Also, there is a button on your model preview image, can open civitai's model page, on that page, you can check everything about that model and its preivew image.  

This extension is under maintenance phase so it will only fix bugs, no new feature.

**Comment by nosdregamon** [comment]
The thing is: Images generated with Civitai's Online-Generator, currently don't store a name but their internal ID so I don't know, which model to search for in the the previews.

For example: 
https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/9953f218-d98a-4726-a82e-4a6aa045883a/original=true/DFF112EFC16EC499F1545A220ADC0DBF2B0E3501467FF35707A105AAF535553C.jpeg

(PNG Info only gives {"type":"checkpoint","modelVersionId":291443} and no Model name)

However, I think, I found a solution, that just requires Javascript - which I understand in opposite to Gradio - so I'll do a fork and see if I can fix it :)

Thanks for your reply.

**Comment by nosdregamon** [comment]
Oh and "fix" I mean "work around Civitai's changes", there's nothing wrong with your extension. 

Thanks for your fine work.

**Comment by butaixianran** [comment]
Your example image is a jpeg file. Jpeg file won't store any generation information. You can only get generation infomation from a .png file.

If this image is a preview image of a model, you can open that model's web page with additional button of this addon
![Snipaste_2024-03-18_03-58-18](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5558722/79b50eb5-3291-4718-ba06-81faf14ec734)

If this image is not a preview image of a model, then it is not a business of this extension. You should ask sd webui to do something with its png info function, to add a link for civitai model's web page.

**Comment by nosdregamon** [comment]
If you say it's out of the scope of the Civitai-Helper, well, I don't want to bother you. 

I got a workaround for now, maybe it's helpful for others and/or maybe I can translate it into it's own thing:
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/277

Just a nickpick aside: Somehow the Jpg has stored information!?
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/1910987/78e0fcfc-657a-46c7-8f04-fbedabf40d47)

**Comment by butaixianran** [comment]
Sorry, checked again, seems jpeg file can have custom data section. But still, this should be a new feature to sd webui's png info function, not to this extension.
