### ISSUE TITLE
404: Not Found on models that exist on CivitAI?

### ISSUE THREAD

**Issue by hobojoker** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#278]
I have the API included, and if I manually update the LORA using Get Model Info from Civitai by URL, it will update with correct image and info, but running the scan to update, it returns a 404: not found

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/13595470/7c1402a0-fa5b-4403-ab36-38e45c8004d3)

Model: https://civitai.com/models/264290

I'm not sure why it's returning 404 when the model clearly exists?

I'm updating like 130 models, and this is happening on like 20-30 of them

It's consistently the same models too, so I don't think it's a temporary timeout or anything like that.

**Comment by butaixianran** [comment]
When searching model info from civitai, this extension uses sha256 hash code as search id. 

But, some models in civitai's database are saved with a wrong sha256 code, or even failed to generate any hash code.  
Civitai has this issue for a long time. They know it, but never fix it. 

You can check this part of document for detail:  
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper?tab=readme-ov-file#get-wrong-model-info-and-preview-images-from-civitai

So, civitai has a  discord topic to report this kind of models:  
https://discord.com/channels/1037799583784370196/1096271712959615100/1096271712959615100

You can report those models to civitai with above topic, so they can fix those model's sha256 data. 

A solution for now is: you can use this extension tab's "Get Model Info from civitai by Url" function, to bind that model to a civitai model page:   
![Snipaste_2024-03-18_09-04-03](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5558722/00793bd1-3782-4a4b-b12a-c845b54d845c)

**Comment by hobojoker** [comment]
Oh, and here I thought I read through your page well enough. Sorry for the redundant issue! Thank you for the quick response
