### ISSUE TITLE
connect timeout=None

### ISSUE THREAD

**Issue by brighticewing** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#279]
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='civitai.com', port=443): Max retries exceeded with url: /api/v1/model-versions/by-hash/37d3cfdaa735db35e866f727dfbe4ddb81e25c5e7c3a45c275527834c4101f1d (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001F50B806680>, 'Connection to civitai.com timed out. (connect timeout=None)'))

How to fix

**Comment by butaixianran** [comment]
network issue, try again later or use a proxy.

**Comment by linzhon1** [comment]
Using a proxy is still an error

**Comment by butaixianran** [comment]
* Make sure your proxy is ok
* You need to set your proxy on sd webui's setting page, civtai helper section. As document already said.
* For sock5 proxy, you need to use `socks5h://xxxxxxx`, not just `socks5://`, which is also described in document.

**Comment by brighticewing** [comment]
> * Make sure your proxy is ok
> * You need to set your proxy on sd webui's setting page, civtai helper section. As document already said.
> * For sock5 proxy, you need to use `socks5h://xxxxxxx`, not just `socks5://`, which is also described in document.

我用了全局代理，还是error

**Comment by butaixianran** [comment]
请在设置页面，civitai helper分页设置代理，全局代理是否对python有效没有测试过

**Comment by butaixianran** [comment]
没有进一步信息，本地实测代理是一直有效的，因此关闭
