### ISSUE TITLE
Helper no longer able to pull information from Civitai

### ISSUE THREAD

**Issue by MCSizematters** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#281]
## Have you read document?
YEs

## Have you checked console log window's msg?
Yes

## Describe Issue
The app returns an error when entering a Civitai URL to download a model.
The app returns an error when attempting to scan models.
THe app returns 404 errors when checking for updates.

## Screenshot for UI issue
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/165220979/72c89057-75f5-4077-8974-2e9d5dcd1622)

## Console log's msg or screenshot for function issue
Download Model

Civitai Helper: Getting model info by: https://civitai.com/models/45484/jess-bush
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai: 45484
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: An error occurred while attempting to process model info:
        'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (get_model_info_by_url) didn't receive enough output values (needed: 6, received: 1).
Wanted outputs:
    [state, textbox, textbox, dropdown, dropdown, <gradio.layouts.Column object at 0x000001A7F84534F0>]
Received outputs:
    [None]

Scan Models

Civitai Helper: Creating model info for: DV_S2_Malani_Vicious.pt
Civitai Helper: model action sha256: a671ac4ee030f0241a2f6ea02acd7ad3d7427b60b9e3926cc96b4887150861cf
Civitai Helper: Request model info from civitai
Civitai Helper: Fetching Parent Model Information
Civitai Helper: Request model info from civitai: 370246
Civitai Helper: GET Request failed with error code:
   404: Not Found
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1117, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
  File "E:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 162, in scan_model
    for result in scan_single_model(filepath, model_type, refetch_old, delay):
  File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\model_action_civitai.py", line 90, in scan_single_model
    model_info = civitai.get_model_info_by_hash(sha256_hash)
  File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 126, in get_model_info_by_hash
    content = append_parent_model_metadata(content)
  File "E:\stable-diffusion-webui\extensions\Stable-Diffusion-Webui-Civitai-Helper\scripts\ch_lib\civitai.py", line 95, in append_parent_model_metadata
    content["creator"] = parent_model.get("creator", "{}")
AttributeError: 'NoneType' object has no attribute 'get'

Scan for updates:

Civitai Helper: Checking models' new version
Civitai Helper: Scanning path: E:\stable-diffusion-webui\embeddings
Civitai Helper: Request model info from civitai: 249616
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 301159
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 107286
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 191578
Civitai Helper: GET Request failed with error code:
   404: Not Found
 
-truncated for space, same result for all models and types - 

Civitai Helper: Request model info from civitai: 152791
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 20781
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 187997
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 193628
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 65639
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 116832
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 116832
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 61099
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 61099
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 9976
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 25282
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 172695
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 140653
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 140589
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 177236
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 97949
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 239803
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 179155
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 107950
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 277887
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 77314
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 276413
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 113938
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 185969
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 93984
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 256435
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 256435
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 196718
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 37006
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 81410
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 99949
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 131822
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 50030
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 24960
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 17455
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 207902
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 102637
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 99256
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 20682
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 8631
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 198920
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 153412
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 8328
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 8328
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 155465
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 156623
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 142273
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 103028
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 7874
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 120628
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 138024
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 112364
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 59527
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 127206
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 169259
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 230182
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 156182
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 102838
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 102838
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 120025
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 120025
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 110762
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 162622
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 147275
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 86417
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 181319
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 9272
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 152610
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 173175
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 34195
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 115562
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 138917
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 189991
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 136067
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 91775
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 91775
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 72451
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 113621
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 61333
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 144378
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 227442
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 105945
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 84625
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 56168
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 157552
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 103442
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 107231
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 26578
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 88024
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 134952
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 175779
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 262240
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 56859
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Scanning path: E:\stable-diffusion-webui\models\LyCORIS
Civitai Helper: Request model info from civitai: 248856
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 8328
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Request model info from civitai: 8328
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: Done: no new versions found.

**Comment by hobojoker** [comment]
I think this is probably because of the new content filtering on the site, it will probably be a bit before the extension is updated

**Comment by butaixianran** [comment]
Hi, I tested some models you listed above. 

Everything is ok, I can get it from civitai without any problem with latest SD webui and this extension. 

So, you need to check following things:
* Are you using another fork of this extension?  For example:

https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper
or
https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper

If so, you need to ask your question there.  

* How did you set your "Content Moderation" setting of your civitai account? You may want to show everything to make sure you can get all models. Like following:  

![Snipaste_2024-03-28_14-53-57](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5558722/586c3b81-137e-43fb-bebf-bb6ad671f8e3)


![Snipaste_2024-03-28_14-53-45](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/5558722/2e1b620b-817e-4607-a75e-3b38f498ac98)

**Comment by hobojoker** [comment]
It's working now with no changes, I'm guessing that there was just an issue with civitai API at the time of these posts

**Comment by MCSizematters** [comment]
Yes, everything seems to be working as expected now. Perhaps, as suggested, growing pains as they expand their ratings system. 

Sorry for the ultimately spurious report, and thank you for the quick reply!
