### ISSUE TITLE
Download Model：Model folder is not a dir ~/stable-diffusion-webui/models/Stable-diffusion/

### ISSUE THREAD

**Issue by maudBoy** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#283]

**Comment by butaixianran** [comment]
seems python's folder check function can not handle linux user home's "~". 

I'll see what I can do about it.

**Comment by butaixianran** [comment]
Added a quick fix to get linux's real user home path.  

Update you extension to latest version, which should work. If not, add feedback here, thanks.

**Comment by butaixianran** [comment]
No feedback, offed a fix, so closed
