### ISSUE TITLE
使用此插件后只能显示一部分LORA模型

### ISSUE THREAD

**Issue by bismarckliu** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#284]
## **如图所示**
<img width="702" alt="52bbe500d50937a528f0b7f0d4a1744" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/166169977/c861386e-07c6-482e-af9b-c9b672e74bae">

<img width="397" alt="6a479fc7f980c492982a2ae6710a0c7" src="https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/166169977/fcca533a-1e08-4b96-b0da-7c5f5a3251a8">

我明明有3个模型却只能显示一个 唯一显示的那一个还是我从秋叶启动器上下载的，其他两个都是从CIVITAI上面下载下来放进去的。但是这两个就死活不显示。我谷歌搜了很久都没有找到解决办法，希望大佬能知道怎么回事

**Comment by butaixianran** [comment]
看文档。

* 设置代理。

 * 看文档Cvitai Api Key 的部分，以及紧跟在后面的 内容过滤的部分。

**Comment by butaixianran** [comment]
无进一步反馈，且已经提供解决方案
