### ISSUE TITLE
预览图最多只能下载10个么？

### ISSUE THREAD

**Issue by larchsis** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#285]
设置代理以及api key后，下载模型和预览图都成功。但是遇到预览图超过10张的情况，只能下载前10张预览图，后面的就下载不了。是c站api的限制还是其他原因？

**Comment by butaixianran** [comment]
没有这种限制，查看文档“Civitai网站上的内容可见设置”部分，或你的civitai帐号上的其他设置，看是否是原因。

[[https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/README.cn.md#civitai%E7%BD%91%E7%AB%99%E4%B8%8A%E7%9A%84%E5%86%85%E5%AE%B9%E5%8F%AF%E8%A7%81%E8%AE%BE%E7%BD%AE](url)](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/blob/main/README.cn.md#civitai%E7%BD%91%E7%AB%99%E4%B8%8A%E7%9A%84%E5%86%85%E5%AE%B9%E5%8F%AF%E8%A7%81%E8%AE%BE%E7%BD%AE)
