### ISSUE TITLE
'Can not find model info file' after clicking to 'open this model civitai url' button

### ISSUE THREAD

**Issue by ostap667inbox** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#286]
## Describe Issue
After today's WebUI update to 1.9.0, it is impossible to open the Civitai URL for any model.
I don't use special characters in paths and filenames. The ***.civitai.info files previously created by Civitai Helper are in the same folders as the models, I checked, they are not deleted and are available.

## Console log's msg or screenshot for function issue
```
Civitai Helper: Start open_model_url
Civitai Helper: Start parse js msg
Civitai Helper: Msg: {"action":"open_url","model_type":"ckp","search_term":"MODELS\\SDXL\\Juggernaut XL - SDXL\\juggernautXL_v8Rundiffusion.safetensors","prompt":"","neg_prompt":""}
Civitai Helper: End parse js msg
Civitai Helper: Open Url for MODELS\SDXL\Juggernaut XL - SDXL\juggernautXL_v8Rundiffusion.safetensors
Civitai Helper: Load model info of MODELS\SDXL\Juggernaut XL - SDXL\juggernautXL_v8Rundiffusion.safetensors in ckp
Civitai Helper: Can not find model info file: F:\NEURAL\MODELS\MODELS\SDXL\Juggernaut XL - SDXL\juggernautXL_v8Rundiffusion.civitai.info
Civitai Helper: Failed to get model info for ckp MODELS\SDXL\Juggernaut XL - SDXL\juggernautXL_v8Rundiffusion.safetensors
```

**Comment by butaixianran** [comment]
Find a bug when using custom model folder. Add a quick fix. 

Get the latest version and try again. You need to re-start the whole sd webui after updating this extension. Just reload UI won't work.

**Comment by butaixianran** [comment]
No feedback and offered a fix, so closed
