### ISSUE TITLE
Question: When using the "Check New Version from Civitai" feature, is there a way to list models that get 404 page errors? 

### ISSUE THREAD

**Issue by Fretag** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#288]
I have many, many not-so often used models and I'm curious which one's are no longer available on Civitai. 

![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/75547953/24900711-f38a-4b34-90a9-63c5d9c47da0)

**Comment by butaixianran** [comment]
No, there is not. But this is a reasonable request, I'll see what I can do.

**Comment by butaixianran** [comment]
hi, I checked the code, I don't think you are using this extension. 

There is no msg as "GET Request failed with error code" in this extension. You must be using another fork of this project.  

With this extension, If it can not find a new version of a model, it gonna ignore that model and go to check next one. So there is no such msg.

**Comment by Fretag** [comment]
Hi, Thank you for checking, in fact I just noticed you point out there is no batch download (which is included in the version I am using). So apologies for getting that confused. I'm a little inexperienced in how to determine the versions, forks etc.
