### ISSUE TITLE
Completed:  * Vixon's Pony Styles: An error has occurred while downloading: 'content-length' ('content-length',)

### ISSUE THREAD

**Issue by diffussy69** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#289]
i get the following error when trying to run a batch download of a bunch of loras: 
https://civitai.com/models/352581/vixons-pony-styles::allFiles::AllModels

Heres a screenshot: ![Screenshot 2024-06-12 012710](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/172483771/99a24f9c-36b3-4c50-81e9-24df348db43b)

**Comment by butaixianran** [comment]
You are not using this extension. This extension has no batch download function. I guess you are using another fork of this project which has the same extension name.
