### ISSUE TITLE
lora dosent work

### ISSUE THREAD

**Issue by baemao** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#290]

**Comment by butaixianran** [comment]
No detail no answer. Also, it works, I just used it today.

**Comment by todochenxi** [comment]
> No detail no answer. Also, it works, I just used it today.

我遇到了类似的问题，我下载的是这个模型https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu，在配置好api key的时候，可以正常下载，Lora 目录里是有的，但是无法加载该模型

**Comment by todochenxi** [comment]
> > No detail no answer. Also, it works, I just used it today.
> 
> 我遇到了类似的问题，我下载的是这个模型[https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu，在配置好api](https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu%EF%BC%8C%E5%9C%A8%E9%85%8D%E7%BD%AE%E5%A5%BDapi) key的时候，可以正常下载，Lora 目录里是有的，但是无法加载该模型

我试着下载一个不需要api key的模型，可以正常加载，这里也许有bug

**Comment by butaixianran** [comment]
> > 我遇到了类似的问题，我下载的是这个模型[https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu，在配置好api](https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu%EF%BC%8C%E5%9C%A8%E9%85%8D%E7%BD%AE%E5%A5%BDapi) key的时候，可以正常下载，Lora 目录里是有的，但是无法加载该模型


你提供的地址是个SDXL的lora，请确定你使用的是SDXL基础模型

**Comment by todochenxi** [comment]
哦，谢谢

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/19/2024 19:46 |
| To | butaixianran/Stable-Diffusion-Webui-Civitai-Helper ***@***.***> |
| Cc | haruhi ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] lora dosent work (Issue #290) |

我遇到了类似的问题，我下载的是这个模型https://civitai.com/models/426152/haruhi-suzumiya-the-melancholy-of-haruhi-suzumiya-suzumiya-haruhi-no-yuuutsu，在配置好api key的时候，可以正常下载，Lora 目录里是有的，但是无法加载该模型

你提供的地址是个SDXL的lora，请确定你使用的是SDXL基础模型
