### ISSUE TITLE
Suggestion: Category Sub Folder Option

### ISSUE THREAD

**Issue by Natans8** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#293]
Each model in CivitAI is assigned a category:
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/52584161/b9f1258a-19c6-4fca-ac73-3b7771916781)

It is stored as a tag, but unlike other tags, it is mandatory to select in order to upload a model, and has a special place in the model's page.
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/52584161/043152d5-c7fd-42d4-bad8-526db0241f2f)

It is useful for me, and I speculate that also to many other users to sort the downloaded loras by category, for example to store all characters together, or all styles together (especially styles in the era of Pony Diffusion), for easy selection and browsing. I already do so manually, but it would be very comfortable if the category was grabbed automatically with the option to save the file in the according sub folder, like we already can do with the base model or the author.

At the moment, the extension throws in the category with the other tags, alphabetically
![image](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/52584161/4a0f686c-cf01-4a42-8d85-f5ea9b874dc0)

If even some of those features would be implemented I am sure they would find much use by the community. Thank you in advance!

**Comment by butaixianran** [comment]
This extension has no tag function. You may be using another fork of this project. 

Also, SD webui uses model's folder name as category. You can create sub-folders for your model and lora.
