### ISSUE TITLE
scan没有反应，后台日志也没有

### ISSUE THREAD

**Issue by lgkt** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#294]
![微信截图_20240629145240](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/assets/169603344/15829539-cef6-4664-bb46-15e0464e7780)

**Comment by butaixianran** [comment]
从你的截图看，你使用的是别人修改过的本插件，而不是我们这里的版本。所以请前往你获取这个插件的地方询问。
