### ISSUE TITLE
Check models' new version feature should make sure they don't already have new version

### ISSUE THREAD

**Issue by nykwil** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#295]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
The "Check model's new version" feature returns a list of models that have newer versions then the ones already downloaded even if you have already downloaded the newer version. Often you want to keep older versions, and sometimes the civitai page has variation models as versions (for instance it says the pony version is a higher version then the xl version) in which case you need multiple versions.

You should not be shown models updates for models you've already updated, and if the idea is to show that you have multiple versions of the same model then that should be a different feature since it is not a desired behaviour in many cases.

## Screenshot for UI issue
![image](https://github.com/user-attachments/assets/4730018e-3acb-4dd6-a930-9090ed5effb1)

## Console log's msg or screenshot for function issue
N/A

**Comment by butaixianran** [comment]
hi, the feature you asked is alreay there. But, it only check if there is already a new version of your model under the same folder.

In your case, your v2.0-inpainting model is under a folder named "inpaint", but your classic version 3.1.1 model is in another folder, so this addon reminded you this new version again.  

I may need to add a new option to let people choose if they want to check all folders for new version existing. I'll let you know when it's done.

**Comment by nykwil** [comment]
Could be a good feature, but I can work with this, thanks.

**Comment by butaixianran** [comment]
Done, you can update to new version and re-start your sd wbui, not just reload UI. 

There is a new checkbox "When checking new model version, check new version existing in all model folders" on this extension's setting page, and it is already set to "true" as default, so you don't need to do anything about it.  

If it doesn't work, just check that option and save setting.
