### ISSUE TITLE
I don’t know how to enable nsfm models

### ISSUE THREAD

**Issue by DELTER1235** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#298]
#No# Have you read document?

#No# Have you checked console log window's msg?

#I don’t know how to enable nsfm models in the civitai helper tab# Describe Issue

#
![image](https://github.com/user-attachments/assets/5fc3565b-093b-46dd-9ff2-8c85c34afb77)
# Screenshot for UI issue

**Comment by butaixianran** [comment]
Setting is on sd web ui's setting page, with a civitai helper section.

**Comment by DELTER1235** [comment]
> Setting is on sd web ui's setting page, with a civitai helper section.

thank you
