### ISSUE TITLE
trigger words 可以參考  model-keyword 的作法

### ISSUE THREAD

**Issue by bluelovers** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#30]
https://github.com/mix1009/model-keyword

這似乎能夠從檔案內找出他的 trigger words
比起 Civitai 頁面上顯示的更精準(有些作者在頁面上填寫的都是錯的)

**Comment by butaixianran** [comment]
這個是他個人手動整理的，他自己認爲合理的tigger words列表，寫在一個txt文件里。它的插件只是去讀取這個txt。

只是他整理的特別多，當你使用常見模型的時候，就感覺好像全都覆蓋到了。

但每個人想要的trigger words都是不一樣的，別人用的模型，他也不一定會去整理。大家想要的詞語結構，前綴，後綴，也都不同。而且，原作者一旦失去熱情，這種手動製作的列表就再也無法更新。

自定義的模型信息功能，會在2.0添加，但不會用這種方式。

**Comment by bluelovers** [comment]
> 這個是他個人手動整理的，他自己認爲合理的tigger words列表，寫在一個txt文件里。它的插件只是去讀取這個txt。
> 
> 只是他整理的特別多，當你使用常見模型的時候，就感覺好像全都覆蓋到了。

...竟然是手動的
