### ISSUE TITLE
是不是这个插件已经不能使用了

### ISSUE THREAD

**Issue by coinbalance** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#309]
我安装了最新版本version:1.11.2，也设置了API，也科学上网了，但是所有url扫描都显示错误，现在还能使用这个插件吗，是不是C站把这个插接件屏蔽了？

**Comment by butaixianran** [comment]
显示什么错误，是可以用的，并没有收到其他人反馈说不行
