### ISSUE TITLE
Civitai Helper: Failed to get model_info

### ISSUE THREAD

**Issue by helloyesterday** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#31]
scan的时候出现Civitai Helper: Failed to get model_info，我把这个文件移走再scan，结果其他文件又出现相同的Failed to get model_info了，就这么弄了好几次，总是有文件报Failed to get model_info的错误。我看了一下，有些文件不是在c站下的，但是也有文件就是从c站下的。所以在scan能不能把这些找不到info文件直接略过，我这里有上百个文件，一个一个弄太麻烦了。

**Comment by helloyesterday** [comment]
我又测试了一下，发现本质似乎是因为缺少preview的图片，我随便给个png文件改成xxxx.preview.png，不用把文件移走也能过，但这仍然是个问题。

**Comment by butaixianran** [comment]
检查预览图的时候，他会扫描这个文件的 model info 信息在不在。不在就会告诉你不在，这就是你看到的。这不是错误。

**Comment by bluelovers** [comment]
> 当然，今天的话，你看到的可能是真的出错，因为今天civitai网站挂了，频繁连不上。所以等civitai恢复了，你再试试看。
> 
> 今天civitai挂了8小时左右。如果你在这期间扫描模型，会生成一批空的模型信息，导致civitai网站恢复之后，插件不会再扫描这些模型。所以，建议你按文件尺寸排序，把那些空的模型信息删掉，等civitai恢复了重新扫描。
> 
> civitai网站会挂8小时是我们没有想到的，插件暂时无法应对这种情况。只能暂时手动删除空的模型信息。

可以增加防錯設計 當連線發生錯誤的時候 就不建立空模型信息

**Comment by butaixianran** [comment]
已经设置过了
