### ISSUE TITLE
C站检查最新版本功能时，请考虑重复提示问题。

### ISSUE THREAD

**Issue by lanfeicui** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#32]
比如某个模型下载页面，作者发布了V1 V2 V3 三个版本
本地已保存了V1 V2 V3版本，但检查还是会提示V1 和 V2 存在最新版本。

**Comment by butaixianran** [comment]
用户自己选择了保留老版本。自然会去检查。这不是什么问题，这是应该的，是用户自己的选择。

**Comment by lanfeicui** [comment]
可是本地已下载最新的版本了呀。

**Comment by butaixianran** [comment]
目前扩展没有办法知道你是否已经下载了新版本。因为文件名不是标准，文件名可以乱改，hash和id才是标准。要找到对应hash，就要把所有文件全部扫描一遍。不可接受。

要不扫描文件，就要为这个事情建个数据库。开发周期不可接受，性价比也低，通用性也差，无法和其他扩展联动。不会考虑建数据库。

既然用户选择了同时保留多个版本，那就请自己接受老版本一定会提示更新的结果。

**Comment by butaixianran** [comment]
改为增加个选项，让用户自己决定是否通过扫描文件来跳过老版本。

性能会非常底下，但用户可以自己选择接受这个结果。
