### ISSUE TITLE
功能请求：通过 PNG Info 辅助复现别人的生成效果

### ISSUE THREAD

**Issue by liasece** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#35]
增加通过hash搜索模型和lora的功能；

增加 PNG Info 中图片依赖的模型和lora的搜索和下载功能；

增加从 Copy Generation Data 中复制下来的文本反查所有依赖模型的功能；

这可以帮助我们复现别人的结果，让这个工具实用性更强

**Comment by butaixianran** [comment]
不打算实现。

prompt中嵌入的是模型文件名，不是模型id和hash。文件名不是查找模型的标准，是可以乱改的。

手动输入hash查找模型也不打算提供。hash是个机器用的id，不是最终用户能够在ui界面获取到的信息。没道理提供个输入框让用户来填入查找。

另外，不要把内容塞在标题里，请学会更成熟有效的发帖方式。

**Comment by liasece** [comment]
> prompt中嵌入的是模型文件名，不是模型id和hash。文件名不是查找模型的标准，是可以乱改的。

不是 prompt 中嵌的模型名，而是`Model hash`的值或者`AddNet Model`(不必，这是插件标准)中的hash：
```
Steps: 15, Sampler: Euler a, CFG scale: 8, Seed: 896492991, Size: 960x576, Model hash: 1c803ef2ca, Denoising strength: 0.46, ENSD: 31337, AddNet Enabled: True, AddNet Module 1: LoRA, AddNet Model 1: guo1.5(c97665df9b71), AddNet Weight A 1: 0.3, AddNet Weight B 1: 0.3, Hires upscale: 2, Hires steps: 10, Hires upscaler: Latent (nearest-exact)
```

> 手动输入hash查找模型也不打算提供。hash是个机器用的id，不是最终用户能够在ui界面获取到的信息。没道理提供个输入框让用户来填入hash查找。

整个webui不仅是用户使用，专业用户也会使用，他们知道机器用的id，对于专业用户没有这个使用壁垒。换句话说，普通用户也不理解模型id的概念。

> 另外，不要把内容塞在标题里，请学会更成熟有效的发帖方式。

感谢提醒。我的问题是把3个issues合成了一个。不过如果标题中没有内容如 _增加功能请求_ 然后在内容里列出三个请求，那也是不成熟的发帖方式。

**Comment by liasece** [comment]
多说一句。目前使用 Civitai 的一个痛点是想要复现别人的效果有点困难，如果别人使用了很多的额外模型就会更加困难。如果我们从Copy Generation Data拿到的信息不足以找到对应的lora或者模型，那可以提示出来。

简单来说，这里提出的需求是：在 Civitai 范围内指导你想复现别人的效果缺少什么模型，如果Civitai上能找到的话应该去哪下。

**Comment by butaixianran** [comment]
你的意思是，你就拿到了一张网上的图片，这个图片根本不是在civitai网站上。但是还是希望就凭借图片中的model hash，去看civitai有没有这个模型？

这个是不行的，civitai查找模型，用的是sha256。SD webui的模型hash，不是SHA256，而且算法每隔一段时间还会换一次，它的hash不能作为标准，一个一直换的hash，一点价值都没有。

这个图片中，如果有model hash，就一定会有模型名字。你可以用模型名字去civitai搜索。

**Comment by liasece** [comment]
> 算法每隔一段时间还会换一次

这我倒是不知道。。如果我们工具去辅助搜索，以建议的方式提供 civitai 上找到的结果，会不会有价值呢？我也在尝试写这个工具。

**Comment by liasece** [comment]
https://github.com/civitai/civitai/wiki/REST-API-Reference#get-apiv1models-versionsby-hashhash

从这里的解释看，他们支持多种 hash 算法，只要 sd webui 不超出这些算法的范围是不是还是有机会实现的。sd webui 那边这种破坏性的改动应该也不是经常性的。

**Comment by butaixianran** [comment]
SD webui修改hash算法，100%还会有下一次。我不可能因为一个人心血来潮换算法，我就一直跟着它去改。

为什么它一定还会换，因为SD webui它是先算出一个唯一hash，然后从这个hash里面，截取一小段，作为填入图片的模型hash。也就是说，多个模型，这个hash实际上可能是完全一样的。

这就像是身份证号码，每个人身份证号码，本来都是唯一的。但是，现在他只截取前面8个数值，当作编号，你想想有多少人会是一样的号码。

**Comment by liasece** [comment]
这没关系的。civitai 的接口也是通过这前半部分搜索的如[这样](https://civitai.com/api/v1/model-versions/by-hash/a074b8864e)。即使是完整的hash也不是唯一的。我们只需给个建议，缩短问题到答案的时间。

**Comment by butaixianran** [comment]
这个插件，需要你本地已经有模型了，再去把本地模型，和civitai的信息对应上。

如果你本地没有模型，这个插件，把模型信息，和什么东西对应呢？

你的需求实际上是，你想要在civitai网站上找模型，只是用模型hash去找。那你直接把这个hash，填入civitai网站的搜索框不就行了吗？

**Comment by liasece** [comment]
那我可能对这个插件有误解。

我觉得它是一个辅助工具，作用是缩短我们做重复劳动的时间。即使没有它，我同样能用你说的方式去civitai一个一个把信息捞下来。

如果你不认为这是这个工具该做的事，那就做你认为正确的事吧。我会去在个人分支开发，到时候如果这个工具能接受我的合并请求我会很开心。

谢谢你的回复。
