### ISSUE TITLE
Suggestion/Request

### ISSUE THREAD

**Issue by LumberingTroll** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#36]
First, thank you so much for making this!

1) If possible it would be amazing to be able to add custom tags to our TI, Ckp, Lora, HN, etc. so that I could say add a "Character" tag to all my character/person based Lora and easily find them, same for Styles, Helpers, Negatives, Utilities, etc.! 

2) The ability to store a note that we could put in our trigger words and used prompts for quick reference on each of these it would save a lot of moving between documents / sites and looking up stuff making the entire workflow faster.

3) Download updated models/lora/embeddings without having to manually go to the site to download them, and also the option to delete old models automatically. 

4) NSFW toggle on the main WebUI that will filter out all NSFW when its on. (some times I want to show people things, but dont want those visible, my kinks are my own :P ) 

Again I really appreciate your efforts and if these requests are not possible I understand.

**Comment by butaixianran** [comment]
This is a Civitai extension, not a everything extension.

Local model and image management is not a Civitai feature. They should be done in another extension.

But, about your first request, you can create subfolders in your model folder, then put different model in different subfolder.

Like one for cartoon, one for photoreal. This is an extra network's buildin feature

**Comment by jokker87** [comment]
@MrKuenning Here's a first somehow working version with that feature. I tried to implement it in the base code of this extension, so that you get the best of both ;)

**Comment by Blackened15** [comment]
Dont wanna create another "issue" thread for a suggestion.

A "Use SFW images on mixed/NSFW model when possible" or something like that would be useful, so it default to using safe for work image preview on model that have both type of image, but still use an NSFW image when thats all thats available.

Also thanks for the extention, saving me hours of work!

Right now I achieve this by scanning without the skip NSFW Preview Image, manually going through the mixed model, deleting the preview and info, and rerunning with the skip option, so it downloads the SFW image on those, while still generating preview on NSFW model

**Comment by butaixianran** [comment]
Check this new extension:
https://github.com/butaixianran/sdweb-easy-prompt-selector

**Comment by butaixianran** [comment]
> dont know if that reply was meant to me or in general, but I just wanted to clarify and simplify my suggestion.
> 

Above new extension is not for your request. There will be no more new feature in v1.x as document says. Your above request will be added to 2.0

**Comment by Blackened15** [comment]
cool, great work so far

**Comment by LumberingTroll** [comment]
> Check this new extension: https://github.com/butaixianran/sdweb-easy-prompt-selector

Thats awesome! thanks a lot!
