### ISSUE TITLE
Default view for Extra Networks if is thumbs，one click to at <lora:loraname:multiplier> and tag.

### ISSUE THREAD

**Issue by xueqing0622** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#38]
Very good plug-ins, Setting of Default view for Extra Networks usually in the card mode, take up a lot of computer screen space. I like to switch to the thumb mode, which is easier to see the overall situation, hope in the  thumbs mode，one click to create prompt "<lora:loraname:multiplier> and tag" will be better choose。

很好的插件，通常card的模式下，会很占电脑屏幕空间，影响工作效率，我喜欢切换成thumbs模式，更容易看全局，希望在thumbs模式加入点击一次生成"<lora:loraname:multiplier> 和 tag"

**Comment by butaixianran** [comment]
已经有很多人提过了，本地开发已经完成了，还没有更新到github，会等其他功能完成后一起作为v1.5版再更新。

**Comment by xueqing0622** [comment]
好的，非常感谢，已经很够用了，大大加快的工作进度。

**Comment by butaixianran** [comment]
已完成，检查更新。更新后关闭SD重开，光是Reload UI对本插件无效。

**Comment by xueqing0622** [comment]
已经用上了 好用 感谢感谢
