### ISSUE TITLE
更新的时候是否可以有log，这样旧的就不用重新扫描或者跳过，不然重新加进几个后又扫描的话时间太久了，一个一个更新又麻烦

### ISSUE THREAD

**Issue by xueqing0622** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#40]
更新的时候是否可以有log，这样旧的就不用重新扫描或者跳过，不然重新加进几个后又扫描的话时间太久了，一个一个更新又麻烦 advntr.civitai.info和preview.png如果发现lora或者embedding文件旁边有这两个文件也可以直接跳过，

**Comment by butaixianran** [comment]
这个log有什么作用呢？他能保证，这些模型在civitai上都没有新版本？

一个模型是否有新版本，完全是由civitai一侧决定的。本地log没有办法判断一个模型是否存在新版本。

问题是，你为什么要在短期内重复扫描呢？

既然你已经扫描过一次了，你愿意更新的都更新了，不打算更新的，重新扫描了也不会去更新。接下来你再下载模型，也都是最新的版本。为什么还要频繁扫描更新呢。

**Comment by xueqing0622** [comment]
好的，感谢！很好的功能了，实验了一下，是我下载的lora的问题，有些lora会这样，抱歉我的错
很好的插件！ 工作流真的好用！
