### ISSUE TITLE
[Feature Request]: Option to select which model types to scan

### ISSUE THREAD

**Issue by freecoderwaifu** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#43]
This is a good extension especially for fetching thumbnails. However it would be cool if the main Scan button had an option to select which types of models to scan: checkpoints hypernetworks, embeddings and/or Lora. 

Currently it scans everything, which can be slow especially when scanning lots of checkpoints. If you only need to scan Lora for example and don't really need to scan for checkpoints, you have to wait for the scan to process checkpoints first, unless you move their folder back and forth after processing what you only need to scan.

A row of checkboxes to enable/disable the types of models to scan, or even a dropdown to select which type would speed up the scan.

**Comment by butaixianran** [comment]
It only scan once, and checkpoint need information too.

**Comment by freecoderwaifu** [comment]
Yes, but what if a user doesn't want to scan checkpoints at all and only wants to scan Lora?

**Comment by butaixianran** [comment]
ok, it is not much work if I don't need to save this setting.

I'll set default value as all selected and won't save it to setting file. But you'll have a checkbox group like the checking update section.

**Comment by freecoderwaifu** [comment]
Sounds good, thank you.

**Comment by butaixianran** [comment]
done, update your version. Re-launch SD after updating, just reload ui won't work.

**Comment by freecoderwaifu** [comment]
Works perfectly, thank you again!
