### ISSUE TITLE
'Use Prompt from Preview' apply all meta data settings.. or add 'send to PNG Info" ?

### ISSUE THREAD

**Issue by DreamOfGit** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#47]
The 'Use Prompt from Preview" rarely reproduces the image it was aiming for since it doesn't apply any settings related to Height / Width / etc..

Maybe this is out of scope and the goal of the button was only to generate a prompt that works for X network?
If so, could we have a way to chuck the preview image in PNG Info?

If you think either of these are out of scope - just close the issue.

Thanks - This extension has been a life saver, the Quality of Life time saving it's done is immeasurable.

**Comment by butaixianran** [comment]
apply setting is not supported for now.

But the main reason you can not get a similar result as preview image, is in the preview image's prompt, it often uses a different lora name from your local lora file name.

so, you actually do not use that lora if you just use the prompt from preview.

solution is simple, just click model card to add your local lora into prompt. Then even you don't use the same setting, you still can get a similar result.

also, you can set lora weight to 0.7 as default in SD webui's setting page, which almost works on every lora

**Comment by DreamOfGit** [comment]
I'm saying it's the Width / Height -  CLIP SKIP & Ensd Overrides, CFG / etc..

Basically all the non-prompt customizations mean an identical prompt with all the Lora / TI's / Hypernetworks in place and on the same Model - still creates a completely different image.

Without all the options being resolved from the meta information, the prompt may generation something good but not what your preview was.

Either way, sounds like it's not something your looking to do. Thanks for your time.
