### ISSUE TITLE
[enhancement] ModelGalleryMaker with civitai-helper

### ISSUE THREAD

**Issue by cibernicola** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#48]
I am creating a template (simple but functional) to generate the gallery for each model on the local computer. I think it is very interesting to have the maximum of information of each one in local and not to depend on connection to the web to consult it.
I think it could be introduced in civitai-helper and if you like, optimize the use of the models.
An example: 
![image](https://user-images.githubusercontent.com/4579387/224947611-1c29446c-b55c-4a6c-98b2-91d88c737b54.png)

**Comment by butaixianran** [comment]
ok, I've already started to design something similar for 2.0.

Is this UI in SD webui? Or it is a stand alone tool?

**Comment by cibernicola** [comment]
its pure html+css+js using jinja2 template

**Comment by butaixianran** [comment]
ok, a template engine is not the way I'll choose. And out of SD webui is also not an option for this extension.  

I don't want to make this extension need to install any more package. Also, server side rendered template is not a good choice here. A lot of data need to be loaded and adjusted at client side. 

Just display model information as static html is not v2.0's target. Which already can be easily achived by opening civitai's url. A different css style from civitai won't help too much.

Thanks for your show case, I'll leave your css style as a reference.

**Comment by cibernicola** [comment]
Well, all your opinions are fine, but far (really far) from all use cases
Open external sites allways is a bad idea as a concept, cos u may need to check something and site may be down.
Is a gallery with static content, displayed using a practical way, I will have a "notes" part, and ofc it will be integrated under WebUI, the idea was to use it as a "plugin" of your extension :D an extra option in order tu cover all use cases, wich are huge.
And, again, I can integrate te output in Gradio, but again, I think is a bad idea, but this is under my limited knowledge.

**Comment by butaixianran** [comment]
Thanks, you know, you can always create your own extension or SD script for this and offer it to public. You almosted finished everything, just add a button to sd as a trigger.
