### ISSUE TITLE
1.按过自带的add network刷新按钮后（且真的有内容更新的话），刷新c站助手按钮似乎无效了；2有些lora作者发布了多个格式的版本，不是默认版本就不会下到预览图

### ISSUE THREAD

**Issue by daxijiu** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#49]
1.按过自带的add network刷新按钮后（且真的有内容更新的话），刷新c站助手按钮似乎无效了；
如果自带的刷新且有内容更新（无内容单纯按没事），c站助手那些按钮会消失了，点刷新c站助手按钮也无效

2有些lora作者发布了多个格式的版本，不是默认版本就不会下到预览图
比如https://civitai.com/models/13941
v2这个版本右侧下拉如果选pickleTensor就能下到预览图，如果选了不是默认的，比如safeTensor就不行

**Comment by butaixianran** [comment]
1. 基本可以确定，你用的国内打包的中文汉化版。查看中文文档，常见问题部分，有个由汉化造成的问题。给你汉化的那个人，手动修改了SDwebui的源代码，所以导致了你的问题。

2. 你描述的是，同一个版本中的多个文件，这不叫多个版本。
对于这种情况，是的，只有默认的文件能下载预览图。因为只有默认的文件，能取到版本id。同一个版本下的其他文件，在civitai的API上，都是取不到id的，所以取不到预览图。

**Comment by ShinaPig** [comment]
> 汉化原因
> 这个插件，需要在模型卡片上，找到一段叫 "replace preview" 的文字。这段文字，是不会被汉化插件汉化的，SD webui 的多语言接口，也不会汉化这个地方。所以，按道理是一定能找到的。
我使用的这个[汉化扩展](https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN)是会汉化这个地方的。

**Comment by butaixianran** [comment]
已更新新版，已经适应多语言，检查更新

**Comment by butaixianran** [comment]
不支持那个双语插件，请换用普通汉化插件。
