### ISSUE TITLE
为啥不能通过URL安装

### ISSUE THREAD

**Issue by akio1321** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#5]
我看英文的README有通过URL安装的。

但是安装报错
GitCommandError: Cmd('git') failed due to: exit code(128) cmdline: git fetch -v origin stderr: 'fatal: unable to access 'https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/': OpenSSL SSL_read: Connection was reset, errno 10054'

**Comment by butaixianran** [comment]
这是你的网络连接问题，和本程序无关

**Comment by akio1321** [comment]
好吧，抱歉

**Comment by butaixianran** [comment]
这个不是浏览器报错，是你的git命令工具报错。你的git网络连接没有配置好。
