### ISSUE TITLE
Suggestion/Request ：add a custom directory box to detect model updates, upgrades, previews and information downloads.

### ISSUE THREAD

**Issue by PuDood** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#53]
Perhaps you can add a custom directory box to detect model updates, upgrades, previews and information downloads. This is of great significance to people who have less storage on a single disk and more than one disk. For example, one of my disk programs is SD, including models (which have occupied most of the storage), and the other disk is used to download and store new models and infrequent models，So every time I download preview images and updates, I need to transfer them. I hope you can see my suggestions. Thank you for your plug-in. It is really very practical

**Comment by butaixianran** [comment]
It will download new version to the same subfolder as your old version of that model.

If you want to put them in another disk, just put your old version of that model to another disk.

**Comment by I-ShadowStar** [comment]
I would like to refine the request. I am using another extension that downloads an extensive list of TIs that are mostly sourced from CivitAI. The files are placed in a subfolder of the extension's folders, and that is not being scanned by the CivitAI Helper extension. Would it be possible to just add a simple option to 'Scan these additional directories:' ?

**Comment by butaixianran** [comment]
SD webui has command arguments can use custom model folder. 

And this extension supports those command argument.

Search "--embeddings-dir"  in Google for tutorial.

Also, check SD webui's wiki for other command arguments.
