### ISSUE TITLE
Close button is missing

### ISSUE THREAD

**Issue by jingo69** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#54]
Hi, I think after a recent update, the close button is missing, so the Civitai-Helper interface cannot be closed.
![Screenshot 2023-03-16 175304](https://user-images.githubusercontent.com/115148876/225709608-f031bfce-b5e8-4a64-a536-5278041ee6ac.jpg)

**Comment by butaixianran** [comment]
this is a new setting by SD webui, there is nothing to do with this extension.

You can click the extra network's icon Again to close it, so this button is no need and they removed it.

**Comment by silverrowan** [comment]
> 

having a close button at the bottom would be great -- there's a lot of scrolling if you have absurd numbers of models!

**Comment by butaixianran** [comment]
Like I said, it is removed by SD webui's team in the latest version.

Ask that in SD webui's issue list.

**Comment by butaixianran** [comment]
What you mean "folder selection list to the top"? There is no such thing as "folder selection list" in this extension.

If you are asking features of extra network, ask them in SD webui's issue list. Extra network is not created by this extension, it is a build-in feature of SD webui, this extension just added another 3 buttons onto its cards.
