### ISSUE TITLE
Scan Behaviour Unexpected - feature request I guess?

### ISSUE THREAD

**Issue by silverrowan** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#55]
When using Scan Models for Civitai there's a few behavioral quirks that are annoying - not a big deal, and there are workarounds, they're just time consuming.

Scan will overwrite images that I've changed in photoshop, back to the replaced main image, but it WONT replace ones I saved and generated directly in A1111 (!??). Its annoying but work-around-able, as my ideal is actually the reverse situation for most models!
---->I'd greatly prefer to be able to choose to replace (or not) the info/images for models that already have info/images on a per model basis, and have the option to scan only models that have no info/images, like the "only show models have no info" toggle under "Get Model Info from Civitai by URL" 

It would also be nice to be able to be able to choose which of the demo images would be best, on a per model basis if the default one is less than helpful after cropping.

When "skip NSFW Preview images" is ticked, it does not check the next image is SFW, but just stops, and at least occasionally there's SFW images behind the NSFW previews. I don't know how N/SFW is implemented in civitai backend so no idea if its doable/reasonable.

**Comment by butaixianran** [comment]
hi, scanning will not overwrite any image at all.

It will check if the file name model_name.preview.png is already there, if there is, it will skip it and go to next model.

So, which version of this extension are you using? Check the version number at the bottom of extension's tab

This extension also will check all NSF image and download the first one it can find.
But an image you think is SFW, is not what civitai thinks.
A lot of SFW image in a human's view, is set as NSFW in civitai. That is how today's NSFW checking works, it has its own standard.
