### ISSUE TITLE
疑似bug反馈

### ISSUE THREAD

**Issue by minecraftyusei** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#57]
下载lora时的进度条现在非常诡异，如图，它似乎是不停的在cmd中创建新进度条而非在原进度条上更新状态。
![2023-03-18](https://user-images.githubusercontent.com/39985294/226083487-24b65ba6-8c5b-4a15-b5ae-cca87d13323e.png)

**Comment by butaixianran** [comment]
我这里没有这种问题，有截图吗？

你要知道，这是单任务的，不能多任务同时运行。下载完一个，才能下另一个。

**Comment by minecraftyusei** [comment]
大概就是这样的情况，随便选了一个Lora做下载对象




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
我这里没有这种问题，有截图吗？
 
你要知道，这是单任务的，不能多任务同时运行。下载完一个，才能下另一个。

**Comment by minecraftyusei** [comment]
我录了一个下载全过程的视频，但是被QQ邮箱退回了邮件（对方的服务器不支持接收）。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
我这里没有这种问题，有截图吗？
 
你要知道，这是单任务的，不能多任务同时运行。下载完一个，才能下另一个。

**Comment by butaixianran** [comment]
你运行单任务也是这样吗？你的截图看起来象是同时在下载多个任务的现象

**Comment by minecraftyusei** [comment]
我录了个操作过程的视频，但是发不过去（github估计是接收不了视频），能丢个邮箱或者能接收视频的方式给我吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上8:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
你运行单任务也是这样吗？你的截图看起来象是同时在下载多个任务的现象

**Comment by butaixianran** [comment]
这不需要发视频，你只需要回答关键问题就行了：
是否是多个任务同时下载？
是否是远程查看命令行窗口？

**Comment by minecraftyusei** [comment]
都不是




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
这不需要发视频，你只需要回答关键问题就行了：
 是否是多个任务同时下载？
 是否是远程查看命令行窗口？

**Comment by butaixianran** [comment]
这个事情是这样，代码上，进度条就2行代码，没有换行符，用的行内输出命令，所以一定会显示在同一行。

除非，有什么工具，替你接收了真实的命令行输出内容，然后再一行行的刷新出来给你。就像是在远程访问别的电脑上的命令行窗口那样。


所以，你可以回忆一下，你这边到底是有什么东西可能做这种事。如果你想不到，我也无能为力了，因为代码上是没有毛病的。

**Comment by minecraftyusei** [comment]
我用的整合包哇。。星空的整合包+秋叶启动器，而且我自己没做过也没那个代码能力去改动整合包。有没有这种工具我是不得而知了。。。
等等看其他人会不会反馈同样的问题吧，我想像我这么用WEBUI（整合包+启动器）的人应该很多


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
这个事情是这样，代码上，进度条就2行代码，没有换行符，用的行内输出命令，所以一定会显示在同一行。
 
除非，有什么工具，替你接收了真实的命令行输出内容，然后再一行行的刷新出来给你。就像是在远程访问别的电脑上的命令行窗口那样。
 
所以，你可以回忆一下，你这边到底是有什么东西可能做这种事。如果你想不到，我也无能为力了，因为代码上是没有毛病的。

**Comment by butaixianran** [comment]
你是mac系统吗

**Comment by minecraftyusei** [comment]
Windows系统，使用整合包（秋叶+星空），整合包除去它的初始配置外只额外加了这一个插件（我看了看整合包已有的插件，也只是一些诸如controlnet之类的功能辅助插件而已）
在此附上启动整合包的cmd加载窗口。（以及我又试着下载了一个lora）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月19日(星期天) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
你是mac系统吗

**Comment by minecraftyusei** [comment]
另附上pip list的结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "butaixianran/Stable-Diffusion-Webui-Civitai-Helper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月19日(星期天) 中午11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper] 疑似bug反馈 (Issue #57)





 
你是mac系统吗

**Comment by butaixianran** [comment]
windows系统没道理，没有第三方工具修改命令行的话，是不可能换行的。这个你想不到可能原因，我也无解了。

**Comment by vanton** [comment]
这是使用了第三方启动器造成的问题，比如bilibili某人做的那个启动器，他会启动一个自定义的 console，而那个 console 并不标准。

使用 webui-user.bat 启动不会有这个问题。

**Comment by butaixianran** [comment]
那我就当这个问题解决了，关了
