### ISSUE TITLE
Feature Request: Add Toggle to Blur NSFW Thumbnails

### ISSUE THREAD

**Issue by Isaiahfeldt** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#61]
Would nice for there to be a setting that would let the user blur thumbnails for NSFW Civitai content.

**Comment by RTX10086** [comment]
I have the same suggestion. Since I'm blurring the NSFWs manullay now. Would be great if there is a switch for blurring, just like the one on the Civitai website.

**Comment by butaixianran** [comment]
This is not a civitai feature, you should ask this in SD webui 's issue list.

Extra network is SD webui's build-in feature, this extension just added another 3 buttons to its cards.

**Comment by Isaiahfeldt** [comment]
> I have the same suggestion. Since I'm blurring the NSFWs manullay now. Would be great if there is a switch for blurring, just like the one on the Civitai website.

I've gone ahead and posted a feature a request on the correct github, you may find it [here ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8739)if you'd like to help give your input.
