### ISSUE TITLE
[BUG] [100%复现] 不支持带有"&"的路径

### ISSUE THREAD

**Issue by RTX10086** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#62]
我的LoRA下有一个子文件夹命名为了`Scene&Style`，使用本Civital插件的预览图按钮获取该子文件夹下的`.info`文件，以使用触发词自动填充、网页链接跳转时，就会报以下错误（我这里通过省略号省略了路径前半部分）：

```
Civitai Helper: Can not find model info file: C:\……\Scene&amp;Style/gachaSplashLORA.civitai.info
Civitai Helper: Failed to get model info for lora /Scene&amp;Style/gachaSplashLORA.safetensors
```
但是实际上，`.info`文件就在该文件夹下。

我发现`&`被转义为了`&amp;`，所以我试着把路径从`Scene&Style`改为`SceneANDStyle`避免符号转义后，就瞬间一切正常——可以通过按钮调用提示词、跳转网页了。改回到“&”就又不行了

这可能印证了是这个字符转义导致的问题

**Comment by butaixianran** [comment]
是的，请不要使用特殊字符。

**Comment by RTX10086** [comment]
> 是的，请不要使用特殊字符。不打算做额外优化，请改名吧。这种目录很多的话，网上有批量改名工具

好吧，我在想是否可以至少在`README`中添加“本插件不支持含有特殊字符的路径”的警告提示，防止后来的朋友再遇到这个问题

**Comment by butaixianran** [comment]
不用了吧，不会有几个人把&符号放在文件名里的，各种程序都会出错，这是全平台的通用规则，不需要一个小插件再去提醒。
