### ISSUE TITLE
Feature Request: Store the descriptions of the model inside the .info file

### ISSUE THREAD

**Issue by SeverianVoid** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#65]
Would be nice if you could include in the .info file and then displayed somehow on the extra networks page, maybe a button you hover over or something the written descriptions that authors of models and files on civitai provide, since quite frequently they include a lot of details about how the models work or extra steps you might need which aren't then available anywhere else.

The button to open the page the model was from is convenient to get there, but sometimes I have found that to not work and it doesnt actually open any page to the model and I am almost always opening it just to check the description

**Comment by butaixianran** [comment]
saved description won't be updated, just click url button to open civitai model's webpage

**Comment by SeverianVoid** [comment]
And what happens if the model is removed from the site? That description would then no longer be available on the page, another reason why storing the model description in the .info file would be beneficial. The number of model uploaders who use the description for extra information is just too much to not include it in the model info file I think.

**Comment by SeverianVoid** [comment]
As for the model link not working, the error I get is

![image](https://user-images.githubusercontent.com/5420686/226727820-49646d98-f971-4456-b98f-feffa7e2d805.png)

> Civitai Helper: Load model info of  d3c225cbc2e0ed3ac8032e05e6fabe5acfe81e2e3d18e23389e84b9cb5ce127f in ckp
> Civitai Helper: Can not find model info file: F:\Neural_Networks\Automatic1111_Git\stable-diffusion-webui\models\Stable-diffusion\ d3c225cbc2e0ed3ac8032e05e6fabe5acfe81e2e3d18e23389e84b9cb5ce127f.civitai.info
> Civitai Helper: Failed to get model info for ckp  d3c225cbc2e0ed3ac8032e05e6fabe5acfe81e2e3d18e23389e84b9cb5ce127f

For whatever reason its trying to use the model hash as the name of the . info file. The info file exists right next to the model and has all the correct information in it, but the web link button doesn't work since its trying to call for the info file using the hash instead of the model name

![image](https://user-images.githubusercontent.com/5420686/226727587-3e4a1dbd-552b-42f1-8963-81bf8afdc712.png)

**Comment by SeverianVoid** [comment]
Just did a bit more testing, and with Lora, TI and Hypernetworks I had no issues loading the model page using the button and the output in the console looks like I would expect calling for the model name

![image](https://user-images.githubusercontent.com/5420686/226730942-f540a7bb-8f45-40eb-8950-cbdad63f2223.png)

So it only seems to be affecting the checkpoints section of the extra networks page, and it seems to happen with every single checkpoint I have tried, as they all show up in the console window looking for the hash value

**Comment by butaixianran** [comment]
ok, the error msg you are looking at, is actually a wrong msg. **The function works right, but print out wrong msg when you opening a checkpoint model's url.** 

I downloaded the "/comicDiffusion_v2.ckpt" model you mentioned here, and can open its url corrrectly without any issue.

The reason your extension can not find this model info, is somehow, your SDwebui's build-in extra network, can not get this model's name. 

For this model, SDwebui should have a string like this saved in its model card:  
`/comicDiffusion_v2.ckpt d3c225cbc2e0ed3ac8032e05e6fabe5acfe81e2e3d18e23389e84b9cb5ce127f`  
As you can see, it's this mode's file name + hash code.  

Then this extension, will get the file name part and use that to get model info file. But, it will print file name + hash code in console log window. So, it does the right thing, but print out wrong msg.   

But somehow, your error msg tells me, your SDwebui can not read this model's file name. In your SDwebui, this hidden string is saved as:  
` d3c225cbc2e0ed3ac8032e05e6fabe5acfe81e2e3d18e23389e84b9cb5ce127f`  
As you can see, there is no file name in it. That's why this extension can not find its model info file.  

So, you need to find out why your SDwebui can not read this model's file name. 

Again, this model works fine, I can click open url button and open its civitai page without any issue. So, you need find out what you did to make your SDwebui can not treat it right.

**Comment by SeverianVoid** [comment]
All the model files are located: stable-diffusion-webui\models\stable-diffusion
All the LoRas are in: stable-diffusion-webui\models\LoRA
All the hypernets are in: stable-diffusion-webui\models\hypernetworks
and the TI are in: stable-diffusion-webui\embeddings

The stable-diffusion-webui folder is on a local SSD internal hard drive. So the full path to the checkpoint folder looks like this
F:\Neural_Networks\Automatic1111_Git\stable-diffusion-webui\models\stable-diffusion
![image](https://user-images.githubusercontent.com/5420686/226748034-adfd246e-7c2a-4fd5-b898-1e9cc5abb18e.png)

All the model checkpoints show up in the extra networks tab, they scan using the extension just fine and every single one has a .info file and preview file. I even deleted every single .info file and hit the scan button on the extension tab and it recreated them all perfectly fine you can see the dates for those are all moments ago. Clicking on the model in the extra networks tab also correctly causes the model to load. 

![image](https://user-images.githubusercontent.com/5420686/226747368-d377ba4c-597e-49c0-973f-35b45bba7c41.png)

Is there a file somewhere that stores the SDwebui extra network data that might have gotten screwed up somehow?
I checked and both the extension and the webui are fully updated with git pulls

**Comment by butaixianran** [comment]
hi, there is nothing to do with this extension about this issue.   

You see, the string is saved by SDwebui, this string's name is called "search_term". It is created by SD webui, and saved into every model card by SDwebui's extra network.  

This extension can only read it. So, no matter how you delete or re-scan models, won't change anything. Your SDwebui is the issue here.  

You need to figure out, why your SD webui can not create it right. One thing you can try is, **Every time you change something then click "Refresh" button, it will re-create this string again.**  So, you can remove or change any checkpoint model's preview image, then click "Refresh". After that, try to open its url, see if it works again.   

Also, you need to find out if only this model has this issue, or, all checkpoint models has this issue. Lora won't have this issue, only checkpoint models.

**Comment by SeverianVoid** [comment]
I tried duplicating one of the model checkpoints and changed its name, re-scanned with the extension and it loaded up correct previews and .info file from the website identical to the model I copied, refreshed the extra networks list, and I get the same results still the copied model also brings up the hash being used instead of the model name.
![image](https://user-images.githubusercontent.com/5420686/226751839-6646b876-c74e-4825-a2fa-476fc44eb7cf.png)

Its happening with every single checkpoint model in the extra network panel not just the one model

I will try disabling extensions to see if that is what might be causing issues.

**Comment by butaixianran** [comment]
OK, here is a way you can directly see this "search_term" in your web page. 

Right click a checkpoint model card, select "Inspect Element" from the menu.  It will open it's html code page.

Spread the "div" card node, until you find "search_term" node. You'll find the string there.  

You need to check if file name is in it.  It should be file name + hash code. Like following.  

![search_term](https://user-images.githubusercontent.com/5558722/226754683-dd7a9aef-2b8a-40fe-8df5-16a1d269b7d7.jpg)

**Comment by SeverianVoid** [comment]
I have disabled every single extension apart form the civit helper extension and then restarted the entire thing not just reloading but closing the command window and relaunching the webui-user.bat, issue remains.

I pulled up the html like you showed and it doesn't seem to have the same format of information in the search term just the hash value with no quotations or file name. It seems like the other url lines in the class style are also slightly different?

![image](https://user-images.githubusercontent.com/5420686/226755633-f7b3287b-a4f4-47e1-b05a-e85621031012.png)

**Comment by butaixianran** [comment]
You did very well, you proved there is no file name in your model's search_term. 

That mean's 2 things:
* You are using an old version of SD webui, but you think you are using the latest version.
* or, you find a bug of SD webui.  

Here is something gonna help you:

Go to bottom of SDwebui's page, there is a commit number. that string, is a url. Copy the whole url to here. We'll see which version of SD webui you are really using.  

Or you can submit a bug to SD webui's issue list, with above sceenshot, ask them why there is no file name in your search_term

**Comment by SeverianVoid** [comment]
When I launch the webui

Commit hash: a9fed7c364061ae6efb37f797b6b522cb3cf7aa2 
![image](https://user-images.githubusercontent.com/5420686/226759285-0d356d06-f9d2-47f1-9c29-8e44a9b5d256.png)

From the bottom of the page
![image](https://user-images.githubusercontent.com/5420686/226759454-d1a7d107-9636-428c-a5dd-2c41283240e8.png)

**Comment by butaixianran** [comment]
ok, good news is you are using latest version of SD webui. 

Bad news is, that means this is a bug of SD webui. 

In SD webui, it uses following code, to get the file path and put it into search_term:
```python
    def search_terms_from_path(self, filename, possible_directories=None):
        abspath = os.path.abspath(filename)

        for parentdir in (possible_directories if possible_directories is not None else self.allowed_directories_for_previews()):
            parentdir = os.path.abspath(parentdir)
            if abspath.startswith(parentdir):
                return abspath[len(parentdir):].replace('\\', '/')

        return ""
```
So, following line, is the reason, your search_term doesn't have a file name:
`if abspath.startswith(parentdir):`

In this line, `abspath` is your model's full path. `parentdir` is your model folder. But in your SDwebui, it thinks your model is not in a model folder SDwebui allows.  

So, it won't add the file name into search_term.  

Yes, a command line arguement can cause some trouble. If you are using some comannd like "--data-dir", you better remove them. 

Still, this should never happen, so, it is a bug of SD webui.

**Comment by butaixianran** [comment]
There is a way to help you find out which folder name caused this, if SDwebui's team won't help you.

Open `your SDwebui/modules/ui_extra_networks.py` as txt. Go to line 59.

Change line 59 and 60, from this:
```python
            parentdir = os.path.abspath(parentdir)
            if abspath.startswith(parentdir):
```
To this:
```python
            parentdir = os.path.abspath(parentdir)
            print("model abspath: " + abspath)
            print("model parentdir: " + parentdir)
            if abspath.startswith(parentdir):
```

Then re-launch your sdwebui, go to extra network's checkpoint model page, and view console log's output, to find out which folders are allowed, and why your model is not in one of those folders.

**Comment by SeverianVoid** [comment]
Changed those lines of code to what you had, relaunching in the console this is what it shows now.

![image](https://user-images.githubusercontent.com/5420686/226766715-ee870f02-d209-4df1-bfb6-42e62a0ca098.png)

So I have no idea whats going on.

I just started a full fresh install of the webui to a new location on the same drive in the hopes that if it is a configuration issue or some setting that is breaking things that it wont show up in a fresh install

**Comment by butaixianran** [comment]
Your screenshot already shows the reason, one path is "stable", the other is "Stable", "s" is different in these 2 paths.

![Snipaste_2023-03-22_08-49-01](https://user-images.githubusercontent.com/5558722/226773658-94e2cf5e-af5e-46c3-8e1a-53aedc08fabc.jpg)

**Comment by SeverianVoid** [comment]
So I just checked, and in the install the folder is all lower case...
![image](https://user-images.githubusercontent.com/5420686/226777026-5ca8c0d0-64e7-4075-b9af-7c7c5199e6a4.png)

**Comment by SeverianVoid** [comment]
Greatly appreciate your help in figuring out what was going on, never would have figured out that letter case of the model folder is what was causing the problem.

I do still think that storing the model description as a part of the .info file would be a good thing to have in the event the model is removed from civitai, or if the civitai site is down. 

Even if there is no way to display it in the webui, just having it in the .info for record keeping would be enough.

**Comment by butaixianran** [comment]
Model folder's name must be exactly the same as official github project. 

Search term is used by extra network, so, there would be something failed when using extra network, you just didn't notice that. When it failed, it didn't tell you.

And download description's feature will not be added. Just open civitai's url. 

This request is closed.
