### ISSUE TITLE
不支援下載 21291/anifantasyfor-testing

### ISSUE THREAD

**Issue by bluelovers** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#66]
not support 

![image](https://user-images.githubusercontent.com/167966/226831346-f3e810f8-b77a-4999-b2a0-794ea6c84286.png)

https://civitai.com/models/21291/anifantasyfor-testing

只會下載 VAE

**Comment by butaixianran** [comment]
是的，当同一个版本中，有多个文件的时候，默认只下载第一个文件。不支持手动选择文件。大部分时候，第一个文件是模型，偶尔会有第一个文件是vae或配置文件的情况。

**Comment by butaixianran** [comment]
civitai的API服务只提供了一个文件的下载链接，其他文件未提供，因此无法解决而关闭
