### ISSUE TITLE
插件导入冲突

### ISSUE THREAD

**Issue by sdbds** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#67]
和另外一个插件dumpunet冲突，
from modules import script
from scripts.lib import xxx
同时读取script.lib下的文件，导致另一个没法用。(因为C在D之前，所以这边正常用)
已经给那边提了issue
[stable-diffusion-webui-dumpunet](https://github.com/hnmr293/stable-diffusion-webui-dumpunet/issues/2)

**Comment by butaixianran** [comment]
已解决，检查更新
