### ISSUE TITLE
Support for proxies

### ISSUE THREAD

**Issue by OedoSoldier** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#69]
## Describe Issue
Need support for proxies to access Civitai

**Comment by butaixianran** [comment]
use global proxy to your system

**Comment by anfp** [comment]
set global proxy on Mac doesn’t work

**Comment by butaixianran** [comment]
> set global proxy on Mac doesn’t work

Really?
https://www.serverlab.ca/tutorials/osx/administration-osx/configuring-a-network-proxy-for-osx/

I find this reasult in 3 seconds

**Comment by anfp** [comment]
> > set global proxy on Mac doesn’t work
> 
> Really? https://www.serverlab.ca/tutorials/osx/administration-osx/configuring-a-network-proxy-for-osx/

tried, no luck

**Comment by butaixianran** [comment]
> tried, no luck

You know, that article just show you the way, you need to change the value to your own proxy:
```
export HTTP_PROXY='http://127.0.0.1:Your_Port'
export HTTPS_PROXY='http://127.0.0.1:Your_Port'
```
If you are using socks5 proxy, you can try this:
```
export HTTP_PROXY='socks5://127.0.0.1:Your_Port'
export HTTPS_PROXY='socks5://127.0.0.1:Your_Port'
```

This is how python's requests get proxy, it should work.

**Comment by anfp** [comment]
> If you are using socks5 proxy, you can try this:
> 
> ```
> export HTTP_PROXY='socks5://127.0.0.1:Your_Port'
> export HTTPS_PROXY='socks5://127.0.0.1:Your_Port'
> ```
> 
> This is how python's requests get proxy, it should work.

Thanks, I did set socks5 proxy in the way like you suggested, somehow it still failed. executing
$ curl cip.cc  
shows the proxy setting is working, and returns the correct IP, but neither wget, curl nor webui works.
It’s like a wired Mac behavior.  Anyway I can live without the network function of civitai-helper, while enjoy other nice features of the the great extension.

**Comment by butaixianran** [comment]
In that case, you may need to set 
```
export HTTP_PROXY='http://127.0.0.1:Your_Port'
export HTTPS_PROXY='http://127.0.0.1:Your_Port'
````
Even you are using socks5. It is not an issue of Mac, it is an issue of the proxy software you are using.

**Comment by butaixianran** [comment]
Proxy is supported in new version v1.6. update.

**Comment by anfp** [comment]
> Proxy is supported in new version v1.6. update.
> 
> Also, check document for usage.

Thanks for your great effort! 
In my case, in civitai helper setting ’socks5h' instead of ’socks5’ works:
`socks5h:127.0.0.1:port`

**Comment by butaixianran** [comment]
good to know, closed
