### ISSUE TITLE
Does not work with custom model directory paths

### ISSUE THREAD

**Issue by williamkmlau** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#7]
does not work when using --ckpt-dir, --lora-dir command line arguments .

edit: I suggest using `shared.cmd_opts.lora_dir` `shared.cmd_opts.ckpt_dir` etc. to get model paths

**Comment by williamkmlau** [comment]
@butaixianran I added a PR to fix this to save you time.

**Comment by Thater** [comment]
Here's a simple fix for now.

# init
model_folders = {
    "ti": "embeddings",
    "hyper": os.path.join("models", "hypernetworks"),
    "ckp": os.path.join("models", "Stable-diffusion"),
    "lora": os.path.join("models", "Lora"),
}

if shared.cmd_opts.ckpt_dir is not None and os.path.isdir(shared.cmd_opts.ckpt_dir):
    model_folders["ti"] = shared.cmd_opts.embeddings_dir
if shared.cmd_opts.hypernetwork_dir is not None and os.path.isdir(shared.cmd_opts.hypernetwork_dir):
    model_folders["hyper"] = shared.cmd_opts.hypernetwork_dir
if shared.cmd_opts.ckpt_dir is not None and os.path.isdir(shared.cmd_opts.ckpt_dir):
    model_folders["ckp"] = shared.cmd_opts.ckpt_dir
if shared.cmd_opts.lora_dir is not None and os.path.isdir(shared.cmd_opts.lora_dir):
    model_folders["lora"] = shared.cmd_opts.lora_dir

**Comment by butaixianran** [comment]
It's done
