### ISSUE TITLE
New feautures

### ISSUE THREAD

**Issue by XimikaT** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#70]
Can you add new feautures, like delete models, move or rename

**Comment by butaixianran** [comment]
removing and re-naming will be in 2.0.

moving won't be there.

There will be a custom list function like YouTube's video list in 2.0, so no need to move a model's really location.

**Comment by kerror** [comment]
Would also be cool if it could check for duplicate hashes so we can find models/loras/textual inversions/etc that are doubled up in the directories that may have different names. This seems to be common on Civitae. Maybe a deduplication feature that asks which one to keep?

**Comment by MARTANFTM** [comment]
Nice work!, thx. What I'm personally missing is version filtering in "Extra Network" cards.
Filter for 1.5, 2.1 SD etc, for easily filter only compatible version between Checkpoints, LORAs etc. Creators rarely insert the version numbering in their files names and it is a mess to work with like trial and error if you have big content. Thank you
