### ISSUE TITLE
"🌐" button always open page in the host machine

### ISSUE THREAD

**Issue by AkazaRenn** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#72]
## Have you read document?

Yes

## Have you checked console log window's msg?

Yes

## Describe Issue

When accessing the web UI from a remote machine (launched with `--listen`), clicking the "🌐" button always open the model's Civitai page in the host machine. On the client machine which is actually accessing the web UI, nothing happened. It's probably better to assign the links directly to the buttons instead of solving the links on the go and open a page from the code.

## Screenshot for UI issue

N/A

## Console log's msg or screenshot for function issue

```
Civitai Helper: Start open_model_url
Civitai Helper: Start parse js msg
Civitai Helper: End parse js msg
Civitai Helper: Open Url: https://civitai.com/models/4468
Civitai Helper: End open_model_url
```

**Comment by butaixianran** [comment]
On this extension's tab, at the botton, there is an option called "Open Url with JS", check it, save the setting. Which will open url at client side. 

This option is checked by default. so, you unchecked it by carelessly?

**Comment by AkazaRenn** [comment]
@butaixianran I see! I was using the oldest version of its initial release, o which there are only two options in the settings. It never got updated because it was installed download from Civitai instead of GitHub. After update I can see the option you mentioned. Thanks!
