### ISSUE TITLE
After installing civit ai helper, the model and vae selection is not working. 

### ISSUE THREAD

**Issue by alternaassets** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#76]
After installing civit ai helper, the model and vae selection is not working also settings as well. Deleting the folder from the extension fixes the problem.I would be grateful if you could handle the bug.Great extension BTW.:)
![Screenshot_1](https://user-images.githubusercontent.com/119500977/228215861-492325c0-cdef-4728-b375-9518f5bea302.jpg)

**Comment by butaixianran** [comment]
Why you guys keep claiming other issues to this extension?
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9055

Don't you know you have updated SD webui?
