### ISSUE TITLE
[BUG] Missing Icons

### ISSUE THREAD

**Issue by JingJang** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#77]
## Describe Issue

When you refresh SD or when you refresh networks to see newly added models, the icons do not show themeslves for many models. 

## Screenshot for UI issue

This is models with icons shown.

![Snap4](https://user-images.githubusercontent.com/13469628/228267843-f3ce797f-c0c9-4871-8dd4-5641d7081062.jpg)

But if I add new networks and refresh or if I refresh SD page the icons for many models disappear, like image below.

![snap1](https://user-images.githubusercontent.com/13469628/228267874-c1caa5d4-48d8-48fa-a0ab-6743dd5d55e1.jpg)

**Comment by butaixianran** [comment]
Why you are so confident to claim it is a bug? If I can ban some users from openning issues, I'm gonna ban you.

![Snipaste_2023-03-28_22-20-20](https://user-images.githubusercontent.com/5558722/228268851-4c13b31b-9499-48cc-be33-372f1bda40f5.jpg)

**Comment by butaixianran** [comment]
**You have been blocked from all projects under this account because of following reason:**

**You don't read document, and you claim a basic feature as a bug because you don't know how to use it.** 

**What you should do:**
Read document, learn how to use a product before claiming claim it doesn't work. Only open an issue after you learned everything from document about a project.

**Comment by ShardM** [comment]
The "Refresh Civitai Helper" button does not appear. 

![Snap5](https://user-images.githubusercontent.com/27601923/228288962-e8235fad-e0b3-4728-a41f-2537ba0a5e5f.jpg)

I downloaded my SD yesterday with your extension afterwards.

**Comment by butaixianran** [comment]
Do you download SD webui from Official project repo?
There is a commit id at the bottom of your SD webui's page, that id is a url. Copy the whole url here.

**Comment by ShardM** [comment]
1) In console there are no errors

2) https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/91ae48fd7e20c60d6374f340cac0939f56d87048

3) version:1.5.7

**Comment by butaixianran** [comment]
This SD webui version need 1.6.x. It is already make it very clearly in civitai. And yet, you choose to ignore it. 

![Snipaste_2023-03-29_01-23-20](https://user-images.githubusercontent.com/5558722/228319426-7a9d67a6-ca22-4619-82f3-d15cd78f7070.jpg)

![Snipaste_2023-03-29_01-23-46](https://user-images.githubusercontent.com/5558722/228319448-a806fc4b-7c36-4cb1-b4bb-e95388328ed9.jpg)

**Comment by ShardM** [comment]
Not everyone understand github. I am a beginner and I just follow instructions from the website how to install. I just now learn how to find out verison number and I have to update manually.

**Comment by butaixianran** [comment]
If you download it from github, it should be latest version as default. 

Or, you download it when it only has v1.5.7, then didn't update your version before reporting issue.

**Comment by rakey0** [comment]
![image](https://user-images.githubusercontent.com/65669708/228487611-62931d25-2159-476a-8143-688a6c8865e4.png)
![image](https://user-images.githubusercontent.com/65669708/228487707-37973e22-a258-414b-af60-5bb579c9857b.png)
目前最新版本也有本地化问题,有选择语言的情况下只有Textual Inversion正常显示
切换成英文就完全正常了
![image](https://user-images.githubusercontent.com/65669708/228488009-366902f5-07d9-465a-8df0-33dd1ae80026.png)
再來把Civitai-HelperHelper版本切換成(2870a489c022be58d02d402f4547e2ee0c3f8ba4)就没以上问题了

**Comment by butaixianran** [comment]
你这个图片的中文化里面，不光是中文化，还改了格式，用了很多空格或者内嵌html脚本。


这个你应该向中文化的插件那边反馈，把图片上这段汉化的前后空格或内嵌html去掉。

**Comment by butaixianran** [comment]
我這邊試了下繁體語言插件，默認並沒有修改格式，但是你這個圖片上，“取代預覽”四個字，爲什麼是居中的？應該是靠左對齊才對。

你是啓用了雙語插件功能嗎？如果啓用了那個，是不會去支持的。

**Comment by rakey0** [comment]
居中的話是我有用(https://github.com/Gerschel/sd-web-ui-quickcss),本來以為是這個擴充功能導致的
後來發現確實是雙語插件導致無法正常顯示
