### ISSUE TITLE
Please remove __pycache__ from the repo

### ISSUE THREAD

**Issue by SLAPaper** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#78]
## Describe Issue
These are cache files of the python code and will be generated or updated after use, and will block the repo from update

## Screenshot for UI issue
![image](https://user-images.githubusercontent.com/7543632/228315815-80c7a08f-979c-4461-b46c-5fc2f14f6c4e.png)

**Comment by butaixianran** [comment]
done, my bad, re-named lib folder, forgot to update ignore file.
