### ISSUE TITLE
图片变得很小按钮堆在一起

### ISSUE THREAD

**Issue by akio1321** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#8]
![image](https://user-images.githubusercontent.com/26807288/223468326-2a89fae8-7a23-4ef8-b079-7efdf57ed969.png)
大概这个样子

**Comment by butaixianran** [comment]
hi, 本扩展是完全没有修改图片大小的，你停用本扩展，这个能恢复吗？

**Comment by akio1321** [comment]
不给大佬丢人了，我没自己改过这个设置，但是发现有一个设置把他改小了。可能是版本更新默认配置变化的原因。
![image](https://user-images.githubusercontent.com/26807288/223471954-1b15dd96-3fb1-4700-8edd-fc142ddb8197.png)

**Comment by ShinaPig** [comment]
Default view for Extra Networks 设置 thumbs 就会显示错误。
