### ISSUE TITLE
Feature Requests: 💡trigger words to prompt

### ISSUE THREAD

**Issue by id-fa** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#80]
- Remove LoRA if it is in the trigger keywords set by the author.
   (because it is often different from filename used)
 - Allow the actual LoRA to be added instead of the above.
    (this is a standard feature, but trigger keywords are rarely used without LoRA, so this button should allow them to be entered together).
 - Pop up UI to select the keyword to be used
   since some LoRAs are used by selecting from multiple trigger keyword candidates.
 - Enable to set the initial value of weight
   (since :1 is rarely used).
 - Add a comma after LoRA

**Comment by butaixianran** [comment]
won't do it
