### ISSUE TITLE
Enhancement:  Save "Model Type" selections for "Scan" & "Check New Versions from Civitai" 

### ISSUE THREAD

**Issue by jrittvo** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#81]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
It would be useful if the selected model types for the "Scan" and "Check New Versions from Civitai" functions were saved along with the other settings that are saved when using "Save Setting" on the Civitai Helper tab.  For instance, I always "scan" and "check new" for all 4 model types, but this does not match the default selections on startup, and I need to re-select each time the interface is restarted.

**Comment by butaixianran** [comment]
hi, I know this is needed. but as I mentioned in Document, there will be no more feature for version 1.x. 

These will be in 2.0 and you have to wait a few months for 2.0.

You can find a v2.0's UI demo video at beginning of the Document.

But, if there is pull request for this I can merge it
