### ISSUE TITLE
Feature request : renaming checkpoints and models using tags.

### ISSUE THREAD

**Issue by cguasti** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#82]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
Amazing work is being done with this extension, however, given the large number of files that we can end up having, it would be nice to have an option to rename the model, loras, hn, etc. files in a style like [user] [model] [version] [sdversion] [date] [etc].

I think this will allow us to quickly visualize models or loras when we have a large quantity in the library. I hope this isn't too much of a request, thank you for your work!

Hope you like the idea, regards.

**Comment by butaixianran** [comment]
You can change file name as you like. This extension uses hash and civitai ID, So no matter how you change file name, it gonna work.

**Comment by cguasti** [comment]
yeah i known that, but i'm refeering to add an option to rename all checkpoints with the custom or a default pattern inside this extension.

sorry, i'm don't really known how to do that besides doing it manually.

**Comment by butaixianran** [comment]
Won't do it, so closed
