### ISSUE TITLE
Get Model Info from Civitai by URL ->model选择建议增加输入字符过滤,并列列表使用首字母排序

### ISSUE THREAD

**Issue by orchie** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#84]
如今的 Get Model Info from Civitai by URL ->model 下拉列表中 ,对于几百个model的情况非常不友好 
建议首字母排序,并且增加一个输入过滤项(js可以实现)
感谢

**Comment by butaixianran** [comment]
![IMG_20230330_182838.jpg](https://user-images.githubusercontent.com/5558722/228808744-f412b961-d7bb-4b31-87af-14b4b3f4ea86.jpg)

**Comment by orchie** [comment]
> ![IMG_20230330_182838.jpg](https://user-images.githubusercontent.com/5558722/228808744-f412b961-d7bb-4b31-87af-14b4b3f4ea86.jpg)

我是因为发现了一个错误的lora信息,才决定反馈的,(虽然不知道他为什么会下载到另一个lora信息)
几乎所有的lora都可以正确下载,但有少部分不论是no info 或者 error info ,如果可以加上这个优化,会更方便.

**Comment by butaixianran** [comment]
可以提供那个lora的的civitai网页地址供测试

你可以删除那个lora的.info文件，再来列表里选

**Comment by butaixianran** [comment]
经过查证，是部分模型，在civitai的数据库中，保存了错误的sha256导致的。

这个无解了，因为本地计算sha256是正确的，但civitai数据库是错的。这不是插件能解决的。提交了问题给civitai，没有回应，估计他们也不打算处理了。

目前只能是删除.info文件，手动绑定到自己指定的模型上。

**Comment by orchie** [comment]
> 经过查证，是部分模型，在civitai的数据库中，保存了错误的sha256导致的。
> 
> 这个无解了，因为本地计算sha256是正确的，但civitai数据库是错的。这不是插件能解决的。提交了问题给civitai，没有回应，估计他们也不打算处理了。
> 
> 目前只能是删除.info文件，手动绑定到自己指定的模型上。

谢谢!
