### ISSUE TITLE
Download To SD - Doesnt delete file If version name has not changed.

### ISSUE THREAD

**Issue by TumnusB** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#85]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
When trying to use the Download Into SD button, the model wouldn't update due to the file existing.
## Screenshot for UI issue
https://www.imgpaste.net/image/KwMxaw
## Model Link
https://civitai.com/models/4597
## Console log's msg or screenshot for function issue
https://pastebin.com/H89Vfbc4
## Fixed via
Adding
os.remove(file_path) to the scripts/ch_lib/downloader.py at line number 102
This deletes the old file and then renames the .downloading file to the old file.

**Comment by butaixianran** [comment]
Done, check update
