### ISSUE TITLE
【提议】在使用lora时可以自动填入Tags

### ISSUE THREAD

**Issue by Erythritee** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#86]
lora在使用的时候，每次都要上civitai查lora对应的tag，不是很方便

**Comment by vanton** [comment]
![image](https://user-images.githubusercontent.com/3294943/229362304-c9936479-3ddc-48d4-a057-98c4779df6a6.png)

后面那个灯泡图标是自动填写 tag，标签图标是自动填写示意图的 prompts。
这是已有的功能。

**Comment by butaixianran** [comment]
无法理解提问的具体内容。开issue的用户没有清晰描述问题，并且没有后续回应。
因此本issue关闭。
