### ISSUE TITLE
feature request - move models into sfw/nsfw folders, thus allowing a sfw/nsfw working environment 

### ISSUE THREAD

**Issue by an303042** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#89]
Hey,
Thanks for this super helpful extension!
I came across this script in civitai - [https://civitai.com/models/26942/organize-models-script](https://civitai.com/models/26942/organize-models-script) and thought it would be a very suitable (and probably easy) addition to your extension. What it does is move models into folders, so you can "turn on" only the sfw folder when selecting models and not have a bunch of ditties on screen (if you are streaming or have kids around or whatever).
Please consider.
Thanks!

**Comment by Trahloc** [comment]
On a related note if this could let us use Tags to automatically save a file into a designated folder.  For example have a list of tags such as NSFW, SFW, Clothing, Inpainting, Negative, Pose, Style, Celebrity, Nobody, etc and they could be listed in a priority for auto sorting / easily be moved between various folders that would not only make this the Civitai download extension it'd be THE extension for sorting our collections.

**Comment by butaixianran** [comment]
Won't do it, everyone has their own way to categorize models. If you want a nsfw folder so much, just put nsfw models into a subfolder.

So closed.
