### ISSUE TITLE
 thumbs（小图式）显示错误

### ISSUE THREAD

**Issue by ShinaPig** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#9]
#8 
情况与此 issue 一致，原因为将 Default view for Extra Networks（附加网络默认视图）设置为 thumbs（小图式）。

**Comment by ShinaPig** [comment]
原 issue 未将情况说明清楚。当 Default view for Extra Networks（附加网络默认视图）设置为 thumbs（小图式）时，原先四个按钮会只显示三个。当鼠标想要选取🌐时，🖼会出现并覆盖🌐导致🌐无法选取。

**Comment by butaixianran** [comment]
hi，本扩展不适合小图模式。图片这么小，无法适应额外4个按钮，不打算适配。
