### ISSUE TITLE
4月4日下午无法获取预览图

### ISSUE THREAD

**Issue by jl0476** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#91]
## Have you read document?
yes
## Have you checked console log window's msg?
yes
## Describe Issue
4月4日下午，无法获取模型的预览图。日志如下：
获取预览图后未报错，就下一个了。
样例模型：
https://civitai.com/models/29203/xuanlu-chinese-celebrity-lora-model
https://civitai.com/models/29409/yukee-chen-or-chen-yu-qi-or

## Console log's msg or screenshot for function issue

Civitai Helper: Creating model info for: xuanluChineseCelebrity_xuanluV1.safetensors
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: 6fde820e06c6ad6cb0ebef829b93fe4108451db61b1fbb3dc96cd5b688236971
Civitai Helper: length: 37877651
Civitai Helper: Request model info from civitai
Civitai Helper: Write model info to file: I:\novelai-webui\novelai-webui-aki-v2\models\Lora\Realastic\xuanluChineseCelebrity_xuanluV1.civitai.info
Civitai Helper: Checking preview image for model: I:\novelai-webui\novelai-webui-aki-v2\models\Lora\Realastic\xuanluChineseCelebrity_xuanluV1.safetensors
Civitai Helper: Creating model info for: yukeeChenChenYuQi_v10.safetensors
Civitai Helper: Use Memory Optimized SHA256
Civitai Helper: sha256: 566631d501595feb7db296c106d1f0476f7c6535e5a6341cde19ee9ab3ffe774
Civitai Helper: length: 37864853
Civitai Helper: Request model info from civitai
Civitai Helper: Write model info to file: I:\novelai-webui\novelai-webui-aki-v2\models\Lora\Realastic\yukeeChenChenYuQi_v10.civitai.info
Civitai Helper: Checking preview image for model: I:\novelai-webui\novelai-webui-aki-v2\models\Lora\Realastic\yukeeChenChenYuQi_v10.safetensors

**Comment by butaixianran** [comment]
今天civitai迎来大更新，现在API里面，没有预览图数据了。

civitai发回来的模型信息里面，预览图部分，现在是这样：
```
"images":[]
```
都是空的。

这个要等civitai更新才能解决

**Comment by butaixianran** [comment]
All Images from civitai API service now are all empty. 

Check civitai's issue for more:
https://github.com/civitai/civitai/issues/414

**Comment by JustMaier** [comment]
@butaixianran This has been resolved.
