### ISSUE TITLE
When the language is localized, the shortcut for LoRA's trigger word no longer appears.

### ISSUE THREAD

**Issue by AI-Angels** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#92]
All features work correctly in the original language. 

However, when translated into foreign languages such as Japanese, the shortcut function for LoRA no longer works. The trigger word is displayed correctly on the TI, but it does not work only on LoRA.

**Comment by butaixianran** [comment]
which version are you using, update your version.

**Comment by AI-Angels** [comment]
Thank you for your comment.

I'm using 30bf55f0.

Also, if I don't use the localization extension, I can use the shortcut for LoRA's trigger word on LoRA.

Just to confirm, the file you used is the following.
https://github.com/Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP

**Comment by butaixianran** [comment]
I mean this extension's version number, at the bottom of this extension's tab page. Not SD webui's version number.

**Comment by AI-Angels** [comment]
Sorry, I'm actually using version 1.6.2. And I'm using the latest version of the web UI. 
I've tried pressing the refresh or reload button on the LoRA screen, but it still only works on TI.

**Comment by AI-Angels** [comment]
After deleting the localization-ja_JP folder and reinstalling the localization file, I pressed the refresh button and it started to appear. 
I need to press the LoRA refresh button every time I reload the screen, but it works for now.

**Comment by butaixianran** [comment]
That should not happen, I tested with Chinese, Japanese and Korean localization extensions. The extension you used "Katsuyuki-Karasawa/stable-diffusion-webui-localization-ja_JP" is tested and works well. 

Is that all addtional buttons doesn't show, or those buttons displayed, but they won't add any word to prompt?

If additional button didn't show, what you need is to press the blue refresh icon, not the "リフレッシュ" button.

**Comment by butaixianran** [comment]
I guess you have your buttons back after clicking "refresh" icon button?

So, this issue is closed. If your issue is still there, you can reply and we can re-open this issue.
