### ISSUE TITLE
区域重叠遮挡问题

### ISSUE THREAD

**Issue by gustavmilo** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#93]
![aa](https://user-images.githubusercontent.com/129682674/230047227-021bd362-823c-4079-8f9e-8cd7430a2838.jpg)
1、如图红色剪头所示，标签栏有时候会变成两行，对缩略图的遮挡过多，以至于影响图示的分辨和识别
2、如绿色箭头所示，当名字很长时，会对标签遮挡无法操作
希望对以上两项内容能有所优化，谢谢

**Comment by vanton** [comment]
更新下，应该已经没这个问题。
另外，如果你是 card 模式，可以设置宽度高度的。

**Comment by butaixianran** [comment]
一个名字就能把整个图片盖满的图片尺寸，哪有空间优化

既然自己选择缩略图模式 ，就接受这个结果

**Comment by gustavmilo** [comment]
> 
名字长因为只是鼠标悬停才会展开，当鼠标悬停的时候多半是要对标签进行操作

**Comment by butaixianran** [comment]
你自己都说了，要操作的时候就会展开，展开就会盖住。

你为什么不去给sd webui官方提意见让他们把图片尺寸改大呢。你对这个图片很满意的话，那就接受这个结果。对图片尺寸不满意的话，就给sd webui官方提意见让他们把尺寸改大。
