### ISSUE TITLE
Download / Update Suggestion

### ISSUE THREAD

**Issue by LumberingTroll** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#94]
I would really appreciate when updating a Ckpt, Lora, TI, etc. it had the option of setting the updater to delete previous version before downloading the new version. Right now I manually go in and remove them, its not a huge task, just a QoL suggestion.

I appreciate the extension, its very helpful!

**Comment by butaixianran** [comment]
Wait for 2.0

**Comment by Janzoooo** [comment]
是的，我觉得增加一个选择提示是否删除或者覆盖之前的版本会比较好

**Comment by SilberComic** [comment]
any update on 2.0? removing old versions is sometimes a bit tricky since the versionnames are missing sometimes @butaixianran
