### ISSUE TITLE
模型和LORA區域不會顯示按鈕

### ISSUE THREAD

**Issue by nacl1415** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#96]
SD已更新至最新，並且插件使用最新版本ea6e121f 
我的SD有使用中文化，Textual Inversion那邊可以正常顯示按鈕
但切換標籤至模型和LoRa區域的時候，預覽圖那邊就無法顯示按鈕了
只有Textual Inversion那個區域有正常顯示按鈕而已，其他均無法正常顯示

**Comment by butaixianran** [comment]
蓝色图标的刷新按钮点了吗

**Comment by nacl1415** [comment]
大佬您好~我有看文檔
直到您PO了圖片我才知道我點錯了按鈕
我之前都是按左邊灰色那個按鈕，我這邊是顯示"重新整理"
所以主要原因是 我一直按錯按鈕 才導致沒有顯示按鈕
感謝大佬解惑

**Comment by butaixianran** [comment]
你的說法不合理。點擊藍色刷新按鈕，文檔是截圖強調的。

你已經被封禁。

今後開issue之前請先看文檔

**Comment by butaixianran** [comment]
这个issue放在这作为example。

**Comment by divineblessing** [comment]
![微信截图_20230406221757](https://user-images.githubusercontent.com/129473727/230405682-7729931d-965f-4b01-8e12-51db79936dde.png)

真棒，我刚上来想跟你分享我也找到是这个启动器同步汉化的原因。

但是看到你的回复，就你这样的心态，还想做好插件？好的插件不是应该都兼容任何场合吗？

你觉得别人没事找事做，找你们插件的麻烦？挑刺？别费劲了，就你这种言行，你不配！

再说，如果我会写代码，还会需要问到你吗？不会动动脑子？动不动上来就说封禁，真厉害哦。

我看你们团队也都是人才吧，怎么会说出这么没质量的话？你们能开源真的替你们团队感到高兴跟开心，但是就你这心态不配待在你们团队吧，估计团队里的人早都看你不爽了，说话都不带脑子的，我行我素，你以为你是谁？

俗话说得好，解决提出问题的人就是解决问题，不要告诉我这是你们团队的宗旨！

玻璃心就别出来做插件了，真的，真心劝你。

我已经把你拉黑了，并且卸载你们的插件，我不需要你这样的人写的插件！

最后谢谢你解决了我的python的问题。

此话题关闭，别再来烦我，你这个玻璃心！

**Comment by butaixianran** [comment]
楼上这个 divineblessing 的行为，和恶意找茬区别很小，而我当时也只是警告，没有拉黑。

对不了解情况的人，我来描述一下楼上的行为。

他使用秋叶启动器，勾选了实验性质的“云端翻译”功能，上面有个巨大的警告提示，说这个功能会替换掉SD webui内置的整个翻译系统。

然后，他勾选之后，导致本扩展不起作用了。他没有说去折腾启动器，跑来说本扩展无效。

然后我耐心一步步帮他查找，告诉他，有个SD webui内置的翻译功能没有生效，并询问他用的什么翻译工具。

到此，他已经多次使用秋叶启动器，即使我反复告诉他，是SDwebui内置翻译功能失效了，他都没有提到，他勾选了“云端翻译”。

在我问他用的什么翻译工具的时候，他依然不提他勾选了启动器的“云端翻译”，而是提供一个github的油猴脚本，说他的翻译用的是那个油猴脚本。

后面，油猴脚本停掉之后，我教他如何测试SD webui的内置功能，到底有没有加载。测试结果是，根本没有加载。

**于是，我告诉他，这不是任何插件能改的，只有你那个启动器能改。即使如此，他还是只字不提他勾选了“云端翻译”实验功能。**

全过程中，他最少需要使用秋叶启动器5次以上，我们询问、强调这个问题，也超过5次以上。就是只字不提自己做过的事情，完全不看启动器上，自己勾选了什么。

这和恶意找茬已经没有区别了。

恶意找茬是什么样的：不是这个产品的问题，找茬的人做了改动，然后一口咬定是这个产品的问题。客服测试出来，产品被改动了，明确问对方有没有改，找茬的人，依然只字不提自己的改动，继续咬定是产品问题。

楼上的言论，他现在还在说这种话：“好的插件不是应该都兼容任何场合吗？”

你自己把SD webui内置基本功能都改掉了，现在还在叫让插件去兼容。这和找茬，还有什么区别呢。

你已经被拉黑。

**Comment by ivever2** [comment]
我觉得多点包容吧，大家也不都是技术大牛，很多人看了教程也不一定能看懂。而且这个图标问题我也出现了，我也点了蓝色按钮还是不那4个按钮，反复看了教程，反复重装插件都没办法。看到这个帖子里的divineblessing贴出的这个图才知道是汉化导致的。大家都是有共同爱好走到一起的，和气最重要。这都翻墙到外网了，言论自由点就没必要玩CPC那套严刑峻法了。

**Comment by butaixianran** [comment]
> 我觉得多点包容吧，大家也不都是技术大牛，很多人看了教程也不一定能看懂。而且这个图标问题我也出现了，我也点了蓝色按钮还是不那4个按钮，反复看了教程，反复重装插件都没办法。看到这个帖子里的divineblessing贴出的这个图才知道是汉化导致的。大家都是有共同爱好走到一起的，和气最重要。这都翻墙到外网了，言论自由点就没必要玩CPC那套严刑峻法了。

你声称你反复看教程，然而你根本没有。因为这个问题已经添加到文档的常见问题部分。而且，文档顶部，有链接一键跳转到常见问题章节。

他被封禁的原因我在另一个帖子已经描述的非常清楚了。根本不是是否了解技术的问题。我已经正面提问了：用的什么翻译，问题出在翻译工具。反复强调了那么多次，对方要么给出错误的回答，要么避而不提。

就像我在另一帖举例，你把手机换成砖头，说充电器不起作用，我反复正面问你手机是不是有改动，你还避开不提。这和技术有什么关系。

**Comment by GodisGod** [comment]
> 

劝别人大度总是很容易
