### ISSUE TITLE
同楼下一样的问题，模型和LORA區域不會顯示按鈕，按了刷新也没用。

### ISSUE THREAD

**Issue by divineblessing** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#97]
civitai可以扫描并且下载模型相应的信息，但是功能就是用不了。以前刚安装的时候可以用，现在的情况是4个按钮也没有，点击模型文件名也不会在tags栏里面创建tags。有没有的懂哥解答下，感谢！

**Comment by divineblessing** [comment]
![微信图片_20230406111321](https://user-images.githubusercontent.com/129473727/230263231-d64da520-2953-43c2-8bb6-9be1100bb011.jpg)

**Comment by divineblessing** [comment]
SD版本，插件全是最新的New New New

**Comment by butaixianran** [comment]
蓝色刷新按钮点了吗？ 
![](https://raw.githubusercontent.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/main/img/refresh_ch.jpg)

提供3个信息：
* 使用的本扩展版本号是多少？版本号在扩展tab页面最下方。
* 使用的SD webui的gradio版本号是多少？gradio版本号在SD webui页面最下方
* 使用的SD webui的commit编号多少？SD webui的commit编号在页面最下方，有个 commit的编号，那个编号是个链接，整个链接复制过来。

**Comment by divineblessing** [comment]
> 蓝色刷新按钮点了吗？ ![](https://raw.githubusercontent.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/main/img/refresh_ch.jpg)
> 
> 你也是一样，不点蓝色刷新按钮，等着被封禁吗？我可以把那个人的回复贴过来。

点了没用，你以为我没点吗？

**Comment by divineblessing** [comment]
I don't know what's wrong with me, I followed the documentation, all the plug-ins are up to date, and the SD version is also the latest, I also clicked the blue refresh button, but it just doesn't work, maybe my luck is too bad?

**Comment by divineblessing** [comment]
![微信图片_20230406114225](https://user-images.githubusercontent.com/129473727/230266771-d5c0da82-f22e-48c6-be94-121830242ab8.png)
![微信图片_20230406114249](https://user-images.githubusercontent.com/129473727/230266777-d0d26a16-8d3c-46d4-81f0-792a9e0bb600.png)

**Comment by butaixianran** [comment]
提供3个版本号：
* 在这个扩展tab页面最下方，扩展的版本号
* 在sd webui页面最下方gradio的版本号
* 在sd webui页面最下方，有个commit hash编号，那个编号是个链接，把整个链接地址复制过来

另外，打开模型卡片列表的时候，按下F12，选择console页面，保持它开着。这时候点击蓝色刷新按钮，看是否有报错。如果有报错，把报错信息提供过来。

不要提供那个启动器的内容，那个不是标准，更新日期没有参考价值。从那个启动器更新插件，甚至不是从官方项目池更新，而是从那个启动器作者自己复制的程序池更新。它去年10月份复制，你哪怕今天更新，也还是去年10月份的版本。

**Comment by divineblessing** [comment]
![q1](https://user-images.githubusercontent.com/129473727/230279159-b654aebc-8a43-47a8-aaac-b267abdbdd18.png)
![q2](https://user-images.githubusercontent.com/129473727/230279169-0b3e90b0-c28e-4cb1-94df-2ea5935496f7.png)
commit hash:https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

**Comment by divineblessing** [comment]
Uncaught ReferenceError: getTranslation is not defined
    at HTMLButtonElement.update_card_for_civitai (civitai_helper.js?1680751934.900948:385:36)
update_card_for_civitai @ civitai_helper.js?1680751934.900948:385
127.0.0.1/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
userscript.html?name=%25E7%25BD%2591%25E9%25A1%25B5%25E9%2599%2590%25E5%2588%25B6%25E8%25A7%25A3%25E9%2599%25A4(%25E6%2594%25B9).user.js&id=abdc24f6-4bd8-4372-9660-a25ea044c73a:842 关闭了快捷键
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/fe97e0b867c348d00e29928cb6f4f07ff3842a8eab7f817f8eaccd01035b93c5.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/fe97e0b867c348d00e29928cb6f4f07ff3842a8eab7f817f8eaccd01035b93c5.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/fe97e0b867c348d00e29928cb6f4f07ff3842a8eab7f817f8eaccd01035b93c5.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/sm/fe97e0b867c348d00e29928cb6f4f07ff3842a8eab7f817f8eaccd01035b93c5.map: System error: net::ERR_BLOCKED_BY_CLIENT
civitai_helper.js?1680751934.900948:385 Uncaught ReferenceError: getTranslation is not defined
    at HTMLButtonElement.update_card_for_civitai (civitai_helper.js?1680751934.900948:385:36)
update_card_for_civitai @ civitai_helper.js?1680751934.900948:385

**Comment by butaixianran** [comment]
前面提到的3个版本号呢？

getTranslation是webui内置的功能，而且内置很久了。没有这个功能，说明你的sd webui是个非常非常老的版本。

而你却一口咬定你都是最新版。

**Comment by divineblessing** [comment]
版本号在截图第一张最下面那一排，getTranslation我不知道什么。对于写代码你是内行，我是外行。我用的是B站秋叶的最新整合包至少是今年2月份或者3月份的，我不知道这个版本有多老。但是我确实是无法使用你这个插件，至少现在不能，之前可以用的。

**Comment by butaixianran** [comment]
你这个版本非常老，你还在咬定是新的。升级你的SD webui吧。

**Comment by divineblessing** [comment]
![微信图片_20230406134643](https://user-images.githubusercontent.com/129473727/230282836-3864569b-0c7e-4a39-b235-8061d03f0a8b.png)

**Comment by divineblessing** [comment]
这个算老吗？

**Comment by butaixianran** [comment]
我前面明确说了吧，你这个更新事件根本不算数。你是在这个启动器作者复制的程序池更新。它去年10月份复制，你哪怕今年更新，也还是去年10月份的内容。我前面难道没有说一模一样的话吗

**Comment by divineblessing** [comment]
誒，既然用了你的插件，那我作为你的用户，站在用户角度说下吧。专业的东西，你才是专业的，能解决问题才是你最关心的问题。我相信秋叶的启动器会与时俱进，你在及时回复我也说明你在认真对待用户。感谢你耐心解答，我没问题了。

**Comment by butaixianran** [comment]
我让你提供完整的commit链接过来，你也不提供。让你提供本扩展的版本号，你也不提供。明确告诉你了，原因是你的sd版本太旧，原因前面也告诉你了，你还要拿启动器截图来当证据。

如果你不是想解决问题，只是想一口咬定启动器都是对的，那你可以留在启动器的圈子，让那边解决。你就把启动器当个和这个不一样的独立软件。

**Comment by divineblessing** [comment]
commit链接 上面不是提供了吗？

**Comment by divineblessing** [comment]
![微信图片_20230406135607](https://user-images.githubusercontent.com/129473727/230284257-ad089365-c85f-45a9-8670-ae2a6a935ea7.png)

在sd webui页面最下方，有个commit hash编号，那个编号是个链接，把整个链接地址复制过来：https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9fed7c364061ae6efb37f797b6b522cb3cf7aa2

**Comment by divineblessing** [comment]
在这个扩展tab页面最下方，扩展的版本号。这个在哪个位置？我没看懂

**Comment by butaixianran** [comment]
你可以去SDwebui的目录下面，打开这个文件：
`stable-diffusion-webui\javascript\localization.js`

看里面第56行左右，有没有
`function getTranslation(text)`
这个内容

**Comment by butaixianran** [comment]
你可以在这个文件里面搜索，看有没有`function getTranslation(text)`这一行

**Comment by divineblessing** [comment]
![微信图片_20230406140203](https://user-images.githubusercontent.com/129473727/230285349-d7792af0-30f3-4ff0-bd67-dd3a6c5a6d3c.png)

**Comment by butaixianran** [comment]
有这一行，那就说明你的SD webui在启动的时候，就出错了。根本没有正常启动，所以插件才找不到这个方法。

那就重启你的SD webui，盯着它的命令行窗口，看它启动的时候，报了什么错误。

**Comment by divineblessing** [comment]
![微信图片_20230406140533](https://user-images.githubusercontent.com/129473727/230285887-7f04be47-7331-42fb-aca3-6452e75cf9ec.png)

**Comment by butaixianran** [comment]
我测试了你这个版本，是可以正常加载这个getTranslation内置功能的，没有任何问题。

需要你提供两个东西：
* 去Civitai助手 的 标签页面，最下面，有个版本号，复制过来
* 去设置页面，有个“重启webui”的大按钮。先打开F12，console页面，一直开着。然后点击这个重启按钮。
接下来，在重启的时候，看console页面有报什么错误。把错误复制过来。

**Comment by divineblessing** [comment]
[127.0.0.1-1680761981156.log](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/files/11166996/127.0.0.1-1680761981156.log)

Civitai助手 的 标签页面版本号：version:1.6.2

**Comment by butaixianran** [comment]
你用的什么翻译插件？你的翻译插件，抢在系统内置功能加载之前报错了，所以后面的东西都没有加载

**Comment by butaixianran** [comment]
你用的这个是什么东西，还不光是翻译，他在修改SDwebui，而且出错了
https://github.com/qxinGitHub/Remove-web-limits-
userscript.html

**Comment by divineblessing** [comment]
Tampermonkey油猴的插件     ：   chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/options.html#nav=a9ecdc0d-7940-4a10-a27b-caa6aa371c0f+editor

**Comment by divineblessing** [comment]
https://github.com/zyufstudio/TM/tree/master/webTranslate

**Comment by butaixianran** [comment]
你把油猴整个停掉再试试看

**Comment by divineblessing** [comment]
我刚才卸载了油猴，重启电脑，重新开了SD还是跟之前的问题一样

**Comment by butaixianran** [comment]
建议改用SDwebui的翻译插件，外面的翻译脚本都会修改js，改了什么是不知道的。冲突概率高。

**Comment by butaixianran** [comment]
为什么你的浏览器插件能在127.0.0.1的环境下运行？默认是禁止的。

**Comment by divineblessing** [comment]
本地部署的SD 不都是这个链接吗？http://127.0.0.1:7860 别人的视频教程也是这个链接

**Comment by butaixianran** [comment]
是的，这是本地地址，浏览器扩展应该是无法生效的，除非你手动让浏览器扩展对本地地址生效。

**Comment by divineblessing** [comment]
我没有改过任何东西，安装SD的时候也是跟着视频教程安装的。

**Comment by butaixianran** [comment]
关掉翻译扩展，用SD自带的汉化插件。然后还是像刚才一样：
* 重启webui的时候，看console里面有什么报错
* 点击蓝色刷新按钮的时候，看console里面有什么报错。

**Comment by divineblessing** [comment]
稍等，我把浏览器所有的拓展程序都关了，重启电脑，再按照你说的做

**Comment by butaixianran** [comment]
这和SD没关系，这是在浏览器扩展设置那边改的。以前没有手动改过的话，浏览器扩展是无法对本地地址生效的

**Comment by butaixianran** [comment]
没有必要重启

**Comment by divineblessing** [comment]
![微信图片_20230406144738](https://user-images.githubusercontent.com/129473727/230293661-fe9bb7cf-a824-4bc7-a68d-5c98b698bac0.png)


F12  console：   index.js?f96c80f1:3418 method Pause []
index.js?f96c80f1:3418 return {target: Window, origin: 'http://127.0.0.1:7860', data: {…}}
index.js?1680534085.639948:1 Method Pause MessageEvent {isTrusted: true, data: {…}, origin: 'http://127.0.0.1:7860', lastEventId: '', source: Window, …}
civitai_helper.js?1680751934.900948:385 Uncaught ReferenceError: getTranslation is not defined
    at HTMLButtonElement.update_card_for_civitai (civitai_helper.js?1680751934.900948:385:36)
update_card_for_civitai @ civitai_helper.js?1680751934.900948:385

**Comment by divineblessing** [comment]
[127.0.0.1-1680763833053.log](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/files/11167189/127.0.0.1-1680763833053.log)

**Comment by butaixianran** [comment]
你需要测试下，内置本地化脚本到底有没有加载。

你需要打开`stable-diffusion-webui\javascript\localization.js`

在文件最前面插入一行：
`console.log("start localization.js");`
然后到文件最后面插入一行：
`console.log("end localization.js");`

然后去设置页面，按F12打开console窗口，保持打开的时候，点击 重启Webui。然后盯着命令行，看是否有输出
`start localization.js
和`
`end localization.js`

**Comment by butaixianran** [comment]
另外，问一下，你每次启动sdwebui，都是用启动器启动的吗？

**Comment by divineblessing** [comment]
用启动器启动看了几遍，代码跳得很快，没有发现。用webui-user.bat启动，显示我没有安装python，但是确实是安装了并且配置了环境

**Comment by butaixianran** [comment]
这个
start localization.js 和
end localization.js
显示了吗？在浏览器的console里面

**Comment by divineblessing** [comment]
启动器运行的版本没有搜索到start localization.js 和
end localization.js

**Comment by butaixianran** [comment]
说了不是启动器，为什么老要盯着启动器呢。浏览器按下F12，console面板里面

**Comment by divineblessing** [comment]
是在浏览器按下F12，console面板里面看的  看了几遍跟搜索关键字了

**Comment by divineblessing** [comment]
[127.0.0.1-1680766489613.log](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/files/11167530/127.0.0.1-1680766489613.log)

**Comment by butaixianran** [comment]
如果没有，那就是运行环境被改了，这不是任何扩展能改的，只有那个启动器能做到。

你必须成功使用webui-user.bat运行。

按下ctrl+R，输入cmd，打开windows命令行窗口，在里面输入：
`pythong --version`
回车，看会不会输出python版本号

不会，就说明你的python环境没有配置正确。把这个东西弄对了，再用webui-user.bat运行。

**Comment by divineblessing** [comment]
正在解决python不存在的问题

**Comment by butaixianran** [comment]
你是用conda安装的python吗？

**Comment by divineblessing** [comment]
谢谢你的帮忙，我晚上回去重装电脑，远程操作家里的电脑有点吃力。如果有最新的进展，我会回来留言

**Comment by divineblessing** [comment]
我是直接从python官网上下载的python-3.10.8-amd64，然后运行安装并且勾选了安装到环境

**Comment by butaixianran** [comment]
不要搞重装系统这种事。没有必要。装python就行了。

另外，你可以用记事本打开 webui-user.bat 这个文件，看看里面每一行的 等于 符号 后面，有哪些参数。如果有参数，复制过来。尤其是`set COMMANDLINE_ARGS=` 这一行。

**Comment by divineblessing** [comment]
问题是我已经安装了，检查了环境，也有python路径在上面。真玄。

@echo off

if not defined PYTHON (set PYTHON=python)
if not defined VENV_DIR (set "VENV_DIR=%~dp0%venv")


set ERROR_REPORTING=FALSE

mkdir tmp 2>NUL

%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :check_pip
echo Couldn't launch python
goto :show_stdout_stderr

:check_pip
%PYTHON% -mpip --help >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
if "%PIP_INSTALLER_LOCATION%" == "" goto :show_stdout_stderr
%PYTHON% "%PIP_INSTALLER_LOCATION%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
echo Couldn't install pip
goto :show_stdout_stderr

:start_venv
if ["%VENV_DIR%"] == ["-"] goto :skip_venv
if ["%SKIP_VENV%"] == ["1"] goto :skip_venv

dir "%VENV_DIR%\Scripts\Python.exe" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv

for /f "delims=" %%i in ('CALL %PYTHON% -c "import sys; print(sys.executable)"') do set PYTHON_FULLNAME="%%i"
echo Creating venv in directory %VENV_DIR% using python %PYTHON_FULLNAME%
%PYTHON_FULLNAME% -m venv "%VENV_DIR%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv
echo Unable to create venv in directory "%VENV_DIR%"
goto :show_stdout_stderr

:activate_venv
set PYTHON="%VENV_DIR%\Scripts\Python.exe"
echo venv %PYTHON%

:skip_venv
if [%ACCELERATE%] == ["True"] goto :accelerate
goto :launch

:accelerate
echo Checking for accelerate
set ACCELERATE="%VENV_DIR%\Scripts\accelerate.exe"
if EXIST %ACCELERATE% goto :accelerate_launch

:launch
%PYTHON% launch.py %*
pause
exit /b

:accelerate_launch
echo Accelerating
%ACCELERATE% launch --num_cpu_threads_per_process=6 launch.py
pause
exit /b

:show_stdout_stderr

echo.
echo exit code: %errorlevel%

for /f %%i in ("tmp\stdout.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stdout:
type tmp\stdout.txt

:show_stderr
for /f %%i in ("tmp\stderr.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stderr:
type tmp\stderr.txt

:endofscript

echo.
echo Launch unsuccessful. Exiting.
pause

**Comment by butaixianran** [comment]
你看错文件了，是 webui-user.bat，不是webui.bat

另外，如果你知道你的python运行文件在哪个目录，你可以在webui-user.bat里面设置：
`set python=你的python程序路径`

**Comment by divineblessing** [comment]
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=

call webui.bat

**Comment by divineblessing** [comment]
! 我试下

**Comment by butaixianran** [comment]
你确定你安装了python的话，就可以设置
`set PYTHON=你的python路径`，不需要重装python

**Comment by divineblessing** [comment]
![801ccb4749b7215fad01eda027d483b](https://user-images.githubusercontent.com/129473727/230311905-28d6cb79-136c-4fca-82ee-7a8be8844b21.png)

**Comment by butaixianran** [comment]
看看这个：
https://cloud.tencent.com/developer/article/1652685

**Comment by butaixianran** [comment]
这个清晰一点：
https://lanlan2017.github.io/blog/be9b7855/

**Comment by butaixianran** [comment]
另外，从你的描述和出错看，你的python是安装在了虚拟环境中，直接运行是运行不了的。要先启动那个环境，才能使用python。

**Comment by divineblessing** [comment]
根据你上面的关闭之后 没问题了  C:\Users\Administrator>python
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by butaixianran** [comment]
运行webui-user.bat，不适用启动器

**Comment by divineblessing** [comment]
![cf0fe86877008a1473869308fe6b113](https://user-images.githubusercontent.com/129473727/230316582-6874a125-dd17-499c-8299-bdb406ad8ec4.png)

**Comment by butaixianran** [comment]
所以说了，你的python应该是安装在了虚拟环境中，要先启动虚拟环境。

没有任何必要重装系统，直接从python官网，安装个新的python，然后把这个新的python，添加到环境变量。不要使用conda。

**Comment by divineblessing** [comment]
晚上我回去严谨的重新装一遍，待我后续

**Comment by butaixianran** [comment]
找到原因了，秋叶启动器里面，有个同名的"localization.js"文件，把原版的覆盖了。这个文件里，他把"getTranslation"方法，修改之后，塞到了一个封装函数里面，于是只有它自己能用，别人用不了。

你继续折腾吧，我原因找到了，也不是本插件的问题，不在乎了。

**Comment by butaixianran** [comment]
你勾选了秋叶启动器的"云端汉化"功能是吧。就是这个造成的。

查了这么长时间，多次提到翻译，出错的命令还是getTranslation。你都没有想到你自己勾选了“云端汉化”？

**Comment by butaixianran** [comment]
这个问题关闭，以后你再因为你用启动器做了什么关键操作你自己忘了，跑来说我们的插件不起作用，就直接封禁。

**Comment by butaixianran** [comment]
你因为在另一個issue低素质的谩骂，所以被封禁了。

**这里给其他人解释一下警告的原因：**
警告这个divineblessing，并不是因为他忘了自己做了什么操作。**而是因为，整个过程，他面对启动器界面很多次，我们也正面询问多次，正面强调多次，他依然对自己使用启动器所做的改动只字不提。**

divineblessing的行为，已经构成了找茬行为，所以被警告。在被警告后，他低素质的谩骂，构成了恶意行为，所以被封禁。

因为，在我们如此多次的正面提问、正面强调下，不是忘了就能混过去的。而且，不管是忘了，还是他认为秋叶启动器100%是对的，其他东西都应该适应启动器。不管心理活动是哪种，只要在行为上，和恶意找茬相同，那么，就是恶意找茬。  

就像开车闯了红灯，造成事故，不是一句你忘了踩刹车就等于你没有违规。  

事件的描述参见：
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/issues/96#issuecomment-1500310981
