### ISSUE TITLE
建议把点击additional 的按钮切换additional的显示隐藏。

### ISSUE THREAD

**Issue by lsjspl** [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#99]
建议把additional 的按钮，点击切换additional的隐藏显示状态。
一般用小的卡片，additional的div正好挡住了大部分小卡片的图片，非常影响使用，建议点击按钮的时候可以切换显示隐藏，而不是一直显示。
![image](https://user-images.githubusercontent.com/2315298/230655332-0e59a40c-576c-41dd-947b-d73a3569a9ed.png)

**Comment by butaixianran** [comment]
![Snipaste_2023-04-08_02-27-17](https://user-images.githubusercontent.com/5558722/230659209-aa2b8e17-ec1c-45a6-bf8e-b1e8bd51c14c.jpg)

上图提到的这个css问题，是SDwebui在gradio 3.16.2时代的问题，gradio 3.23的时代已经没有了。但我不认为所有人都会升级到gradio 3.23的版本。尤其是国内使用打包版本和启动器的人。实际上，韩国也有很多人使用打包版本。

所以，这个问题目前不打算解决。

**Comment by lsjspl** [comment]
> ![Snipaste_2023-04-08_02-27-17](https://user-images.githubusercontent.com/5558722/230659209-aa2b8e17-ec1c-45a6-bf8e-b1e8bd51c14c.jpg)
> 
> 上图提到的这个css问题，是SDwebui在gradio 3.16.2时代的问题，gradio 3.23的时代已经没有了。但我不认为所有人都会升级到gradio 3.23的版本。尤其是国内使用打包版本和启动器的人。实际上，韩国也有很多人使用打包版本。
> 
> 所以，这个问题目前不打算解决。

我刚才在其他issues看到了，麻烦把这个issues给删除或者关闭吧
